http://localhost:5984/
Welcome
http://localhost:5984/svtdev
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/allbgpNeighbours.yaml
Checking for collect existence
http://localhost:5984/svtdev/_design/admin/_view/isnewcollect?reduce=true&startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]&group_level=2
http://localhost:5984/svtdev/_design/nsx-edge/_view/bgpNeighbours?startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]
{
    "data": {
        "nsx-1": {
            "nsx-edge": {
                "edge-19": {
                    "bgpNeighbours": {}
                },
                "edge-20": {
                    "bgpNeighbours": {}
                },
                "edge-21": {
                    "bgpNeighbours": {}
                },
                "edge-28": {
                    "bgpNeighbours": {}
                },
                "edge-29": {
                    "bgpNeighbours": {}
                },
                "edge-30": {
                    "bgpNeighbours": {}
                },
                "edge-32": {
                    "bgpNeighbours": {}
                },
                "edge-33": {
                    "bgpNeighbours": {}
                },
                "edge-36": {
                    "bgpNeighbours": {}
                },
                "edge-37": {
                    "bgpNeighbours": {}
                },
                "edge-38": {
                    "bgpNeighbours": {}
                },
                "edge-6": {
                    "bgpNeighbours": {}
                },
                "edge-7": {
                    "bgpNeighbours": {}
                },
                "edge-9": {
                    "bgpNeighbours": {}
                }
            }
        },
        "nsx-2": {
            "nsx-edge": {
                "edge-10": {
                    "bgpNeighbours": {}
                },
                "edge-12": {
                    "bgpNeighbours": {}
                },
                "edge-15": {
                    "bgpNeighbours": {}
                },
                "edge-27": {
                    "bgpNeighbours": {}
                },
                "edge-28": {
                    "bgpNeighbours": {}
                },
                "edge-31": {
                    "bgpNeighbours": {}
                },
                "edge-32": {
                    "bgpNeighbours": {}
                },
                "edge-33": {
                    "bgpNeighbours": {}
                },
                "edge-36": {
                    "bgpNeighbours": {}
                },
                "edge-38": {
                    "bgpNeighbours": {}
                },
                "edge-39": {
                    "bgpNeighbours": {}
                },
                "edge-40": {
                    "bgpNeighbours": {}
                },
                "edge-8": {
                    "bgpNeighbours": {}
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
