Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/app.yaml
Checking for collect existence
{
    "data": {
        "nsx-1": {
            "nsx-appliance": {
                "manager": {
                    "cpuInfoDto": {
                        "capacity": "2900 MHZ",
                        "freeCapacity": "2096 MHZ",
                        "totalNoOfCPUs": 4,
                        "usedCapacity": "804 MHZ",
                        "usedPercentage": 28
                    },
                    "versionInfo": {
                        "buildNumber": "3102213",
                        "majorVersion": "6",
                        "minorVersion": "1",
                        "patchVersion": "5"
                    }
                },
                "network": {
                    "dns": {
                        "domainList": "utility.pge.com net.pge.com conf.pge.com",
                        "ipv4Dns": [
                            "172.24.13.44",
                            "172.24.14.44"
                        ],
                        "ipv6Dns": null
                    },
                    "hostName": "itcldrcnsxmgt01",
                    "networkIPv4AddressDto": {
                        "interfaceInfo": null,
                        "ipv4Address": "172.24.120.179",
                        "ipv4Gateway": "172.24.120.161",
                        "ipv4NetMask": "255.255.255.224"
                    }
                },
                "timesettings": {
                    "datetime": "09/13/2016 17:39:48",
                    "ntpServer": [
                        "172.24.13.44",
                        "172.24.14.44"
                    ],
                    "timezone": "UTC"
                }
            }
        },
        "nsx-2": {
            "nsx-appliance": {
                "manager": {
                    "cpuInfoDto": {
                        "capacity": "2900 MHZ",
                        "freeCapacity": "2844 MHZ",
                        "totalNoOfCPUs": 4,
                        "usedCapacity": "56 MHZ",
                        "usedPercentage": 2
                    },
                    "versionInfo": {
                        "buildNumber": "3102213",
                        "majorVersion": "6",
                        "minorVersion": "1",
                        "patchVersion": "5"
                    }
                },
                "network": {
                    "dns": {
                        "domainList": "utility.pge.com",
                        "ipv4Dns": [
                            "10.1.1.1",
                            "172.24.13.44"
                        ],
                        "ipv6Dns": null
                    },
                    "hostName": "itcldfxnsxmgt01",
                    "networkIPv4AddressDto": {
                        "interfaceInfo": null,
                        "ipv4Address": "172.24.120.146",
                        "ipv4Gateway": "172.24.120.129",
                        "ipv4NetMask": "255.255.255.224"
                    }
                },
                "timesettings": {
                    "datetime": "09/13/2016 17:42:41",
                    "ntpServer": [
                        "172.24.14.44",
                        "172.24.13.44"
                    ],
                    "timezone": "UTC"
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
