Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/report.yaml
Checking for collect existence
{
    "data": {
        "nsx-1": {
            "nsx-edge": {
                "edge-19": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.0.2",
                                        "subnetMask": "255.255.255.240",
                                        "subnetPrefixLength": "28"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "uplink"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.0.19",
                                        "subnetMask": "255.255.255.240",
                                        "subnetPrefixLength": "28"
                                    }
                                ]
                            },
                            "label": "vNic_2",
                            "type": "uplink"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.1.1",
                                        "subnetMask": "255.255.255.224",
                                        "subnetPrefixLength": "27"
                                    }
                                ]
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.1.33",
                                        "subnetMask": "255.255.255.224",
                                        "subnetPrefixLength": "27"
                                    }
                                ]
                            },
                            "label": "vNic_4",
                            "type": "uplink"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.1.65",
                                        "subnetMask": "255.255.255.240",
                                        "subnetPrefixLength": "28"
                                    }
                                ]
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.1.81",
                                        "subnetMask": "255.255.255.240",
                                        "subnetPrefixLength": "28"
                                    }
                                ]
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-20": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_0",
                            "type": "internal"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_2",
                            "type": "internal"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "1.1.1.1",
                                        "subnetMask": "255.255.255.0",
                                        "subnetPrefixLength": "24"
                                    }
                                ]
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-21": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.24.11",
                                        "secondaryAddresses": {
                                            "ipAddress": [
                                                "10.31.24.103",
                                                "10.31.24.102",
                                                "10.31.24.34",
                                                "10.31.24.20",
                                                "10.31.24.222",
                                                "10.31.24.12",
                                                "10.31.24.22",
                                                "10.31.24.18",
                                                "10.31.24.17",
                                                "10.31.24.27"
                                            ],
                                            "type": "secondary_addresses"
                                        },
                                        "subnetMask": "255.255.254.0",
                                        "subnetPrefixLength": "23"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "uplink"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_2",
                            "type": "internal"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-28": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.10.10.10",
                                        "subnetMask": "255.255.255.0",
                                        "subnetPrefixLength": "24"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "internal"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "1.1.1.1",
                                        "subnetMask": "255.255.254.0",
                                        "subnetPrefixLength": "23"
                                    }
                                ]
                            },
                            "label": "vNic_2",
                            "type": "internal"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-29": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.152.11",
                                        "secondaryAddresses": {
                                            "ipAddress": [
                                                "10.31.152.100"
                                            ],
                                            "type": "secondary_addresses"
                                        },
                                        "subnetMask": "255.255.254.0",
                                        "subnetPrefixLength": "23"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "uplink"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_2",
                            "type": "internal"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-30": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.0.18",
                                        "subnetMask": "255.255.255.240",
                                        "subnetPrefixLength": "28"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "uplink"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.1.5",
                                        "subnetMask": "255.255.255.224",
                                        "subnetPrefixLength": "27"
                                    }
                                ]
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.0.3",
                                        "subnetMask": "255.255.255.240",
                                        "subnetPrefixLength": "28"
                                    }
                                ]
                            },
                            "label": "vNic_2",
                            "type": "uplink"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.1.37",
                                        "subnetMask": "255.255.255.224",
                                        "subnetPrefixLength": "27"
                                    }
                                ]
                            },
                            "label": "vNic_3",
                            "type": "uplink"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.1.67",
                                        "subnetMask": "255.255.255.240",
                                        "subnetPrefixLength": "28"
                                    }
                                ]
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.1.82",
                                        "subnetMask": "255.255.255.240",
                                        "subnetPrefixLength": "28"
                                    }
                                ]
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-32": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.28.25",
                                        "secondaryAddresses": {
                                            "ipAddress": [
                                                "10.31.28.89",
                                                "10.31.28.81",
                                                "10.31.28.82",
                                                "10.31.28.83",
                                                "10.31.28.75",
                                                "10.31.28.66",
                                                "10.31.28.74",
                                                "10.31.28.65",
                                                "10.31.28.64",
                                                "10.31.28.76",
                                                "10.31.28.63",
                                                "10.31.28.71",
                                                "10.31.28.62",
                                                "10.31.28.70",
                                                "10.31.28.61",
                                                "10.31.28.55",
                                                "10.31.28.73",
                                                "10.31.28.60",
                                                "10.31.28.72",
                                                "10.31.28.57",
                                                "10.31.28.56",
                                                "10.31.28.59",
                                                "10.31.28.58",
                                                "10.31.28.69",
                                                "10.31.28.68",
                                                "10.31.28.67"
                                            ],
                                            "type": "secondary_addresses"
                                        },
                                        "subnetMask": "255.255.254.0",
                                        "subnetPrefixLength": "23"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "uplink"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_2",
                            "type": "internal"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-33": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.26.11",
                                        "secondaryAddresses": {
                                            "ipAddress": [
                                                "10.31.26.31",
                                                "10.31.26.12",
                                                "10.31.26.30",
                                                "10.31.26.16",
                                                "10.31.26.17",
                                                "10.31.26.38",
                                                "10.31.26.37",
                                                "10.31.26.36",
                                                "10.31.26.35",
                                                "10.31.26.34",
                                                "10.31.26.33",
                                                "10.31.26.32",
                                                "10.31.26.19",
                                                "10.31.26.18",
                                                "10.31.26.20",
                                                "10.31.26.40",
                                                "10.31.26.103",
                                                "10.31.26.42",
                                                "10.31.26.41",
                                                "10.31.26.44",
                                                "10.31.26.26",
                                                "10.31.26.43",
                                                "10.31.26.25",
                                                "10.31.26.28",
                                                "10.31.26.46",
                                                "10.31.26.27",
                                                "10.31.26.45",
                                                "10.31.26.22",
                                                "10.31.26.21",
                                                "10.31.26.24",
                                                "10.31.26.23",
                                                "10.31.26.29"
                                            ],
                                            "type": "secondary_addresses"
                                        },
                                        "subnetMask": "255.255.254.0",
                                        "subnetPrefixLength": "23"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "uplink"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_2",
                            "type": "internal"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-36": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.148.11",
                                        "secondaryAddresses": {
                                            "ipAddress": [
                                                "10.31.148.21",
                                                "10.31.148.20",
                                                "10.31.148.22",
                                                "10.31.148.17",
                                                "10.31.148.18",
                                                "10.31.148.19"
                                            ],
                                            "type": "secondary_addresses"
                                        },
                                        "subnetMask": "255.255.254.0",
                                        "subnetPrefixLength": "23"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "internal"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_2",
                            "type": "internal"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-9": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.253.13",
                                        "secondaryAddresses": {
                                            "ipAddress": [
                                                "10.31.253.16",
                                                "10.31.253.36",
                                                "10.31.253.25"
                                            ],
                                            "type": "secondary_addresses"
                                        },
                                        "subnetMask": "255.255.255.0",
                                        "subnetPrefixLength": "24"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "internal"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_2",
                            "type": "internal"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                }
            }
        },
        "nsx-2": {
            "nsx-edge": {
                "edge-10": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.30.0.2",
                                        "subnetMask": "255.255.255.240",
                                        "subnetPrefixLength": "28"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "uplink"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.30.0.19",
                                        "subnetMask": "255.255.255.240",
                                        "subnetPrefixLength": "28"
                                    }
                                ]
                            },
                            "label": "vNic_1",
                            "type": "uplink"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.30.1.33",
                                        "subnetMask": "255.255.255.224",
                                        "subnetPrefixLength": "27"
                                    }
                                ]
                            },
                            "label": "vNic_2",
                            "type": "internal"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.30.1.1",
                                        "subnetMask": "255.255.255.224",
                                        "subnetPrefixLength": "27"
                                    }
                                ]
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.30.1.65",
                                        "subnetMask": "255.255.255.240",
                                        "subnetPrefixLength": "28"
                                    }
                                ]
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.30.1.81",
                                        "subnetMask": "255.255.255.240",
                                        "subnetPrefixLength": "28"
                                    }
                                ]
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-15": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.253.13",
                                        "secondaryAddresses": {
                                            "ipAddress": [
                                                "10.31.253.16",
                                                "10.31.253.36",
                                                "10.31.253.25"
                                            ],
                                            "type": "secondary_addresses"
                                        },
                                        "subnetMask": "255.255.255.0",
                                        "subnetPrefixLength": "24"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "internal"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_2",
                            "type": "internal"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-27": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.30.24.11",
                                        "secondaryAddresses": {
                                            "ipAddress": [
                                                "10.30.24.22",
                                                "10.30.24.102",
                                                "10.30.24.103",
                                                "10.30.24.16"
                                            ],
                                            "type": "secondary_addresses"
                                        },
                                        "subnetMask": "255.255.254.0",
                                        "subnetPrefixLength": "23"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "uplink"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_2",
                            "type": "internal"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-28": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.30.26.11",
                                        "secondaryAddresses": {
                                            "ipAddress": [
                                                "10.30.26.31",
                                                "10.30.26.32",
                                                "10.30.26.20",
                                                "10.30.26.30",
                                                "10.30.26.26",
                                                "10.30.26.27",
                                                "10.30.26.37",
                                                "10.30.26.28",
                                                "10.30.26.29",
                                                "10.30.26.35",
                                                "10.30.26.22",
                                                "10.30.26.17",
                                                "10.30.26.23",
                                                "10.30.26.36",
                                                "10.30.26.18",
                                                "10.30.26.24",
                                                "10.30.26.33",
                                                "10.30.26.42",
                                                "10.30.26.25",
                                                "10.30.26.34",
                                                "10.30.26.16",
                                                "10.30.26.102",
                                                "10.30.26.19",
                                                "10.30.26.103"
                                            ],
                                            "type": "secondary_addresses"
                                        },
                                        "subnetMask": "255.255.254.0",
                                        "subnetPrefixLength": "23"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "uplink"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_2",
                            "type": "internal"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-31": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.30.28.11",
                                        "secondaryAddresses": {
                                            "ipAddress": [
                                                "10.30.28.199",
                                                "10.30.28.109",
                                                "10.30.28.48",
                                                "10.30.28.29",
                                                "10.30.28.28",
                                                "10.30.28.27",
                                                "10.30.28.26",
                                                "10.30.28.25",
                                                "10.30.28.108",
                                                "10.30.28.24",
                                                "10.30.28.41",
                                                "10.30.28.23",
                                                "10.30.28.40",
                                                "10.30.28.22",
                                                "10.30.28.21",
                                                "10.30.28.20",
                                                "10.30.28.42",
                                                "10.30.28.19",
                                                "10.30.28.18",
                                                "10.30.28.39",
                                                "10.30.28.36",
                                                "10.30.28.35",
                                                "10.30.28.38",
                                                "10.30.28.37",
                                                "10.30.28.32",
                                                "10.30.28.31",
                                                "10.30.28.34",
                                                "10.30.28.33",
                                                "10.30.28.30"
                                            ],
                                            "type": "secondary_addresses"
                                        },
                                        "subnetMask": "255.255.254.0",
                                        "subnetPrefixLength": "23"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "uplink"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_2",
                            "type": "internal"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-32": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.152.11",
                                        "subnetMask": "255.255.254.0",
                                        "subnetPrefixLength": "23"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "internal"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_2",
                            "type": "internal"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-33": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.150.11",
                                        "subnetMask": "255.255.254.0",
                                        "subnetPrefixLength": "23"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "internal"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_2",
                            "type": "internal"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-36": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.30.0.18",
                                        "subnetMask": "255.255.255.240",
                                        "subnetPrefixLength": "28"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "uplink"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.30.1.5",
                                        "subnetMask": "255.255.255.224",
                                        "subnetPrefixLength": "27"
                                    }
                                ]
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.30.0.3",
                                        "subnetMask": "255.255.255.240",
                                        "subnetPrefixLength": "28"
                                    }
                                ]
                            },
                            "label": "vNic_2",
                            "type": "uplink"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.30.1.37",
                                        "subnetMask": "255.255.255.224",
                                        "subnetPrefixLength": "27"
                                    }
                                ]
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.30.1.67",
                                        "subnetMask": "255.255.255.240",
                                        "subnetPrefixLength": "28"
                                    }
                                ]
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.30.1.82",
                                        "subnetMask": "255.255.255.240",
                                        "subnetPrefixLength": "28"
                                    }
                                ]
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                },
                "edge-38": {
                    "vnics": {
                        "vNic_0": {
                            "addressGroups": {
                                "addressGroups": [
                                    {
                                        "primaryAddress": "10.31.148.11",
                                        "secondaryAddresses": {
                                            "ipAddress": [
                                                "10.31.148.21",
                                                "10.31.148.20",
                                                "10.31.148.22",
                                                "10.31.148.17",
                                                "10.31.148.18",
                                                "10.31.148.19"
                                            ],
                                            "type": "secondary_addresses"
                                        },
                                        "subnetMask": "255.255.254.0",
                                        "subnetPrefixLength": "23"
                                    }
                                ]
                            },
                            "label": "vNic_0",
                            "type": "internal"
                        },
                        "vNic_1": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_1",
                            "type": "internal"
                        },
                        "vNic_2": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_2",
                            "type": "internal"
                        },
                        "vNic_3": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_3",
                            "type": "internal"
                        },
                        "vNic_4": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_4",
                            "type": "internal"
                        },
                        "vNic_5": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_5",
                            "type": "internal"
                        },
                        "vNic_6": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_6",
                            "type": "internal"
                        },
                        "vNic_7": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_7",
                            "type": "internal"
                        },
                        "vNic_8": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_8",
                            "type": "internal"
                        },
                        "vNic_9": {
                            "addressGroups": {
                                "addressGroups": []
                            },
                            "label": "vNic_9",
                            "type": "internal"
                        }
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
