Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/viprcluster.yaml
Checking for collect existence
{
    "data": {
        "vipr-1": {
            "vipr-block": {
                "clusters": {
                    "0a1cabae-3ff5-4165-a2de-bbe34b6c5a07": {
                        "name": "FX-Tenant-NonDR-Cluster01",
                        "vcenter_data_center": {
                            "id": "urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                            "link": {
                                "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "1abc1813-46c9-46e6-a20a-ec2143ce9fcb": {
                        "name": "FX-Automation-Cluster01",
                        "vcenter_data_center": {
                            "id": "urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                            "link": {
                                "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "2147637c-2122-4655-b696-c4775d369a89": {
                        "name": "FX-Tenant-DR-Cluster01",
                        "vcenter_data_center": {
                            "id": "urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                            "link": {
                                "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "3024a68a-f2d3-4b28-abb8-b803e6feab22": {
                        "name": "RC-NEI-Cluster01",
                        "vcenter_data_center": {
                            "id": "urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                            "link": {
                                "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "433a214a-a45f-45da-96d4-781093fdbcbf": {
                        "name": "RC-Automation-Cluster01",
                        "vcenter_data_center": {
                            "id": "urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                            "link": {
                                "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "57d9cd3d-9f5b-437c-bd4d-7a66e5aceb7c": {
                        "name": "Lab-NonDR-Cluster",
                        "vcenter_data_center": {
                            "id": "urn:storageos:VcenterDataCenter:04ea6145-c0e8-4121-ab2c-bf68a6c0e853:vdc1",
                            "link": {
                                "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:04ea6145-c0e8-4121-ab2c-bf68a6c0e853:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "73af04d6-ffad-4def-808e-98358f0b50ce": {
                        "name": "RC-Tenant-NonDR-Cluster01",
                        "vcenter_data_center": {
                            "id": "urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                            "link": {
                                "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "9e64bb04-3d6a-4895-a4b4-b2658647afba": {
                        "name": "RC-VDI-Cluster01",
                        "vcenter_data_center": {
                            "id": "urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                            "link": {
                                "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "a4fd48dd-a44a-4b2b-a06f-330f93320077": {
                        "name": "RC-Tenant-DR-Cluster01",
                        "vcenter_data_center": {
                            "id": "urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                            "link": {
                                "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "b0ecb3ed-1103-4b54-bb49-3cbcd6c16142": {
                        "name": "FX-VDI-Cluster01",
                        "vcenter_data_center": {
                            "id": "urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                            "link": {
                                "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "b48c38bc-bca9-40a5-8204-efe377c34825": {
                        "name": "Lab-NonDR-Cluster",
                        "vcenter_data_center": {
                            "id": "urn:storageos:VcenterDataCenter:bf4591f6-a708-4bdf-ab59-ebc32de64499:vdc1",
                            "link": {
                                "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:bf4591f6-a708-4bdf-ab59-ebc32de64499:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "fd24a6c8-8c94-43b5-81e8-fa21c2ff7210": {
                        "name": "FX-NEI-Cluster01",
                        "vcenter_data_center": {
                            "id": "urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                            "link": {
                                "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                                "rel": "self"
                            }
                        }
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
