Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/viprcombine-cluster.yaml
Checking for collect existence
{
    "data": {
        "vipr-1": {
            "vipr-block": {
                "clusters-combine": {
                    "0a1cabae-3ff5-4165-a2de-bbe34b6c5a07": {
                        "cluster": {
                            "_id": "9f54dd2b1165f2b7af3b34a9b75d5650",
                            "_rev": "1-a1108c5a7f7638cc44d6d9c05ee39ded",
                            "creation_time": 1429637513742,
                            "global": false,
                            "id": "urn:storageos:Cluster:0a1cabae-3ff5-4165-a2de-bbe34b6c5a07:vdc1",
                            "inactive": false,
                            "internal": false,
                            "link": {
                                "href": "/compute/clusters/urn:storageos:Cluster:0a1cabae-3ff5-4165-a2de-bbe34b6c5a07:vdc1",
                                "rel": "self"
                            },
                            "name": "FX-Tenant-NonDR-Cluster01",
                            "remote": false,
                            "svt_client": "PGE",
                            "svt_collect_date": "2016-09-13-10-35-57",
                            "svt_source": "vipr-1",
                            "svt_source_file": "vipr_compute-cluster_0a1cabae-3ff5-4165-a2de-bbe34b6c5a07.json",
                            "tags": [],
                            "tenant": {
                                "id": "urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                "link": {
                                    "href": "/tenants/urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                    "rel": "self"
                                }
                            },
                            "vcenter_data_center": {
                                "id": "urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                                "link": {
                                    "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                                    "rel": "self"
                                }
                            },
                            "vdc": {
                                "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "link": {
                                    "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                    "rel": "self"
                                }
                            }
                        }
                    },
                    "1abc1813-46c9-46e6-a20a-ec2143ce9fcb": {
                        "cluster": {
                            "_id": "4546776a9bd668325e550b4e2bd75586",
                            "_rev": "1-f066dbd7441626992bb75d5cfa4faec8",
                            "creation_time": 1429128814276,
                            "global": false,
                            "id": "urn:storageos:Cluster:1abc1813-46c9-46e6-a20a-ec2143ce9fcb:vdc1",
                            "inactive": false,
                            "internal": false,
                            "link": {
                                "href": "/compute/clusters/urn:storageos:Cluster:1abc1813-46c9-46e6-a20a-ec2143ce9fcb:vdc1",
                                "rel": "self"
                            },
                            "name": "FX-Automation-Cluster01",
                            "remote": false,
                            "svt_client": "PGE",
                            "svt_collect_date": "2016-09-13-10-35-57",
                            "svt_source": "vipr-1",
                            "svt_source_file": "vipr_compute-cluster_1abc1813-46c9-46e6-a20a-ec2143ce9fcb.json",
                            "tags": [],
                            "tenant": {
                                "id": "urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                "link": {
                                    "href": "/tenants/urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                    "rel": "self"
                                }
                            },
                            "vcenter_data_center": {
                                "id": "urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                                "link": {
                                    "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                                    "rel": "self"
                                }
                            },
                            "vdc": {
                                "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "link": {
                                    "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                    "rel": "self"
                                }
                            }
                        }
                    },
                    "2147637c-2122-4655-b696-c4775d369a89": {
                        "cluster": {
                            "_id": "4546776a9bd668325e550b4e2bb1f539",
                            "_rev": "1-2055e68084b76fe919cabb354ec3c599",
                            "creation_time": 1429637513709,
                            "global": false,
                            "id": "urn:storageos:Cluster:2147637c-2122-4655-b696-c4775d369a89:vdc1",
                            "inactive": false,
                            "internal": false,
                            "link": {
                                "href": "/compute/clusters/urn:storageos:Cluster:2147637c-2122-4655-b696-c4775d369a89:vdc1",
                                "rel": "self"
                            },
                            "name": "FX-Tenant-DR-Cluster01",
                            "remote": false,
                            "svt_client": "PGE",
                            "svt_collect_date": "2016-09-13-10-35-57",
                            "svt_source": "vipr-1",
                            "svt_source_file": "vipr_compute-cluster_2147637c-2122-4655-b696-c4775d369a89.json",
                            "tags": [],
                            "tenant": {
                                "id": "urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                "link": {
                                    "href": "/tenants/urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                    "rel": "self"
                                }
                            },
                            "vcenter_data_center": {
                                "id": "urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                                "link": {
                                    "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                                    "rel": "self"
                                }
                            },
                            "vdc": {
                                "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "link": {
                                    "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                    "rel": "self"
                                }
                            }
                        }
                    },
                    "3024a68a-f2d3-4b28-abb8-b803e6feab22": {
                        "cluster": {
                            "_id": "4546776a9bd668325e550b4e2bb23d5b",
                            "_rev": "1-cf70619a80bf0f76605896724b54c3d0",
                            "creation_time": 1429128658417,
                            "global": false,
                            "id": "urn:storageos:Cluster:3024a68a-f2d3-4b28-abb8-b803e6feab22:vdc1",
                            "inactive": false,
                            "internal": false,
                            "link": {
                                "href": "/compute/clusters/urn:storageos:Cluster:3024a68a-f2d3-4b28-abb8-b803e6feab22:vdc1",
                                "rel": "self"
                            },
                            "name": "RC-NEI-Cluster01",
                            "remote": false,
                            "svt_client": "PGE",
                            "svt_collect_date": "2016-09-13-10-35-57",
                            "svt_source": "vipr-1",
                            "svt_source_file": "vipr_compute-cluster_3024a68a-f2d3-4b28-abb8-b803e6feab22.json",
                            "tags": [],
                            "tenant": {
                                "id": "urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                "link": {
                                    "href": "/tenants/urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                    "rel": "self"
                                }
                            },
                            "vcenter_data_center": {
                                "id": "urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                                "link": {
                                    "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                                    "rel": "self"
                                }
                            },
                            "vdc": {
                                "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "link": {
                                    "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                    "rel": "self"
                                }
                            }
                        }
                    },
                    "433a214a-a45f-45da-96d4-781093fdbcbf": {
                        "cluster": {
                            "_id": "9f54dd2b1165f2b7af3b34a9b71cbae8",
                            "_rev": "1-2d96e8ca4e0f2e801d9b75aaa357867b",
                            "creation_time": 1429128658411,
                            "global": false,
                            "id": "urn:storageos:Cluster:433a214a-a45f-45da-96d4-781093fdbcbf:vdc1",
                            "inactive": false,
                            "internal": false,
                            "link": {
                                "href": "/compute/clusters/urn:storageos:Cluster:433a214a-a45f-45da-96d4-781093fdbcbf:vdc1",
                                "rel": "self"
                            },
                            "name": "RC-Automation-Cluster01",
                            "remote": false,
                            "svt_client": "PGE",
                            "svt_collect_date": "2016-09-13-10-35-57",
                            "svt_source": "vipr-1",
                            "svt_source_file": "vipr_compute-cluster_433a214a-a45f-45da-96d4-781093fdbcbf.json",
                            "tags": [],
                            "tenant": {
                                "id": "urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                "link": {
                                    "href": "/tenants/urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                    "rel": "self"
                                }
                            },
                            "vcenter_data_center": {
                                "id": "urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                                "link": {
                                    "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                                    "rel": "self"
                                }
                            },
                            "vdc": {
                                "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "link": {
                                    "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                    "rel": "self"
                                }
                            }
                        }
                    },
                    "57d9cd3d-9f5b-437c-bd4d-7a66e5aceb7c": {
                        "cluster": {
                            "_id": "4546776a9bd668325e550b4e2bc1c2ad",
                            "_rev": "1-4a666a812701e404c03a824ec926f95d",
                            "creation_time": 1472278394184,
                            "global": false,
                            "id": "urn:storageos:Cluster:57d9cd3d-9f5b-437c-bd4d-7a66e5aceb7c:vdc1",
                            "inactive": false,
                            "internal": false,
                            "link": {
                                "href": "/compute/clusters/urn:storageos:Cluster:57d9cd3d-9f5b-437c-bd4d-7a66e5aceb7c:vdc1",
                                "rel": "self"
                            },
                            "name": "Lab-NonDR-Cluster",
                            "remote": false,
                            "svt_client": "PGE",
                            "svt_collect_date": "2016-09-13-10-35-57",
                            "svt_source": "vipr-1",
                            "svt_source_file": "vipr_compute-cluster_57d9cd3d-9f5b-437c-bd4d-7a66e5aceb7c.json",
                            "tags": [],
                            "tenant": {
                                "id": "urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                "link": {
                                    "href": "/tenants/urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                    "rel": "self"
                                }
                            },
                            "vcenter_data_center": {
                                "id": "urn:storageos:VcenterDataCenter:04ea6145-c0e8-4121-ab2c-bf68a6c0e853:vdc1",
                                "link": {
                                    "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:04ea6145-c0e8-4121-ab2c-bf68a6c0e853:vdc1",
                                    "rel": "self"
                                }
                            },
                            "vdc": {
                                "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "link": {
                                    "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                    "rel": "self"
                                }
                            }
                        }
                    },
                    "73af04d6-ffad-4def-808e-98358f0b50ce": {
                        "cluster": {
                            "_id": "9f54dd2b1165f2b7af3b34a9b71ddb4f",
                            "_rev": "1-96a6c49823a2cfbfb82950ce4cf3c649",
                            "creation_time": 1429637513722,
                            "global": false,
                            "id": "urn:storageos:Cluster:73af04d6-ffad-4def-808e-98358f0b50ce:vdc1",
                            "inactive": false,
                            "internal": false,
                            "link": {
                                "href": "/compute/clusters/urn:storageos:Cluster:73af04d6-ffad-4def-808e-98358f0b50ce:vdc1",
                                "rel": "self"
                            },
                            "name": "RC-Tenant-NonDR-Cluster01",
                            "remote": false,
                            "svt_client": "PGE",
                            "svt_collect_date": "2016-09-13-10-35-57",
                            "svt_source": "vipr-1",
                            "svt_source_file": "vipr_compute-cluster_73af04d6-ffad-4def-808e-98358f0b50ce.json",
                            "tags": [],
                            "tenant": {
                                "id": "urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                "link": {
                                    "href": "/tenants/urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                    "rel": "self"
                                }
                            },
                            "vcenter_data_center": {
                                "id": "urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                                "link": {
                                    "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                                    "rel": "self"
                                }
                            },
                            "vdc": {
                                "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "link": {
                                    "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                    "rel": "self"
                                }
                            }
                        }
                    },
                    "9e64bb04-3d6a-4895-a4b4-b2658647afba": {
                        "cluster": {
                            "_id": "9f54dd2b1165f2b7af3b34a9b763ff74",
                            "_rev": "1-1be77e5e3444b5b48c86a219af451f27",
                            "creation_time": 1467353738909,
                            "global": false,
                            "id": "urn:storageos:Cluster:9e64bb04-3d6a-4895-a4b4-b2658647afba:vdc1",
                            "inactive": false,
                            "internal": false,
                            "link": {
                                "href": "/compute/clusters/urn:storageos:Cluster:9e64bb04-3d6a-4895-a4b4-b2658647afba:vdc1",
                                "rel": "self"
                            },
                            "name": "RC-VDI-Cluster01",
                            "remote": false,
                            "svt_client": "PGE",
                            "svt_collect_date": "2016-09-13-10-35-57",
                            "svt_source": "vipr-1",
                            "svt_source_file": "vipr_compute-cluster_9e64bb04-3d6a-4895-a4b4-b2658647afba.json",
                            "tags": [],
                            "tenant": {
                                "id": "urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                "link": {
                                    "href": "/tenants/urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                    "rel": "self"
                                }
                            },
                            "vcenter_data_center": {
                                "id": "urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                                "link": {
                                    "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                                    "rel": "self"
                                }
                            },
                            "vdc": {
                                "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "link": {
                                    "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                    "rel": "self"
                                }
                            }
                        }
                    },
                    "a4fd48dd-a44a-4b2b-a06f-330f93320077": {
                        "cluster": {
                            "_id": "9f54dd2b1165f2b7af3b34a9b7177f8b",
                            "_rev": "1-5b5152c6559178cdb7f85ab77be803d4",
                            "creation_time": 1429637513694,
                            "global": false,
                            "id": "urn:storageos:Cluster:a4fd48dd-a44a-4b2b-a06f-330f93320077:vdc1",
                            "inactive": false,
                            "internal": false,
                            "link": {
                                "href": "/compute/clusters/urn:storageos:Cluster:a4fd48dd-a44a-4b2b-a06f-330f93320077:vdc1",
                                "rel": "self"
                            },
                            "name": "RC-Tenant-DR-Cluster01",
                            "remote": false,
                            "svt_client": "PGE",
                            "svt_collect_date": "2016-09-13-10-35-57",
                            "svt_source": "vipr-1",
                            "svt_source_file": "vipr_compute-cluster_a4fd48dd-a44a-4b2b-a06f-330f93320077.json",
                            "tags": [],
                            "tenant": {
                                "id": "urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                "link": {
                                    "href": "/tenants/urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                    "rel": "self"
                                }
                            },
                            "vcenter_data_center": {
                                "id": "urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                                "link": {
                                    "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:256700d3-56c3-402f-9d8d-25771df6b8ff:vdc1",
                                    "rel": "self"
                                }
                            },
                            "vdc": {
                                "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "link": {
                                    "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                    "rel": "self"
                                }
                            }
                        }
                    },
                    "b0ecb3ed-1103-4b54-bb49-3cbcd6c16142": {
                        "cluster": {
                            "_id": "9f54dd2b1165f2b7af3b34a9b722ff6e",
                            "_rev": "1-2ff87044a3aeb798c8b1d69179b2c00e",
                            "creation_time": 1467785785219,
                            "global": false,
                            "id": "urn:storageos:Cluster:b0ecb3ed-1103-4b54-bb49-3cbcd6c16142:vdc1",
                            "inactive": false,
                            "internal": false,
                            "link": {
                                "href": "/compute/clusters/urn:storageos:Cluster:b0ecb3ed-1103-4b54-bb49-3cbcd6c16142:vdc1",
                                "rel": "self"
                            },
                            "name": "FX-VDI-Cluster01",
                            "remote": false,
                            "svt_client": "PGE",
                            "svt_collect_date": "2016-09-13-10-35-57",
                            "svt_source": "vipr-1",
                            "svt_source_file": "vipr_compute-cluster_b0ecb3ed-1103-4b54-bb49-3cbcd6c16142.json",
                            "tags": [],
                            "tenant": {
                                "id": "urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                "link": {
                                    "href": "/tenants/urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                    "rel": "self"
                                }
                            },
                            "vcenter_data_center": {
                                "id": "urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                                "link": {
                                    "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                                    "rel": "self"
                                }
                            },
                            "vdc": {
                                "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "link": {
                                    "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                    "rel": "self"
                                }
                            }
                        }
                    },
                    "b48c38bc-bca9-40a5-8204-efe377c34825": {
                        "cluster": {
                            "_id": "4546776a9bd668325e550b4e2bc8a6c4",
                            "_rev": "1-25b3ca49b805fb98bb324cfc9b1ada51",
                            "creation_time": 1472278348610,
                            "global": false,
                            "id": "urn:storageos:Cluster:b48c38bc-bca9-40a5-8204-efe377c34825:vdc1",
                            "inactive": false,
                            "internal": false,
                            "link": {
                                "href": "/compute/clusters/urn:storageos:Cluster:b48c38bc-bca9-40a5-8204-efe377c34825:vdc1",
                                "rel": "self"
                            },
                            "name": "Lab-NonDR-Cluster",
                            "remote": false,
                            "svt_client": "PGE",
                            "svt_collect_date": "2016-09-13-10-35-57",
                            "svt_source": "vipr-1",
                            "svt_source_file": "vipr_compute-cluster_b48c38bc-bca9-40a5-8204-efe377c34825.json",
                            "tags": [],
                            "tenant": {
                                "id": "urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                "link": {
                                    "href": "/tenants/urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                    "rel": "self"
                                }
                            },
                            "vcenter_data_center": {
                                "id": "urn:storageos:VcenterDataCenter:bf4591f6-a708-4bdf-ab59-ebc32de64499:vdc1",
                                "link": {
                                    "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:bf4591f6-a708-4bdf-ab59-ebc32de64499:vdc1",
                                    "rel": "self"
                                }
                            },
                            "vdc": {
                                "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "link": {
                                    "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                    "rel": "self"
                                }
                            }
                        }
                    },
                    "fd24a6c8-8c94-43b5-81e8-fa21c2ff7210": {
                        "cluster": {
                            "_id": "4546776a9bd668325e550b4e2be021f8",
                            "_rev": "1-81ce2d653e9db35000522ebaa26d9caa",
                            "creation_time": 1429128814287,
                            "global": false,
                            "id": "urn:storageos:Cluster:fd24a6c8-8c94-43b5-81e8-fa21c2ff7210:vdc1",
                            "inactive": false,
                            "internal": false,
                            "link": {
                                "href": "/compute/clusters/urn:storageos:Cluster:fd24a6c8-8c94-43b5-81e8-fa21c2ff7210:vdc1",
                                "rel": "self"
                            },
                            "name": "FX-NEI-Cluster01",
                            "remote": false,
                            "svt_client": "PGE",
                            "svt_collect_date": "2016-09-13-10-35-57",
                            "svt_source": "vipr-1",
                            "svt_source_file": "vipr_compute-cluster_fd24a6c8-8c94-43b5-81e8-fa21c2ff7210.json",
                            "tags": [],
                            "tenant": {
                                "id": "urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                "link": {
                                    "href": "/tenants/urn:storageos:TenantOrg:70f84a12-6ce1-4b50-b616-06ac71c8f94f:global",
                                    "rel": "self"
                                }
                            },
                            "vcenter_data_center": {
                                "id": "urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                                "link": {
                                    "href": "/compute/vcenter-data-centers/urn:storageos:VcenterDataCenter:10462174-c304-464c-b567-51d70ca68e59:vdc1",
                                    "rel": "self"
                                }
                            },
                            "vdc": {
                                "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "link": {
                                    "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                    "rel": "self"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
