Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: yamldefs/all-vipr_vdc-network-systems.yaml
Checking for collect existence
{
    "data": {
        "vipr-1": {
            "vipr-vdc": {
                "network-systems": {
                    "44ea0225-ab7f-4ce5-aae7-00eb289708b4": {
                        "compatibility_status": "COMPATIBLE",
                        "creation_time": 1429029650067,
                        "global": false,
                        "id": "urn:storageos:NetworkSystem:44ea0225-ab7f-4ce5-aae7-00eb289708b4:vdc1",
                        "inactive": false,
                        "internal": false,
                        "ip_address": "172.24.125.21",
                        "job_discovery_status": "COMPLETE",
                        "job_metering_status": "CREATED",
                        "last_discovery_run_time": 1473787904314,
                        "last_discovery_status_message": "Discovery completed successfully for Network System : urn:storageos:NetworkSystem:44ea0225-ab7f-4ce5-aae7-00eb289708b4:vdc1",
                        "last_metering_run_time": 0,
                        "link": {
                            "href": "/vdc/network-systems/urn:storageos:NetworkSystem:44ea0225-ab7f-4ce5-aae7-00eb289708b4:vdc1",
                            "rel": "self"
                        },
                        "name": "cssrciocvbmd9102 - Fabric B - RC",
                        "native_guid": "MDS+172.24.125.21+22",
                        "next_discovery_run_time": 1473791499966,
                        "next_metering_run_time": 0,
                        "port_number": 22,
                        "registration_status": "REGISTERED",
                        "remote": false,
                        "smis_port_number": 22,
                        "smis_provider_ip": "172.24.125.21",
                        "smis_use_ssl": false,
                        "smis_user_name": "admin",
                        "success_discovery_time": 1473787904314,
                        "success_metering_time": 0,
                        "system_type": "mds",
                        "tags": [],
                        "uptime": "369 days, 0 hours, 17 minutes, 51 seconds",
                        "user_name": "admin",
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "version": "6.2(11b)"
                    },
                    "4f54d166-6715-4cae-90d6-7b77a6081d62": {
                        "compatibility_status": "COMPATIBLE",
                        "creation_time": 1429029598027,
                        "global": false,
                        "id": "urn:storageos:NetworkSystem:4f54d166-6715-4cae-90d6-7b77a6081d62:vdc1",
                        "inactive": false,
                        "internal": false,
                        "ip_address": "172.24.125.20",
                        "job_discovery_status": "COMPLETE",
                        "job_metering_status": "CREATED",
                        "last_discovery_run_time": 1473787905323,
                        "last_discovery_status_message": "Discovery completed successfully for Network System : urn:storageos:NetworkSystem:4f54d166-6715-4cae-90d6-7b77a6081d62:vdc1",
                        "last_metering_run_time": 0,
                        "link": {
                            "href": "/vdc/network-systems/urn:storageos:NetworkSystem:4f54d166-6715-4cae-90d6-7b77a6081d62:vdc1",
                            "rel": "self"
                        },
                        "name": "cssrciocvbmd9101 - Fabric A - RC",
                        "native_guid": "MDS+172.24.125.20+22",
                        "next_discovery_run_time": 1473791500121,
                        "next_metering_run_time": 0,
                        "port_number": 22,
                        "registration_status": "REGISTERED",
                        "remote": false,
                        "smis_port_number": 22,
                        "smis_provider_ip": "172.24.125.20",
                        "smis_use_ssl": false,
                        "smis_user_name": "admin",
                        "success_discovery_time": 1473787905323,
                        "success_metering_time": 0,
                        "system_type": "mds",
                        "tags": [],
                        "uptime": "369 days, 0 hours, 28 minutes, 21 seconds",
                        "user_name": "admin",
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "version": "6.2(11b)"
                    },
                    "7814302b-d2eb-4136-849b-b9e4cc36744c": {
                        "compatibility_status": "COMPATIBLE",
                        "creation_time": 1429029765105,
                        "global": false,
                        "id": "urn:storageos:NetworkSystem:7814302b-d2eb-4136-849b-b9e4cc36744c:vdc1",
                        "inactive": false,
                        "internal": false,
                        "ip_address": "172.24.124.21",
                        "job_discovery_status": "COMPLETE",
                        "job_metering_status": "CREATED",
                        "last_discovery_run_time": 1473787907174,
                        "last_discovery_status_message": "Discovery completed successfully for Network System : urn:storageos:NetworkSystem:7814302b-d2eb-4136-849b-b9e4cc36744c:vdc1",
                        "last_metering_run_time": 0,
                        "link": {
                            "href": "/vdc/network-systems/urn:storageos:NetworkSystem:7814302b-d2eb-4136-849b-b9e4cc36744c:vdc1",
                            "rel": "self"
                        },
                        "name": "cssffiocaxvbmd9102 - Fabric B - FF",
                        "native_guid": "MDS+172.24.124.21+22",
                        "next_discovery_run_time": 1473791500265,
                        "next_metering_run_time": 0,
                        "port_number": 22,
                        "registration_status": "REGISTERED",
                        "remote": false,
                        "smis_port_number": 22,
                        "smis_provider_ip": "172.24.124.21",
                        "smis_use_ssl": false,
                        "smis_user_name": "admin",
                        "success_discovery_time": 1473787907174,
                        "success_metering_time": 0,
                        "system_type": "mds",
                        "tags": [],
                        "uptime": "365 days, 0 hours, 25 minutes, 21 seconds",
                        "user_name": "admin",
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "version": "6.2(11b)"
                    },
                    "e7a33267-f274-4e80-86fa-f7eb818f5290": {
                        "compatibility_status": "COMPATIBLE",
                        "creation_time": 1429029728114,
                        "global": false,
                        "id": "urn:storageos:NetworkSystem:e7a33267-f274-4e80-86fa-f7eb818f5290:vdc1",
                        "inactive": false,
                        "internal": false,
                        "ip_address": "172.24.124.20",
                        "job_discovery_status": "COMPLETE",
                        "job_metering_status": "CREATED",
                        "last_discovery_run_time": 1473787908248,
                        "last_discovery_status_message": "Discovery completed successfully for Network System : urn:storageos:NetworkSystem:e7a33267-f274-4e80-86fa-f7eb818f5290:vdc1",
                        "last_metering_run_time": 0,
                        "link": {
                            "href": "/vdc/network-systems/urn:storageos:NetworkSystem:e7a33267-f274-4e80-86fa-f7eb818f5290:vdc1",
                            "rel": "self"
                        },
                        "name": "cssffiocaxvbmd9101 - Fabric A - FF",
                        "native_guid": "MDS+172.24.124.20+22",
                        "next_discovery_run_time": 1473791500385,
                        "next_metering_run_time": 0,
                        "port_number": 22,
                        "registration_status": "REGISTERED",
                        "remote": false,
                        "smis_port_number": 22,
                        "smis_provider_ip": "172.24.124.20",
                        "smis_use_ssl": false,
                        "smis_user_name": "admin",
                        "success_discovery_time": 1473787908248,
                        "success_metering_time": 0,
                        "system_type": "mds",
                        "tags": [],
                        "uptime": "365 days, 0 hours, 50 minutes, 51 seconds",
                        "user_name": "admin",
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "version": "6.2(11b)"
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
