http://localhost:5984/
Welcome
http://localhost:5984/svtdev
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/all_vipr-vdc_storage-systems.yaml
Checking for collect existence
http://localhost:5984/svtdev/_design/admin/_view/isnewcollect?reduce=true&startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]&group_level=2
http://localhost:5984/svtdev/_design/vipr-vdc/_view/storage-systems?startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]
{
    "data": {
        "vipr-1": {
            "vipr-vdc": {
                "storage-systems": {
                    "10d14f9a-cc42-4286-becc-9a396bafee41.json": {
                        "active_provider_uri": {
                            "id": "urn:storageos:StorageProvider:fe831645-7a72-4caa-bb19-d24824a62ca1:vdc1",
                            "link": {
                                "href": "/vdc/smis-providers/urn:storageos:StorageProvider:fe831645-7a72-4caa-bb19-d24824a62ca1:vdc1",
                                "rel": "self"
                            }
                        },
                        "associated_systems": [],
                        "async_actions": [
                            "CreateGroupReplica",
                            "CreateElementReplica"
                        ],
                        "average_port_metrics": 3.9558595681043704,
                        "compatibility_status": "COMPATIBLE",
                        "connected_systems": [],
                        "creation_time": 1428533671249,
                        "export_masks": [],
                        "firmware_version": "05.33.009.5.155",
                        "global": false,
                        "id": "urn:storageos:StorageSystem:10d14f9a-cc42-4286-becc-9a396bafee41:vdc1",
                        "inactive": false,
                        "internal": false,
                        "job_discovery_status": "COMPLETE",
                        "job_metering_status": "COMPLETE",
                        "last_discovery_run_time": 1473787924167,
                        "last_discovery_status_message": "Unknown Status",
                        "last_metering_run_time": 1473787875176,
                        "link": {
                            "href": "/vdc/storage-systems/urn:storageos:StorageSystem:10d14f9a-cc42-4286-becc-9a396bafee41:vdc1",
                            "rel": "self"
                        },
                        "max_resources": -1,
                        "model": "Rack Mounted VNX8000",
                        "name": "CLARIION+APM00144937724",
                        "native_guid": "CLARIION+APM00144937724",
                        "next_discovery_run_time": 1473791499571,
                        "next_metering_run_time": 1473791469561,
                        "num_resources": 69,
                        "protocols": [],
                        "reachable": true,
                        "registration_status": "REGISTERED",
                        "remote": false,
                        "secondary_ips": [],
                        "serial_number": "APM00144937724",
                        "smis_port_number": 5989,
                        "smis_provider_ip": "172.24.120.178",
                        "smis_providers": [
                            {
                                "id": "urn:storageos:StorageProvider:fe831645-7a72-4caa-bb19-d24824a62ca1:vdc1",
                                "link": {
                                    "href": "/vdc/smis-providers/urn:storageos:StorageProvider:fe831645-7a72-4caa-bb19-d24824a62ca1:vdc1",
                                    "rel": "self"
                                }
                            }
                        ],
                        "smis_use_ssl": true,
                        "smis_user_name": "admin",
                        "success_discovery_time": 1473787924167,
                        "success_metering_time": 1473787875176,
                        "supported_provisioning_type": "THIN_AND_THICK",
                        "supported_replication_types": [],
                        "system_type": "vnxblock",
                        "tags": [],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "94eff137-6f58-45d3-b6f9-cd12497edbb2.json": {
                        "active_provider_uri": {
                            "id": "urn:storageos:StorageProvider:f53bdd37-e2e5-406f-925e-6c86db4c13df:vdc1",
                            "link": {
                                "href": "/vdc/smis-providers/urn:storageos:StorageProvider:f53bdd37-e2e5-406f-925e-6c86db4c13df:vdc1",
                                "rel": "self"
                            }
                        },
                        "associated_systems": [],
                        "async_actions": [
                            "CreateGroupReplica",
                            "CreateElementReplica"
                        ],
                        "average_port_metrics": 4.8770837400713125,
                        "compatibility_status": "COMPATIBLE",
                        "connected_systems": [],
                        "creation_time": 1429028916933,
                        "export_masks": [],
                        "firmware_version": "05.33.009.5.155",
                        "global": false,
                        "id": "urn:storageos:StorageSystem:94eff137-6f58-45d3-b6f9-cd12497edbb2:vdc1",
                        "inactive": false,
                        "internal": false,
                        "job_discovery_status": "COMPLETE",
                        "job_metering_status": "COMPLETE",
                        "last_discovery_run_time": 1473787907915,
                        "last_discovery_status_message": "Unknown Status",
                        "last_metering_run_time": 1473787874721,
                        "link": {
                            "href": "/vdc/storage-systems/urn:storageos:StorageSystem:94eff137-6f58-45d3-b6f9-cd12497edbb2:vdc1",
                            "rel": "self"
                        },
                        "max_resources": -1,
                        "model": "Rack Mounted VNX8000",
                        "name": "CLARIION+APM00144937726",
                        "native_guid": "CLARIION+APM00144937726",
                        "next_discovery_run_time": 1473791499660,
                        "next_metering_run_time": 1473791469695,
                        "num_resources": 71,
                        "protocols": [],
                        "reachable": true,
                        "registration_status": "REGISTERED",
                        "remote": false,
                        "secondary_ips": [],
                        "serial_number": "APM00144937726",
                        "smis_port_number": 5989,
                        "smis_provider_ip": "172.24.120.145",
                        "smis_providers": [
                            {
                                "id": "urn:storageos:StorageProvider:f53bdd37-e2e5-406f-925e-6c86db4c13df:vdc1",
                                "link": {
                                    "href": "/vdc/smis-providers/urn:storageos:StorageProvider:f53bdd37-e2e5-406f-925e-6c86db4c13df:vdc1",
                                    "rel": "self"
                                }
                            }
                        ],
                        "smis_use_ssl": true,
                        "smis_user_name": "admin",
                        "success_discovery_time": 1473787907915,
                        "success_metering_time": 1473787874721,
                        "supported_provisioning_type": "THIN_AND_THICK",
                        "supported_replication_types": [],
                        "system_type": "vnxblock",
                        "tags": [],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
