http://localhost:5984/
Welcome
http://localhost:5984/svtdev
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/allmanager.yaml
Checking for collect existence
http://localhost:5984/svtdev/_design/admin/_view/isnewcollect?reduce=true&startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]&group_level=2
http://localhost:5984/svtdev/_design/nsx-appliance/_view/manager?startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]
{
    "data": {
        "nsx-1": {
            "nsx-appliance": {
                "manager": {
                    "_id": "6e814398566d99b3f818bb1cba5ca5cd",
                    "_rev": "1-b297675b82c298589b68d7fae7dfa3b0",
                    "applianceName": "vShield Virtual Appliance Management",
                    "cpuInfoDto": {
                        "capacity": "2900 MHZ",
                        "freeCapacity": "2096 MHZ",
                        "totalNoOfCPUs": 4,
                        "usedCapacity": "804 MHZ",
                        "usedPercentage": 28
                    },
                    "currentSystemDate": "Tuesday, 13 September 2016 05:39:48 PM UTC",
                    "domainName": "utility.pge.com",
                    "hostName": "itcldrcnsxmgt01",
                    "ipv4Address": "172.24.120.179",
                    "ipv6Address": null,
                    "memInfoDto": {
                        "freeMemory": "105 MB",
                        "totalMemory": "11996 MB",
                        "usedMemory": "11890 MB",
                        "usedPercentage": 99
                    },
                    "storageInfoDto": {
                        "freeStorage": "44G",
                        "totalStorage": "71G",
                        "usedPercentage": 38,
                        "usedStorage": "27G"
                    },
                    "svt_client": "PGE",
                    "svt_collect_date": "2016-09-13-10-35-57",
                    "svt_source": "nsx-1",
                    "svt_source_file": "nsx_appliance-management-summary-system.json",
                    "uptime": "266 days, 14 hours, 10 minutes",
                    "versionInfo": {
                        "buildNumber": "3102213",
                        "majorVersion": "6",
                        "minorVersion": "1",
                        "patchVersion": "5"
                    }
                }
            }
        },
        "nsx-2": {
            "nsx-appliance": {
                "manager": {
                    "_id": "6e814398566d99b3f818bb1cba3aeef4",
                    "_rev": "1-d7bd31cd3da39895350ea66ebc363ec8",
                    "applianceName": "vShield Virtual Appliance Management",
                    "cpuInfoDto": {
                        "capacity": "2900 MHZ",
                        "freeCapacity": "2844 MHZ",
                        "totalNoOfCPUs": 4,
                        "usedCapacity": "56 MHZ",
                        "usedPercentage": 2
                    },
                    "currentSystemDate": "Tuesday, 13 September 2016 05:42:41 PM UTC",
                    "domainName": "utility.pge.com",
                    "hostName": "itcldfxnsxmgt01",
                    "ipv4Address": "172.24.120.146",
                    "ipv6Address": null,
                    "memInfoDto": {
                        "freeMemory": "5034 MB",
                        "totalMemory": "11996 MB",
                        "usedMemory": "6961 MB",
                        "usedPercentage": 58
                    },
                    "storageInfoDto": {
                        "freeStorage": "48G",
                        "totalStorage": "71G",
                        "usedPercentage": 32,
                        "usedStorage": "23G"
                    },
                    "svt_client": "PGE",
                    "svt_collect_date": "2016-09-13-10-35-57",
                    "svt_source": "nsx-2",
                    "svt_source_file": "nsx_appliance-management-summary-system.json",
                    "uptime": "1 day, 21 hours, 22 minutes",
                    "versionInfo": {
                        "buildNumber": "3102213",
                        "majorVersion": "6",
                        "minorVersion": "1",
                        "patchVersion": "5"
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
