Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/allmanager.yaml
Checking for collect existence
{
    "data": {
        "nsx-1": {
            "nsx-appliance": {
                "manager": {
                    "applianceName": "vShield Virtual Appliance Management",
                    "cpuInfoDto": {
                        "capacity": "2900 MHZ",
                        "freeCapacity": "2096 MHZ",
                        "totalNoOfCPUs": 4,
                        "usedCapacity": "804 MHZ",
                        "usedPercentage": 28
                    },
                    "currentSystemDate": "Tuesday, 13 September 2016 05:39:48 PM UTC",
                    "domainName": "utility.pge.com",
                    "hostName": "itcldrcnsxmgt01",
                    "ipv4Address": "172.24.120.179",
                    "ipv6Address": null,
                    "memInfoDto": {
                        "freeMemory": "105 MB",
                        "totalMemory": "11996 MB",
                        "usedMemory": "11890 MB",
                        "usedPercentage": 99
                    },
                    "storageInfoDto": {
                        "freeStorage": "44G",
                        "totalStorage": "71G",
                        "usedPercentage": 38,
                        "usedStorage": "27G"
                    },
                    "uptime": "266 days, 14 hours, 10 minutes",
                    "versionInfo": {
                        "buildNumber": "3102213",
                        "majorVersion": "6",
                        "minorVersion": "1",
                        "patchVersion": "5"
                    }
                }
            }
        },
        "nsx-2": {
            "nsx-appliance": {
                "manager": {
                    "applianceName": "vShield Virtual Appliance Management",
                    "cpuInfoDto": {
                        "capacity": "2900 MHZ",
                        "freeCapacity": "2844 MHZ",
                        "totalNoOfCPUs": 4,
                        "usedCapacity": "56 MHZ",
                        "usedPercentage": 2
                    },
                    "currentSystemDate": "Tuesday, 13 September 2016 05:42:41 PM UTC",
                    "domainName": "utility.pge.com",
                    "hostName": "itcldfxnsxmgt01",
                    "ipv4Address": "172.24.120.146",
                    "ipv6Address": null,
                    "memInfoDto": {
                        "freeMemory": "5034 MB",
                        "totalMemory": "11996 MB",
                        "usedMemory": "6961 MB",
                        "usedPercentage": 58
                    },
                    "storageInfoDto": {
                        "freeStorage": "48G",
                        "totalStorage": "71G",
                        "usedPercentage": 32,
                        "usedStorage": "23G"
                    },
                    "uptime": "1 day, 21 hours, 22 minutes",
                    "versionInfo": {
                        "buildNumber": "3102213",
                        "majorVersion": "6",
                        "minorVersion": "1",
                        "patchVersion": "5"
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
