http://localhost:5984/
Welcome
http://localhost:5984/svtdev
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/components.yaml
Checking for collect existence
http://localhost:5984/svtdev/_design/admin/_view/isnewcollect?reduce=true&startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]&group_level=2
http://localhost:5984/svtdev/_design/nsx-appliance/_view/components?startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]
{
    "data": {
        "nsx-1": {
            "nsx-appliance": {
                "components": {
                    "NSX": {
                        "componentGroup": "NSXGRP",
                        "description": "NSX Manager",
                        "enabled": true,
                        "usedBy": [],
                        "uses": [
                            "VPOSTGRES",
                            "RABBITMQ"
                        ]
                    },
                    "NSXAPIMGMT": {
                        "componentGroup": "NSXAPIGRP",
                        "description": "NSX API Manager",
                        "enabled": true,
                        "usedBy": [],
                        "uses": null
                    },
                    "RABBITMQ": {
                        "componentGroup": "COMMON",
                        "description": "RabbitMQ - Messaging service",
                        "enabled": true,
                        "usedBy": [
                            "NSX"
                        ],
                        "uses": null
                    },
                    "SSH": {
                        "componentGroup": "SYSTEM",
                        "description": "Secure Shell",
                        "enabled": true,
                        "usedBy": [],
                        "uses": null
                    },
                    "VPOSTGRES": {
                        "componentGroup": "COMMON",
                        "description": "vPostgres - Database service",
                        "enabled": true,
                        "usedBy": [
                            "NSX"
                        ],
                        "uses": null
                    }
                }
            }
        },
        "nsx-2": {
            "nsx-appliance": {
                "components": {
                    "NSX": {
                        "componentGroup": "NSXGRP",
                        "description": "NSX Manager",
                        "enabled": true,
                        "usedBy": [],
                        "uses": [
                            "VPOSTGRES",
                            "RABBITMQ"
                        ]
                    },
                    "NSXAPIMGMT": {
                        "componentGroup": "NSXAPIGRP",
                        "description": "NSX API Manager",
                        "enabled": true,
                        "usedBy": [],
                        "uses": null
                    },
                    "RABBITMQ": {
                        "componentGroup": "COMMON",
                        "description": "RabbitMQ - Messaging service",
                        "enabled": true,
                        "usedBy": [
                            "NSX"
                        ],
                        "uses": null
                    },
                    "SSH": {
                        "componentGroup": "SYSTEM",
                        "description": "Secure Shell",
                        "enabled": true,
                        "usedBy": [],
                        "uses": null
                    },
                    "VPOSTGRES": {
                        "componentGroup": "COMMON",
                        "description": "vPostgres - Database service",
                        "enabled": true,
                        "usedBy": [
                            "NSX"
                        ],
                        "uses": null
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
