Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/lb.yaml
Checking for collect existence
{
    "data": {
        "nsx-1": {
            "nsx-edge": {
                "edge-19": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 5
                    }
                },
                "edge-20": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "interval": 10,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-4",
                                "name": "monitor-4",
                                "timeout": 15,
                                "type": "icmp",
                                "url": "/"
                            },
                            {
                                "expected": "HTTP/1.1",
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 64
                    }
                },
                "edge-21": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "expected": "HTTP:/1.1",
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 10,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-5",
                                "name": "RPMS-Https-Mon",
                                "receive": "200 OK",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-6",
                                "name": "default_icmp_monitor",
                                "timeout": 15,
                                "type": "icmp",
                                "url": "/"
                            },
                            {
                                "extension": "eregi=\"(is operational)\"",
                                "interval": 3,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-9",
                                "name": "amps_https",
                                "timeout": 5,
                                "type": "https",
                                "url": "/monitor.html"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-10",
                                "name": "coherence-tcp-monitor",
                                "receive": "\"\\\\x09\\\\x00\\\\x04\\\\x02\\\\x00\\\\x42\\\\x00\\\\x03\\\\x64\\\\x40\"",
                                "send": "\u201c\\\\x07\\\\x00\\\\x03\\\\x00\\\\x00\\\\x42\\\\x00\\\\x40\u201d",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "expected": "200 OK",
                                "interval": 10,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-11",
                                "name": "citrix-http",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "expected": "401",
                                "interval": 5,
                                "maxRetries": 2,
                                "method": "GET",
                                "monitorId": "monitor-12",
                                "name": "HTTP-401",
                                "timeout": 5,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "extension": "eregi=\"(is operational)\"",
                                "interval": 3,
                                "maxRetries": 2,
                                "method": "GET",
                                "monitorId": "monitor-13",
                                "name": "TOTL-Custom-http",
                                "timeout": 5,
                                "type": "http",
                                "url": "/monitor.htm"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-8",
                                "name": "WLS-https",
                                "timeout": 5,
                                "type": "https",
                                "url": "/helloworld"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-7",
                                "name": "WLS-http",
                                "timeout": 5,
                                "type": "http",
                                "url": "/helloworld"
                            },
                            {
                                "expected": "200 OK",
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-14",
                                "name": "GLS-HTTP",
                                "timeout": 5,
                                "type": "http",
                                "url": "/default.html"
                            },
                            {
                                "interval": 3,
                                "maxRetries": 3,
                                "monitorId": "monitor-15",
                                "name": "RPMS_PRD_MONITOR",
                                "timeout": 6,
                                "type": "tcp"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 359
                    }
                },
                "edge-28": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "expected": "HTTP/1.1",
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-4",
                                "name": "default_icmp_monitor",
                                "timeout": 15,
                                "type": "icmp",
                                "url": "/"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 23
                    }
                },
                "edge-29": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "expected": "HTTP/1.1",
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-4",
                                "name": "default_icmp_monitor",
                                "timeout": 15,
                                "type": "icmp",
                                "url": "/"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 16
                    }
                },
                "edge-30": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 2
                    }
                },
                "edge-32": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-43",
                                "name": "MonitorFor-decdappwvip0005-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-67",
                                "name": "MonitorFor-decdappavip0027-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-74",
                                "name": "App-http-monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-75",
                                "name": "MonitorFor-TEST121615_131-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-77",
                                "name": "MonitorFor-TEST121602_131-1",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-47",
                                "name": "default-icmp-monitor",
                                "timeout": 15,
                                "type": "icmp",
                                "url": "/"
                            },
                            {
                                "expected": "HTTP/1.1",
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-46",
                                "name": "default-http-monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-81",
                                "name": "default-https-monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-82",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 517
                    }
                },
                "edge-33": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-4",
                                "name": "MonitorFor-qacdappivip0014-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-5",
                                "name": "MonitorFor-qacdappivip0016-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-6",
                                "name": "MonitorFor-qacdappivip0017-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-7",
                                "name": "MonitorFor-qacdappivip0020-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-8",
                                "name": "MonitorFor-qacdappivip0021-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-9",
                                "name": "MonitorFor-qacdappavip0001-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-10",
                                "name": "MonitorFor-qacdappivip0023-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-11",
                                "name": "MonitorFor-qacdappavip0002-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-12",
                                "name": "MonitorFor-qacdappivip0025-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-13",
                                "name": "MonitorFor-qacdappivip0026-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-14",
                                "name": "MonitorFor-qacdappavip0007-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-15",
                                "name": "MonitorFor-qacdappavip0008-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-16",
                                "name": "MonitorFor-qacdappavip0009-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-17",
                                "name": "MonitorFor-qacdappivip0028-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-18",
                                "name": "MonitorFor-qacdappivip0029-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-19",
                                "name": "MonitorFor-qacdappavip0010-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-20",
                                "name": "MonitorFor-qacdappivip0030-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-21",
                                "name": "MonitorFor-default9vip0001-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-22",
                                "name": "MonitorFor-default9vip0002-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-23",
                                "name": "MonitorFor-qacdappivip0031-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-24",
                                "name": "MonitorFor-qacdappavip0011-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-25",
                                "name": "MonitorFor-qacdappavip0012-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-26",
                                "name": "MonitorFor-qacdappivip0032-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-28",
                                "name": "default_icmp_monitor",
                                "timeout": 15,
                                "type": "icmp",
                                "url": "/"
                            },
                            {
                                "expected": "401",
                                "interval": 5,
                                "maxRetries": 2,
                                "method": "GET",
                                "monitorId": "monitor-29",
                                "name": "http-401",
                                "timeout": 5,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "extension": "eregi=\"(is operational)\"",
                                "interval": 3,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-30",
                                "name": "amps_https",
                                "timeout": 5,
                                "type": "https",
                                "url": "/monitor.html"
                            },
                            {
                                "interval": 3,
                                "maxRetries": 3,
                                "monitorId": "monitor-27",
                                "name": "RPMS_QA_MONITOR",
                                "timeout": 6,
                                "type": "tcp"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 427
                    }
                },
                "edge-36": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "expected": "HTTP/1.1",
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-4",
                                "name": "default_icmp_monitor",
                                "timeout": 15,
                                "type": "icmp",
                                "url": "/"
                            },
                            {
                                "extension": "eregi=\"(reached successfully)\"",
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-5",
                                "name": "HPP-P-https",
                                "timeout": 5,
                                "type": "https",
                                "url": "/sap/public/ping?sap-client=800"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 19
                    }
                },
                "edge-9": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "interval": 3,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-4",
                                "name": "vpostgres",
                                "receive": "Postgres.Master=true",
                                "timeout": 9,
                                "type": "https",
                                "url": "/vPostgresService.py"
                            },
                            {
                                "interval": 3,
                                "maxRetries": 10,
                                "method": "GET",
                                "monitorId": "monitor-7",
                                "name": "vcac_iaas_manager",
                                "receive": "BasicHttpBinding_VMPSProxyAgent_policy",
                                "timeout": 9,
                                "type": "https",
                                "url": "/VMPS2"
                            },
                            {
                                "expected": "200 OK",
                                "interval": 3,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-6",
                                "name": "vcac_iaas_web",
                                "receive": "iaas-service",
                                "timeout": 9,
                                "type": "https",
                                "url": "/WAPI/api/status"
                            },
                            {
                                "interval": 3,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-5",
                                "name": "vcac_va",
                                "receive": "REGISTERED",
                                "timeout": 9,
                                "type": "https",
                                "url": "/vcac/services/api/status"
                            },
                            {
                                "interval": 10,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-9",
                                "name": "icmp",
                                "timeout": 15,
                                "type": "icmp",
                                "url": "/"
                            },
                            {
                                "interval": 3,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-8",
                                "name": "vco",
                                "receive": "REGISTERED",
                                "timeout": 9,
                                "type": "https",
                                "url": "/vco/api/status"
                            },
                            {
                                "expected": "200 OK",
                                "interval": 3,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-10",
                                "name": "vcac_iaas_manager2",
                                "timeout": 9,
                                "type": "https",
                                "url": "/VMPS2Proxy"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 316
                    }
                }
            }
        },
        "nsx-2": {
            "nsx-edge": {
                "edge-10": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 3
                    }
                },
                "edge-15": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "interval": 3,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-5",
                                "name": "vcac_va",
                                "receive": "REGISTERED",
                                "timeout": 9,
                                "type": "https",
                                "url": "/vcac/services/api/status"
                            },
                            {
                                "interval": 3,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-4",
                                "name": "vpostgres",
                                "receive": "Postgres.Master=true",
                                "timeout": 9,
                                "type": "https",
                                "url": "/vPostgresService.py"
                            },
                            {
                                "interval": 3,
                                "maxRetries": 10,
                                "method": "GET",
                                "monitorId": "monitor-7",
                                "name": "vcac_iaas_manager",
                                "receive": "BasicHttpBinding_VMPSProxyAgent_policy",
                                "timeout": 9,
                                "type": "https",
                                "url": "/VMPS2"
                            },
                            {
                                "interval": 10,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-9",
                                "name": "icmp",
                                "timeout": 15,
                                "type": "icmp",
                                "url": "/"
                            },
                            {
                                "expected": "200 OK",
                                "interval": 3,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-6",
                                "name": "vcac_iaas_web",
                                "receive": "iaas-service",
                                "timeout": 9,
                                "type": "https",
                                "url": "/WAPI/api/status"
                            },
                            {
                                "interval": 3,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-8",
                                "name": "vco",
                                "receive": "REGISTERED",
                                "timeout": 9,
                                "type": "https",
                                "url": "/vco/api/status"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 54
                    }
                },
                "edge-27": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "expected": "HTTP/1.1",
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-4",
                                "name": "default_icmp_monitor",
                                "timeout": 15,
                                "type": "icmp",
                                "url": "/"
                            },
                            {
                                "interval": 10,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-5",
                                "name": "WLS-http",
                                "timeout": 15,
                                "type": "http",
                                "url": "/helloworld"
                            },
                            {
                                "extension": "eregi=\"(is operational)\"",
                                "interval": 3,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-7",
                                "name": "amps_https",
                                "timeout": 5,
                                "type": "https",
                                "url": "/monitor.html"
                            },
                            {
                                "expected": "401",
                                "interval": 5,
                                "maxRetries": 2,
                                "method": "GET",
                                "monitorId": "monitor-8",
                                "name": "HTTP-401",
                                "timeout": 5,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "extension": "eregi=\"(is operational)\"",
                                "interval": 3,
                                "maxRetries": 2,
                                "method": "GET",
                                "monitorId": "monitor-9",
                                "name": "TOTL-Custom-http",
                                "timeout": 5,
                                "type": "http",
                                "url": "/monitor.htm"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-6",
                                "name": "WLS-https",
                                "timeout": 10,
                                "type": "https",
                                "url": "/helloworld"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 160
                    }
                },
                "edge-28": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "expected": "HTTP/1.1",
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-4",
                                "name": "MonitorFor-qacdappivip0007-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-5",
                                "name": "MonitorFor-qacdappivip0009-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-6",
                                "name": "MonitorFor-qacdappivip0011-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-7",
                                "name": "MonitorFor-qacdappivip0013-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-8",
                                "name": "MonitorFor-qacdappivip0015-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-9",
                                "name": "MonitorFor-qacdappivip0018-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-10",
                                "name": "MonitorFor-qacdappivip0019-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-11",
                                "name": "MonitorFor-qacdappivip0022-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-12",
                                "name": "MonitorFor-qacdappivip0024-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-13",
                                "name": "MonitorFor-qacdappavip0003-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-14",
                                "name": "MonitorFor-qacdappavip0004-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-15",
                                "name": "MonitorFor-qacdappavip0005-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-16",
                                "name": "MonitorFor-qacdappavip0006-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-17",
                                "name": "MonitorFor-qacdappivip0027-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-19",
                                "name": "default_icmp_monitor",
                                "timeout": 15,
                                "type": "icmp",
                                "url": "/"
                            },
                            {
                                "interval": 10,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-18",
                                "name": "WLS-http",
                                "timeout": 15,
                                "type": "http",
                                "url": "/helloworld"
                            },
                            {
                                "interval": 10,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-20",
                                "name": "WLS-https",
                                "timeout": 15,
                                "type": "https",
                                "url": "/helloworld"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-22",
                                "name": "Coherence-tcp-custom",
                                "receive": "\"\\x09\\x00\\x04\\x02\\x00\\x42\\x00\\x03\\x64\\x40\"",
                                "send": "\"\\x07\\x00\\x03\\x00\\x00\\x42\\x00\\x40\"",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "extension": "eregi=\"(reached successfully)\"",
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-23",
                                "name": "HPQ-QA-https",
                                "timeout": 5,
                                "type": "https",
                                "url": "/sap/public/ping?sap-client=800"
                            },
                            {
                                "interval": 10,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-21",
                                "name": "HTTP-401",
                                "receive": "Unauthorized",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "extension": "eregi=\"(is operational)\"",
                                "interval": 3,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-24",
                                "name": "amps_https",
                                "timeout": 5,
                                "type": "https",
                                "url": "/monitor.html"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 385
                    }
                },
                "edge-31": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "expected": "HTTP/1.1",
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-4",
                                "name": "MonitorFor-tscdappivip0007-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-6",
                                "name": "MonitorFor-tscdappivip0008-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-7",
                                "name": "MonitorFor-decdappivip0010-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-8",
                                "name": "MonitorFor-tscdappivip0010-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-9",
                                "name": "MonitorFor-decdappivip0012-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-10",
                                "name": "MonitorFor-tscdappivip0011-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-11",
                                "name": "MonitorFor-tscdappivip0016-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-12",
                                "name": "MonitorFor-decdappivip0015-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-13",
                                "name": "MonitorFor-default8vip0001-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-14",
                                "name": "MonitorFor-decdappivip0017-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-15",
                                "name": "MonitorFor-tscdappivip0018-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-16",
                                "name": "MonitorFor-deccappivip0001-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-17",
                                "name": "MonitorFor-decdappivip0018-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-18",
                                "name": "MonitorFor-tscdappivip0019-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-19",
                                "name": "MonitorFor-decdappivip0019-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-20",
                                "name": "MonitorFor-decdappivip0024-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-21",
                                "name": "MonitorFor-tscdappivip0022-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-22",
                                "name": "MonitorFor-tscdappivip0023-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-23",
                                "name": "MonitorFor-tscdappivip0024-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-24",
                                "name": "MonitorFor-decdappivip0030-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-25",
                                "name": "MonitorFor-decdappavip0012-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-26",
                                "name": "MonitorFor-decdappavip0013-1",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-27",
                                "name": "default_icmp_monitor",
                                "timeout": 15,
                                "type": "icmp",
                                "url": "/"
                            },
                            {
                                "interval": 10,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-31",
                                "name": "WLS-Https",
                                "timeout": 15,
                                "type": "https",
                                "url": "/helloworld"
                            },
                            {
                                "interval": 10,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-30",
                                "name": "WLS-http",
                                "timeout": 15,
                                "type": "http",
                                "url": "/helloworld"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-32",
                                "name": "coherence-tcp-monitor",
                                "receive": "\"\\x09\\x00\\x04\\x02\\x00\\x42\\x00\\x03\\x64\\x40\"",
                                "send": "\"\\x07\\x00\\x03\\x00\\x00\\x42\\x00\\x40\"",
                                "timeout": 15,
                                "type": "tcp"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 621
                    }
                },
                "edge-32": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "expected": "HTTP/1.1",
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-5",
                                "name": "default_icmp_monitor",
                                "timeout": 15,
                                "type": "icmp",
                                "url": "/"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 10
                    }
                },
                "edge-33": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "expected": "HTTP/1.1",
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-4",
                                "name": "default_icmp_monitor",
                                "timeout": 15,
                                "type": "icmp",
                                "url": "/"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 7
                    }
                },
                "edge-36": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 2
                    }
                },
                "edge-38": {
                    "loadbalancer": {
                        "monitor": [
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "monitorId": "monitor-1",
                                "name": "default_tcp_monitor",
                                "timeout": 15,
                                "type": "tcp"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-2",
                                "name": "default_http_monitor",
                                "timeout": 15,
                                "type": "http",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-3",
                                "name": "default_https_monitor",
                                "timeout": 15,
                                "type": "https",
                                "url": "/"
                            },
                            {
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-4",
                                "name": "default_icmp_monitor",
                                "timeout": 15,
                                "type": "icmp",
                                "url": "/"
                            },
                            {
                                "extension": "eregi=\"(reached successfully)\"",
                                "interval": 5,
                                "maxRetries": 3,
                                "method": "GET",
                                "monitorId": "monitor-5",
                                "name": "HPP-P-https",
                                "timeout": 5,
                                "type": "https",
                                "url": "/sap/public/ping?sap-client=800"
                            }
                        ],
                        "tenant": "svt_no_data",
                        "version": 34
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
