http://localhost:5984/
Welcome
http://localhost:5984/svtdev
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/manager.yaml
Checking for collect existence
http://localhost:5984/svtdev/_design/admin/_view/isnewcollect?reduce=true&startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]&group_level=2
http://localhost:5984/svtdev/_design/nsx-appliance/_view/manager?startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]
'{"info": {"svt_collect": "2016-09-13-10-35-57", "svt_client": "PGE"}, "data": {"nsx-1": {"nsx-appliance": {"manager": {"ipv4Address": "172.24.120.179", "uptime": "266 days, 14 hours, 10 minutes", "hostName": "itcldrcnsxmgt01", "dnsName": "svt_no_data", "currentSystemDate": "Tuesday, 13 September 2016 05:39:48 PM UTC", "versionInfo": {"buildNumber": "3102213", "majorVersion": "6", "patchVersion": "5", "minorVersion": "1"}}}}, "nsx-2": {"nsx-appliance": {"manager": {"ipv4Address": "172.24.120.146", "uptime": "1 day, 21 hours, 22 minutes", "hostName": "itcldfxnsxmgt01", "dnsName": "svt_no_data", "currentSystemDate": "Tuesday, 13 September 2016 05:42:41 PM UTC", "versionInfo": {"buildNumber": "3102213", "majorVersion": "6", "patchVersion": "5", "minorVersion": "1"}}}}}}'
