http://localhost:5984/
Welcome
http://localhost:5984/svtdev
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/nsx-appliance_manager.yaml
Checking for collect existence
http://localhost:5984/svtdev/_design/admin/_view/isnewcollect?reduce=true&startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]&group_level=2
http://localhost:5984/svtdev/_design/nsx-appliance/_view/summary-system?startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]
{
    "data": {
        "nsx-1": {
            "nsx-appliance": {
                "summary-system": {
                    "currentSystemDate": "Tuesday, 13 September 2016 05:39:48 PM UTC",
                    "domainName": "utility.pge.com",
                    "hostName": "itcldrcnsxmgt01",
                    "ipv4Address": "172.24.120.179",
                    "uptime": "266 days, 14 hours, 10 minutes",
                    "versionInfo": {
                        "buildNumber": "3102213",
                        "majorVersion": "6",
                        "minorVersion": "1",
                        "patchVersion": "5"
                    }
                }
            }
        },
        "nsx-2": {
            "nsx-appliance": {
                "summary-system": {
                    "currentSystemDate": "Tuesday, 13 September 2016 05:42:41 PM UTC",
                    "domainName": "utility.pge.com",
                    "hostName": "itcldfxnsxmgt01",
                    "ipv4Address": "172.24.120.146",
                    "uptime": "1 day, 21 hours, 22 minutes",
                    "versionInfo": {
                        "buildNumber": "3102213",
                        "majorVersion": "6",
                        "minorVersion": "1",
                        "patchVersion": "5"
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
