Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: yamldefs/nsx-vdn_switches.yaml
Checking for collect existence
{
    "data": {
        "nsx-1": {
            "nsx-vdn": {
                "svt_single": {},
                "switches": {
                    "switch1": {
                        "failoverUplinkPortNames": [
                            "Uplink 4"
                        ],
                        "mtu": 1600,
                        "promiscuousMode": false,
                        "switchObj": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "RC-NEI-vDS",
                            "objectId": "dvs-55",
                            "objectTypeName": "VmwareDistributedVirtualSwitch",
                            "revision": 135,
                            "scope": {
                                "id": "datacenter-2",
                                "name": "RC-Tenant-Datacenter01",
                                "objectTypeName": "Datacenter"
                            },
                            "type": {
                                "name": "VmwareDistributedVirtualSwitch"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        },
                        "teamingPolicy": "FAILOVER_ORDER"
                    },
                    "switch2": {
                        "failoverUplinkPortNames": [
                            "dvUplink1"
                        ],
                        "mtu": 1600,
                        "promiscuousMode": false,
                        "switchObj": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "RC-Automation-vDS",
                            "objectId": "dvs-58",
                            "objectTypeName": "VmwareDistributedVirtualSwitch",
                            "revision": 71,
                            "scope": {
                                "id": "datacenter-2",
                                "name": "RC-Tenant-Datacenter01",
                                "objectTypeName": "Datacenter"
                            },
                            "type": {
                                "name": "VmwareDistributedVirtualSwitch"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        },
                        "teamingPolicy": "FAILOVER_ORDER"
                    },
                    "switch3": {
                        "failoverUplinkPortNames": [
                            "dvUplink1"
                        ],
                        "mtu": 1600,
                        "promiscuousMode": false,
                        "switchObj": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "RC-Tenant-vDS",
                            "objectId": "dvs-60",
                            "objectTypeName": "VmwareDistributedVirtualSwitch",
                            "revision": 118,
                            "scope": {
                                "id": "datacenter-2",
                                "name": "RC-Tenant-Datacenter01",
                                "objectTypeName": "Datacenter"
                            },
                            "type": {
                                "name": "VmwareDistributedVirtualSwitch"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        },
                        "teamingPolicy": "FAILOVER_ORDER"
                    },
                    "switch4": {
                        "failoverUplinkPortNames": [
                            "dvUplink1"
                        ],
                        "mtu": 1600,
                        "promiscuousMode": false,
                        "switchObj": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "RC-Tenant-VDI-vDS",
                            "objectId": "dvs-71918",
                            "objectTypeName": "VmwareDistributedVirtualSwitch",
                            "revision": 40,
                            "scope": {
                                "id": "datacenter-2",
                                "name": "RC-Tenant-Datacenter01",
                                "objectTypeName": "Datacenter"
                            },
                            "type": {
                                "name": "VmwareDistributedVirtualSwitch"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        },
                        "teamingPolicy": "FAILOVER_ORDER"
                    },
                    "switch5": {
                        "failoverUplinkPortNames": [
                            "Uplink 2"
                        ],
                        "mtu": 1600,
                        "promiscuousMode": false,
                        "switchObj": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "RC-DR-Tenant-vDS",
                            "objectId": "dvs-8368",
                            "objectTypeName": "VmwareDistributedVirtualSwitch",
                            "revision": 18,
                            "scope": {
                                "id": "datacenter-2",
                                "name": "RC-Tenant-Datacenter01",
                                "objectTypeName": "Datacenter"
                            },
                            "type": {
                                "name": "VmwareDistributedVirtualSwitch"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        },
                        "teamingPolicy": "FAILOVER_ORDER"
                    }
                }
            }
        },
        "nsx-2": {
            "nsx-vdn": {
                "svt_single": {},
                "switches": {
                    "switch1": {
                        "failoverUplinkPortNames": [
                            "dvUplink1"
                        ],
                        "mtu": 1600,
                        "promiscuousMode": false,
                        "switchObj": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "FX-Tenant-vDS",
                            "objectId": "dvs-121",
                            "objectTypeName": "VmwareDistributedVirtualSwitch",
                            "revision": 93,
                            "scope": {
                                "id": "datacenter-21",
                                "name": "FX-Tenant-Datacenter01",
                                "objectTypeName": "Datacenter"
                            },
                            "type": {
                                "name": "VmwareDistributedVirtualSwitch"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        },
                        "teamingPolicy": "FAILOVER_ORDER"
                    },
                    "switch2": {
                        "failoverUplinkPortNames": [
                            "Uplink 2"
                        ],
                        "mtu": 1600,
                        "promiscuousMode": false,
                        "switchObj": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "FX-DR-Tenant-vDS",
                            "objectId": "dvs-4944",
                            "objectTypeName": "VmwareDistributedVirtualSwitch",
                            "revision": 20,
                            "scope": {
                                "id": "datacenter-21",
                                "name": "FX-Tenant-Datacenter01",
                                "objectTypeName": "Datacenter"
                            },
                            "type": {
                                "name": "VmwareDistributedVirtualSwitch"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        },
                        "teamingPolicy": "FAILOVER_ORDER"
                    },
                    "switch3": {
                        "failoverUplinkPortNames": [
                            "dvUplink1"
                        ],
                        "mtu": 1600,
                        "promiscuousMode": false,
                        "switchObj": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "FX-Automation-vDS",
                            "objectId": "dvs-56",
                            "objectTypeName": "VmwareDistributedVirtualSwitch",
                            "revision": 7,
                            "scope": {
                                "id": "datacenter-21",
                                "name": "FX-Tenant-Datacenter01",
                                "objectTypeName": "Datacenter"
                            },
                            "type": {
                                "name": "VmwareDistributedVirtualSwitch"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        },
                        "teamingPolicy": "FAILOVER_ORDER"
                    },
                    "switch4": {
                        "failoverUplinkPortNames": [
                            "dvUplink1"
                        ],
                        "mtu": 1600,
                        "promiscuousMode": false,
                        "switchObj": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "FX-Tenant-VDI-vDS",
                            "objectId": "dvs-56118",
                            "objectTypeName": "VmwareDistributedVirtualSwitch",
                            "revision": 34,
                            "scope": {
                                "id": "datacenter-21",
                                "name": "FX-Tenant-Datacenter01",
                                "objectTypeName": "Datacenter"
                            },
                            "type": {
                                "name": "VmwareDistributedVirtualSwitch"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        },
                        "teamingPolicy": "FAILOVER_ORDER"
                    },
                    "switch5": {
                        "failoverUplinkPortNames": [
                            "dvUplink1"
                        ],
                        "mtu": 1600,
                        "promiscuousMode": false,
                        "switchObj": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "FX-NEI-vDS",
                            "objectId": "dvs-58",
                            "objectTypeName": "VmwareDistributedVirtualSwitch",
                            "revision": 112,
                            "scope": {
                                "id": "datacenter-21",
                                "name": "FX-Tenant-Datacenter01",
                                "objectTypeName": "Datacenter"
                            },
                            "type": {
                                "name": "VmwareDistributedVirtualSwitch"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        },
                        "teamingPolicy": "FAILOVER_ORDER"
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
