Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: yamldefs/nsx-vdn_controllers.yaml
Checking for collect existence
{
    "data": {
        "nsx-1": {
            "nsx-vdn": {
                "controllers": {
                    "controller1": {
                        "clientHandle": "",
                        "clusterInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "RC-NEI-Cluster01",
                            "objectId": "domain-c46",
                            "objectTypeName": "ClusterComputeResource",
                            "revision": 148,
                            "scope": {
                                "id": "datacenter-2",
                                "name": "RC-Tenant-Datacenter01",
                                "objectTypeName": "Datacenter"
                            },
                            "type": {
                                "name": "ClusterComputeResource"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        },
                        "controllerClusterStatus": {
                            "controllerConnectivityList": [
                                {
                                    "destControllerIp": "172.24.120.189",
                                    "isDestActive": true,
                                    "lastRefreshedAt": 1473788385034,
                                    "pingStatus": "SUCCESS",
                                    "srcControllerId": "controller-1",
                                    "srcControllerIp": "172.24.120.188"
                                },
                                {
                                    "destControllerIp": "172.24.120.190",
                                    "isDestActive": true,
                                    "lastRefreshedAt": 1473788385034,
                                    "pingStatus": "SUCCESS",
                                    "srcControllerId": "controller-1",
                                    "srcControllerIp": "172.24.120.188"
                                }
                            ]
                        },
                        "datastoreInfos": [
                            {
                                "clientHandle": "",
                                "extendedAttributes": [],
                                "name": "rcioc-nei-ds-vm01",
                                "objectId": "datastore-50",
                                "objectTypeName": "Datastore",
                                "revision": 1,
                                "type": {
                                    "name": "Datastore"
                                },
                                "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                            }
                        ],
                        "hostInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "itvircneiesx01.utility.pge.com",
                            "objectId": "host-48",
                            "objectTypeName": "HostSystem",
                            "revision": 1046,
                            "scope": {
                                "id": "domain-c46",
                                "name": "RC-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "HostSystem"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        },
                        "id": "controller-1",
                        "ipAddress": "172.24.120.188",
                        "resourcePoolInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "Resources",
                            "objectId": "resgroup-47",
                            "objectTypeName": "ResourcePool",
                            "revision": 239,
                            "scope": {
                                "id": "domain-c46",
                                "name": "RC-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "ResourcePool"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        },
                        "revision": 0,
                        "status": "RUNNING",
                        "upgradeAvailable": false,
                        "upgradeStatus": "UPGRADED",
                        "version": "6.1.45116",
                        "virtualMachineInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "NSX_Controller_525cbc4d-ccfa-4bdc-a6cf-74a0e0f85ab4",
                            "objectId": "vm-62",
                            "objectTypeName": "VirtualMachine",
                            "revision": 88,
                            "scope": {
                                "id": "domain-c46",
                                "name": "RC-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "VirtualMachine"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        }
                    },
                    "controller2": {
                        "clientHandle": "",
                        "clusterInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "RC-NEI-Cluster01",
                            "objectId": "domain-c46",
                            "objectTypeName": "ClusterComputeResource",
                            "revision": 148,
                            "scope": {
                                "id": "datacenter-2",
                                "name": "RC-Tenant-Datacenter01",
                                "objectTypeName": "Datacenter"
                            },
                            "type": {
                                "name": "ClusterComputeResource"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        },
                        "controllerClusterStatus": {
                            "controllerConnectivityList": [
                                {
                                    "destControllerIp": "172.24.120.188",
                                    "isDestActive": true,
                                    "lastRefreshedAt": 1473788385069,
                                    "pingStatus": "SUCCESS",
                                    "srcControllerId": "controller-2",
                                    "srcControllerIp": "172.24.120.189"
                                },
                                {
                                    "destControllerIp": "172.24.120.190",
                                    "isDestActive": true,
                                    "lastRefreshedAt": 1473788385069,
                                    "pingStatus": "SUCCESS",
                                    "srcControllerId": "controller-2",
                                    "srcControllerIp": "172.24.120.189"
                                }
                            ]
                        },
                        "datastoreInfos": [
                            {
                                "clientHandle": "",
                                "extendedAttributes": [],
                                "name": "rcioc-nei-ds-vm01",
                                "objectId": "datastore-50",
                                "objectTypeName": "Datastore",
                                "revision": 1,
                                "type": {
                                    "name": "Datastore"
                                },
                                "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                            }
                        ],
                        "hostInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "itvircneiesx03.utility.pge.com",
                            "objectId": "host-86226",
                            "objectTypeName": "HostSystem",
                            "revision": 58,
                            "scope": {
                                "id": "domain-c46",
                                "name": "RC-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "HostSystem"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        },
                        "id": "controller-2",
                        "ipAddress": "172.24.120.189",
                        "resourcePoolInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "Resources",
                            "objectId": "resgroup-47",
                            "objectTypeName": "ResourcePool",
                            "revision": 239,
                            "scope": {
                                "id": "domain-c46",
                                "name": "RC-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "ResourcePool"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        },
                        "revision": 0,
                        "status": "RUNNING",
                        "upgradeAvailable": false,
                        "upgradeStatus": "UPGRADED",
                        "version": "6.1.45116",
                        "virtualMachineInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "NSX_Controller_e877e1bb-8a65-477e-9f41-8970907fbb4a",
                            "objectId": "vm-64",
                            "objectTypeName": "VirtualMachine",
                            "revision": 64,
                            "scope": {
                                "id": "domain-c46",
                                "name": "RC-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "VirtualMachine"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        }
                    },
                    "controller3": {
                        "clientHandle": "",
                        "clusterInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "RC-NEI-Cluster01",
                            "objectId": "domain-c46",
                            "objectTypeName": "ClusterComputeResource",
                            "revision": 148,
                            "scope": {
                                "id": "datacenter-2",
                                "name": "RC-Tenant-Datacenter01",
                                "objectTypeName": "Datacenter"
                            },
                            "type": {
                                "name": "ClusterComputeResource"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        },
                        "controllerClusterStatus": {
                            "controllerConnectivityList": [
                                {
                                    "destControllerIp": "172.24.120.188",
                                    "isDestActive": true,
                                    "lastRefreshedAt": 1473788385051,
                                    "pingStatus": "SUCCESS",
                                    "srcControllerId": "controller-3",
                                    "srcControllerIp": "172.24.120.190"
                                },
                                {
                                    "destControllerIp": "172.24.120.189",
                                    "isDestActive": true,
                                    "lastRefreshedAt": 1473788385051,
                                    "pingStatus": "SUCCESS",
                                    "srcControllerId": "controller-3",
                                    "srcControllerIp": "172.24.120.190"
                                }
                            ]
                        },
                        "datastoreInfos": [
                            {
                                "clientHandle": "",
                                "extendedAttributes": [],
                                "name": "rcioc-nei-ds-vm01",
                                "objectId": "datastore-50",
                                "objectTypeName": "Datastore",
                                "revision": 1,
                                "type": {
                                    "name": "Datastore"
                                },
                                "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                            }
                        ],
                        "hostInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "itvircneiesx02.utility.pge.com",
                            "objectId": "host-51",
                            "objectTypeName": "HostSystem",
                            "revision": 1057,
                            "scope": {
                                "id": "domain-c46",
                                "name": "RC-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "HostSystem"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        },
                        "id": "controller-3",
                        "ipAddress": "172.24.120.190",
                        "resourcePoolInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "Resources",
                            "objectId": "resgroup-47",
                            "objectTypeName": "ResourcePool",
                            "revision": 239,
                            "scope": {
                                "id": "domain-c46",
                                "name": "RC-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "ResourcePool"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        },
                        "revision": 0,
                        "status": "RUNNING",
                        "upgradeAvailable": false,
                        "upgradeStatus": "UPGRADED",
                        "version": "6.1.45116",
                        "virtualMachineInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "NSX_Controller_5f019cd6-6d53-4c84-b85e-117538b4391b",
                            "objectId": "vm-65",
                            "objectTypeName": "VirtualMachine",
                            "revision": 68,
                            "scope": {
                                "id": "domain-c46",
                                "name": "RC-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "VirtualMachine"
                            },
                            "vsmUuid": "421E8E23-972E-82FB-C17D-21E5E95A81D7"
                        }
                    }
                },
                "svt_single": {}
            }
        },
        "nsx-2": {
            "nsx-vdn": {
                "controllers": {
                    "controller1": {
                        "clientHandle": "",
                        "clusterInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "FX-NEI-Cluster01",
                            "objectId": "domain-c28",
                            "objectTypeName": "ClusterComputeResource",
                            "revision": 117,
                            "scope": {
                                "id": "datacenter-21",
                                "name": "FX-Tenant-Datacenter01",
                                "objectTypeName": "Datacenter"
                            },
                            "type": {
                                "name": "ClusterComputeResource"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        },
                        "controllerClusterStatus": {
                            "controllerConnectivityList": [
                                {
                                    "destControllerIp": "172.24.120.154",
                                    "isDestActive": true,
                                    "lastRefreshedAt": 1473788556536,
                                    "pingStatus": "SUCCESS",
                                    "srcControllerId": "controller-2",
                                    "srcControllerIp": "172.24.120.153"
                                },
                                {
                                    "destControllerIp": "172.24.120.155",
                                    "isDestActive": true,
                                    "lastRefreshedAt": 1473788556536,
                                    "pingStatus": "SUCCESS",
                                    "srcControllerId": "controller-2",
                                    "srcControllerIp": "172.24.120.153"
                                }
                            ]
                        },
                        "datastoreInfos": [
                            {
                                "clientHandle": "",
                                "extendedAttributes": [],
                                "name": "ffioc-nei-ds-vm02",
                                "objectId": "datastore-365",
                                "objectTypeName": "Datastore",
                                "revision": 1,
                                "type": {
                                    "name": "Datastore"
                                },
                                "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                            }
                        ],
                        "hostInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "itvifxneiesx04.utility.pge.com",
                            "objectId": "host-67704",
                            "objectTypeName": "HostSystem",
                            "revision": 82,
                            "scope": {
                                "id": "domain-c28",
                                "name": "FX-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "HostSystem"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        },
                        "id": "controller-2",
                        "ipAddress": "172.24.120.153",
                        "resourcePoolInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "Resources",
                            "objectId": "resgroup-29",
                            "objectTypeName": "ResourcePool",
                            "revision": 217,
                            "scope": {
                                "id": "domain-c28",
                                "name": "FX-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "ResourcePool"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        },
                        "revision": 0,
                        "status": "RUNNING",
                        "upgradeAvailable": false,
                        "upgradeStatus": "UPGRADED",
                        "version": "6.1.45116",
                        "virtualMachineInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "NSX_Controller_d3d92601-0703-4b1d-8516-a965860f1853",
                            "objectId": "vm-129",
                            "objectTypeName": "VirtualMachine",
                            "revision": 68,
                            "scope": {
                                "id": "domain-c28",
                                "name": "FX-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "VirtualMachine"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        }
                    },
                    "controller2": {
                        "clientHandle": "",
                        "clusterInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "FX-NEI-Cluster01",
                            "objectId": "domain-c28",
                            "objectTypeName": "ClusterComputeResource",
                            "revision": 117,
                            "scope": {
                                "id": "datacenter-21",
                                "name": "FX-Tenant-Datacenter01",
                                "objectTypeName": "Datacenter"
                            },
                            "type": {
                                "name": "ClusterComputeResource"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        },
                        "controllerClusterStatus": {
                            "controllerConnectivityList": [
                                {
                                    "destControllerIp": "172.24.120.153",
                                    "isDestActive": true,
                                    "lastRefreshedAt": 1473788556507,
                                    "pingStatus": "SUCCESS",
                                    "srcControllerId": "controller-3",
                                    "srcControllerIp": "172.24.120.154"
                                },
                                {
                                    "destControllerIp": "172.24.120.155",
                                    "isDestActive": true,
                                    "lastRefreshedAt": 1473788556507,
                                    "pingStatus": "SUCCESS",
                                    "srcControllerId": "controller-3",
                                    "srcControllerIp": "172.24.120.154"
                                }
                            ]
                        },
                        "datastoreInfos": [
                            {
                                "clientHandle": "",
                                "extendedAttributes": [],
                                "name": "ffioc-nei-ds-vm01",
                                "objectId": "datastore-39",
                                "objectTypeName": "Datastore",
                                "revision": 1,
                                "type": {
                                    "name": "Datastore"
                                },
                                "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                            }
                        ],
                        "hostInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "itvifxneiesx03.utility.pge.com",
                            "objectId": "host-67700",
                            "objectTypeName": "HostSystem",
                            "revision": 83,
                            "scope": {
                                "id": "domain-c28",
                                "name": "FX-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "HostSystem"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        },
                        "id": "controller-3",
                        "ipAddress": "172.24.120.154",
                        "resourcePoolInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "Resources",
                            "objectId": "resgroup-29",
                            "objectTypeName": "ResourcePool",
                            "revision": 217,
                            "scope": {
                                "id": "domain-c28",
                                "name": "FX-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "ResourcePool"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        },
                        "revision": 0,
                        "status": "RUNNING",
                        "upgradeAvailable": false,
                        "upgradeStatus": "UPGRADED",
                        "version": "6.1.45116",
                        "virtualMachineInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "NSX_Controller_1f96a7f9-8200-41b7-82ff-adc9e6c20600",
                            "objectId": "vm-130",
                            "objectTypeName": "VirtualMachine",
                            "revision": 57,
                            "scope": {
                                "id": "domain-c28",
                                "name": "FX-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "VirtualMachine"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        }
                    },
                    "controller3": {
                        "clientHandle": "",
                        "clusterInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "FX-NEI-Cluster01",
                            "objectId": "domain-c28",
                            "objectTypeName": "ClusterComputeResource",
                            "revision": 117,
                            "scope": {
                                "id": "datacenter-21",
                                "name": "FX-Tenant-Datacenter01",
                                "objectTypeName": "Datacenter"
                            },
                            "type": {
                                "name": "ClusterComputeResource"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        },
                        "controllerClusterStatus": {
                            "controllerConnectivityList": [
                                {
                                    "destControllerIp": "172.24.120.153",
                                    "isDestActive": true,
                                    "lastRefreshedAt": 1473788556483,
                                    "pingStatus": "SUCCESS",
                                    "srcControllerId": "controller-4",
                                    "srcControllerIp": "172.24.120.155"
                                },
                                {
                                    "destControllerIp": "172.24.120.154",
                                    "isDestActive": true,
                                    "lastRefreshedAt": 1473788556483,
                                    "pingStatus": "SUCCESS",
                                    "srcControllerId": "controller-4",
                                    "srcControllerIp": "172.24.120.155"
                                }
                            ]
                        },
                        "datastoreInfos": [
                            {
                                "clientHandle": "",
                                "extendedAttributes": [],
                                "name": "ffioc-nei-ds-vm01",
                                "objectId": "datastore-39",
                                "objectTypeName": "Datastore",
                                "revision": 1,
                                "type": {
                                    "name": "Datastore"
                                },
                                "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                            }
                        ],
                        "hostInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "itvifxneiesx02.utility.pge.com",
                            "objectId": "host-40",
                            "objectTypeName": "HostSystem",
                            "revision": 921,
                            "scope": {
                                "id": "domain-c28",
                                "name": "FX-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "HostSystem"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        },
                        "id": "controller-4",
                        "ipAddress": "172.24.120.155",
                        "resourcePoolInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "Resources",
                            "objectId": "resgroup-29",
                            "objectTypeName": "ResourcePool",
                            "revision": 217,
                            "scope": {
                                "id": "domain-c28",
                                "name": "FX-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "ResourcePool"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        },
                        "revision": 0,
                        "status": "RUNNING",
                        "upgradeAvailable": false,
                        "upgradeStatus": "UPGRADED",
                        "version": "6.1.45116",
                        "virtualMachineInfo": {
                            "clientHandle": "",
                            "extendedAttributes": [],
                            "name": "NSX_Controller_803c8988-a3f8-4b86-ae30-b524b635c05a",
                            "objectId": "vm-131",
                            "objectTypeName": "VirtualMachine",
                            "revision": 68,
                            "scope": {
                                "id": "domain-c28",
                                "name": "FX-NEI-Cluster01",
                                "objectTypeName": "ClusterComputeResource"
                            },
                            "type": {
                                "name": "VirtualMachine"
                            },
                            "vsmUuid": "423D33C2-07ED-16FC-54FD-99F86CE5740D"
                        }
                    }
                },
                "svt_single": {}
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
