http://localhost:5984/
Welcome
http://localhost:5984/svtdev
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/nsx-appliance_certificates.yaml
Checking for collect existence
http://localhost:5984/svtdev/_design/admin/_view/isnewcollect?reduce=true&startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]&group_level=2
http://localhost:5984/svtdev/_design/nsx-appliance/_view/certificates?startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]
{
    "data": {
        "nsx-1": {
            "nsx-appliance": {
                "certificates": {
                    "certificate1": {
                        "isCa": false,
                        "isValid": true,
                        "issuerCn": "itcldrcnsxmgt01.utility.pge.com",
                        "publicKeyAlgo": "RSA",
                        "publicKeyLength": "2048",
                        "rsaPublicKeyExponent": "10001",
                        "signature": "7f fa f4 90 08 09 0e 3d 53 bc 08 0b de 1b 92 22 75 06 7b be 44 16 51 ca 78 88 32 c3 a1 eb 0f b1 da f0 da 50 64 08 93 08 6b a7 8a f3 50 b8 20 ef 5b ef ef a9 16 8b 61 ea f0 9a bd cd 34 20 2b ac ea 83 3b 21 0f fa 21 8c cf e2 7d 20 38 f4 da dd be b0 5e 85 7b ac 35 ff 0c 24 d3 57 ed bb 5a 89 c9 32 70 27 e8 8e 4f bd 17 43 5f 44 16 e9 d5 8c 63 0f b8 ee 8b 1f bd 95 db 56 b9 3c a0 ae dd b7 c4 b5 18 83 66 9b 51 db 4d 74 ff bc c9 2d 18 54 5a b2 72 49 d4 37 72 26 c6 b7 a1 19 97 a1 4f c5 3a 8b aa 47 cf 82 f2 eb 80 95 93 7f db 79 d1 6e 95 36 99 63 ff b5 a4 64 9b 2a d4 a6 ee 4c 28 9f eb 21 42 df 29 dd be ee 90 cf da f8 7e 70 32 6f fc 8d 01 4b eb 2f c0 d3 14 0b 8c 83 af b4 be 53 d9 d2 07 d6 a5 bc 12 80 80 31 f1 36 eb eb bb 1c c2 97 24 62 24 fc 71 69 02 d1 e0 9b d4 de a4 5d",
                        "signatureAlgo": "SHA256WITHRSA",
                        "subjectCn": "itcldrcnsxmgt01.utility.pge.com",
                        "version": "3"
                    }
                }
            }
        },
        "nsx-2": {
            "nsx-appliance": {
                "certificates": {
                    "certificate1": {
                        "isCa": false,
                        "isValid": true,
                        "issuerCn": "itcldfxnsxmgt01.utility.pge.com",
                        "publicKeyAlgo": "RSA",
                        "publicKeyLength": "2048",
                        "rsaPublicKeyExponent": "10001",
                        "signature": "52 25 de 17 38 79 9e a8 71 96 9b a9 b5 5c c2 65 b6 14 ba 3a 9a 56 59 59 25 7d 68 a1 cc fd 0d ae 1f 8f 39 36 ce 12 dc 6e 46 c1 3a d8 1c b8 f1 b7 ec dd 9d 1b 46 c0 be 2e 30 2b ef 2c 21 ca b5 71 0a 62 e4 6e 0e e1 52 57 77 f1 39 07 6b e6 fe 8e 6c cf 93 59 b3 09 04 bd 57 22 bc c0 98 45 2d 1d 65 09 3d 6c d5 1c 7a e9 6e 65 a4 9b 33 65 24 40 3e 12 e3 6e 15 17 a9 a1 94 42 13 79 19 bf 79 c1 8e 05 e8 29 fa a9 cf 80 9c 9f 90 b1 2c e4 be fb 72 ce 9c e8 99 81 7a 83 6d 33 e7 c2 1e 2b 2c ff f2 65 94 c7 29 b6 71 d7 81 23 99 4c 24 c8 94 cd 41 4d 95 5a d7 44 0b 8a 25 87 07 5f fb 43 8a 91 ef 4b 87 1b 3d f8 6a f4 7c a6 40 42 02 19 e5 3c 1f 13 f8 31 25 e0 dd c9 ac cd 13 fd 87 ca 6a 19 18 a6 52 4c fa 5e ec d5 4c ef 04 1f 75 d2 5c 14 b5 1c e5 e3 64 ac 96 0e dd 44 fb 13 d3 e5 ec f5",
                        "signatureAlgo": "SHA256WITHRSA",
                        "subjectCn": "itcldfxnsxmgt01.utility.pge.com",
                        "version": "3"
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
