Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/nsxreport3.yaml
Checking for collect existence
{
    "data": {
        "nsx-1": {
            "nsx-edge": {
                "edge-19": {
                    "appliances": {
                        "RC Enterprise_ESG-0": {
                            "applianceSize": "large",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-48",
                            "hostName": "itvircneiesx01.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-20": {
                    "appliances": {
                        "RC Non Rep LB-0": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-48",
                            "hostName": "itvircneiesx01.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-21": {
                    "appliances": {
                        "RC-Prod-LB1-0": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-51",
                            "hostName": "itvircneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-28": {
                    "appliances": {
                        "RC-QA-DR-LB1-0": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-48",
                            "hostName": "itvircneiesx01.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-29": {
                    "appliances": {
                        "RC-Non-Prod-DR-LB1-0": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-48",
                            "hostName": "itvircneiesx01.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-30": {
                    "appliances": {
                        "RC Enterprise_ESG-2-0": {
                            "applianceSize": "large",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-51",
                            "hostName": "itvircneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-32": {
                    "appliances": {
                        "RC Non Prod LB1-0": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-48",
                            "hostName": "itvircneiesx01.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-33": {
                    "appliances": {
                        "RC QA LB1-0": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-48",
                            "hostName": "itvircneiesx01.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-36": {
                    "appliances": {
                        "RC-Production-DR-LB1-0": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-51",
                            "hostName": "itvircneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        },
                        "RC-Production-DR-LB1-1": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-48",
                            "hostName": "itvircneiesx01.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-37": {
                    "appliances": {
                        "RC-Automation-DLR-0": {
                            "applianceSize": "compact",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-51",
                            "hostName": "itvircneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        },
                        "RC-Automation-DLR-1": {
                            "applianceSize": "compact",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-48",
                            "hostName": "itvircneiesx01.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-38": {
                    "appliances": {
                        "RC VDI LDR-0": {
                            "applianceSize": "compact",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-51",
                            "hostName": "itvircneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        },
                        "RC VDI LDR-1": {
                            "applianceSize": "compact",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-48",
                            "hostName": "itvircneiesx01.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-6": {
                    "appliances": {
                        "RC Rep LDR-0": {
                            "applianceSize": "compact",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-51",
                            "hostName": "itvircneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        },
                        "RC Rep LDR-1": {
                            "applianceSize": "compact",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-48",
                            "hostName": "itvircneiesx01.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-7": {
                    "appliances": {
                        "RC Non Rep LDR-0": {
                            "applianceSize": "compact",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-51",
                            "hostName": "itvircneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        },
                        "RC Non Rep LDR-1": {
                            "applianceSize": "compact",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-48",
                            "hostName": "itvircneiesx01.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-9": {
                    "appliances": {
                        "RC-Automation-VRA-LB-0": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-48",
                            "hostName": "itvircneiesx01.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        },
                        "RC-Automation-VRA-LB-1": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-51",
                            "hostName": "itvircneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                }
            }
        },
        "nsx-2": {
            "nsx-edge": {
                "edge-10": {
                    "appliances": {
                        "FX-Enterprise_ESG-0": {
                            "applianceSize": "large",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-40",
                            "hostName": "itvifxneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-12": {
                    "appliances": {
                        "FX Non Rep LDR-0": {
                            "applianceSize": "compact",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-67700",
                            "hostName": "itvifxneiesx03.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        },
                        "FX Non Rep LDR-1": {
                            "applianceSize": "compact",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-40",
                            "hostName": "itvifxneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-15": {
                    "appliances": {
                        "RC-Automation-VRA-LB-0": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-67704",
                            "hostName": "itvifxneiesx04.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        },
                        "RC-Automation-VRA-LB-1": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-40",
                            "hostName": "itvifxneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-27": {
                    "appliances": {
                        "FX-Prod-LB1-0": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-40",
                            "hostName": "itvifxneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-28": {
                    "appliances": {
                        "FX-QA-LB1-0": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-67700",
                            "hostName": "itvifxneiesx03.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-31": {
                    "appliances": {
                        "FX-Non-Prod-LB1-0": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-67700",
                            "hostName": "itvifxneiesx03.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-32": {
                    "appliances": {
                        "FX-Non-Prod-DR-LB1-0": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-40",
                            "hostName": "itvifxneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-33": {
                    "appliances": {
                        "FX-QA-DR-LB1-0": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-40",
                            "hostName": "itvifxneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-36": {
                    "appliances": {
                        "FX Enterprise ESG-2-0": {
                            "applianceSize": "large",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-40",
                            "hostName": "itvifxneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-38": {
                    "appliances": {
                        "RC-Production-DR-LB1-0": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-40",
                            "hostName": "itvifxneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        },
                        "RC-Production-DR-LB1-1": {
                            "applianceSize": "xlarge",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-67700",
                            "hostName": "itvifxneiesx03.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-39": {
                    "appliances": {
                        "FX-Automation-Pod_DLR-0": {
                            "applianceSize": "compact",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-67700",
                            "hostName": "itvifxneiesx03.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        },
                        "FX-Automation-Pod_DLR-1": {
                            "applianceSize": "compact",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-40",
                            "hostName": "itvifxneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-40": {
                    "appliances": {
                        "FX-VDI-LDR-0": {
                            "applianceSize": "compact",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-67704",
                            "hostName": "itvifxneiesx04.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        },
                        "FX-VDI-LDR-1": {
                            "applianceSize": "compact",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-40",
                            "hostName": "itvifxneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                },
                "edge-8": {
                    "appliances": {
                        "FX-Rep LDR-0": {
                            "applianceSize": "compact",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-67704",
                            "hostName": "itvifxneiesx04.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        },
                        "FX-Rep LDR-1": {
                            "applianceSize": "compact",
                            "configuredDataStore": "svt_no_data",
                            "deployAppliances": true,
                            "hostId": "host-40",
                            "hostName": "itvifxneiesx02.utility.pge.com",
                            "memoryReservation": "svt_no_data"
                        }
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
