Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: yamldefs/rpa-clusters_settings.yaml
Checking for collect existence
{
    "data": {
        "rpa-1": {
            "rpa-clusters": {
                "settings": {
                    "3802441544150219833": {
                        "ampsSettings": [
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 3802441544150220000
                                    },
                                    "id": 208561698267745150
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [],
                                "name": "Internal XtremIO",
                                "systemGenerated": true,
                                "type": "XTREMIO"
                            },
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 3802441544150220000
                                    },
                                    "id": 280619292305673100
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [],
                                "name": "Internal VPLEX",
                                "systemGenerated": true,
                                "type": "VPLEX"
                            },
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 3802441544150220000
                                    },
                                    "id": 424734480381528960
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [],
                                "name": "Internal ScaleIO",
                                "systemGenerated": true,
                                "type": "SCALEIO"
                            },
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 3802441544150220000
                                    },
                                    "id": 136504104229817220
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [],
                                "name": "Internal VC",
                                "systemGenerated": true,
                                "type": "VC"
                            },
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 3802441544150220000
                                    },
                                    "id": 64446510191889280
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [
                                    {
                                        "arrayUID": {
                                            "clusterUID": {
                                                "id": 3802441544150220000
                                            },
                                            "id": 127557298984413060
                                        },
                                        "connetionParams": {
                                            "JsonSubType": "ClariionConnectionParams",
                                            "mgmtIP": {
                                                "ip": "172.24.125.45",
                                                "ipVersion": "IPV4"
                                            },
                                            "spbIP": {
                                                "ip": "172.24.125.46",
                                                "ipVersion": "IPV4"
                                            }
                                        },
                                        "credentials": {
                                            "JsonSubType": "ClariionCredentials",
                                            "authenticationType": "GLOBAL",
                                            "certificate": null,
                                            "credentialsType": "PASSWORD",
                                            "password": "QVJuNUR2TEVNclNIQzVNYWorUDJxRFUydUFQbDh3RHZMK3pjVFY1MGViZlZWSSt3bnBxbDliUzhPa1hCcENreTF2c2J6aG1IYVhaVnZKaVhoUWxpaFMwQmFQZUtRVVVqQ3lvam50a21heGZzMTZkY0hXKzh4SHVaTnpZS1pPYVlPZGZZelFtYkZvYXhqUXVUWDlMN2taaTlkTWJuVlZFdUpHYzQ2a3poK0lIUnlVNFJYUHlKUWQvWU1GZjI3S2NvVTVMcUFqUlpEaXZQVUh3RWZyYllLbDBJOUZJY05raEF1TWV3SGpiYU9HdkI4RU1JRVZOL0lEaU5JczJkRzNUWmh5aGRMV1M4ZVdUZVM5QkNlNXhqeVloZngxRTViTEZubE05RVMySUN4Vk9uM25hNlF5bWt5dWVVK2hxdm9zbmpmMTVoTXlWN3F6clM1ZTBzeGw1dDNSODFHZ25BNGdnV2lPdEhRV0RUeDZPN0NLZjRkQkxXNnNXVnRrU1JLN1NUNFZSQkhyVk5zTnJwcjU3Z0htekN1YmdZdVk0WHRoSHNBTENxcDJoZEZnU3NlcGJLYVlLSzJLMU1wMU9FZVdRalVaSnNGMkZZc0hpZnNKZGl4YW1xZlVNZW5HeWV6UXpIN1NMZ0xuWFlOcHZ0Nm1taGt1S2dhQWpYem93YWU3Y2s2OVNtTEVIZGlXZ1kxeUpwSmNDUm5LanFVYXpDalZVb2t3RFlmQVNvdityaw==",
                                            "username": "sysadmin"
                                        },
                                        "name": "APM00144937724-A",
                                        "resourcePools": [],
                                        "serialNumber": "APM00144937724",
                                        "type": "VNX"
                                    }
                                ],
                                "name": "Internal NaviSec",
                                "systemGenerated": true,
                                "type": "NAVISECCLI"
                            }
                        ],
                        "attachedPhoenixClusterName": "",
                        "autoRegistrationInfo": null,
                        "clusterIndex": 0,
                        "clusterName": "RCRPCluster01",
                        "clusterUID": {
                            "id": 3802441544150220000
                        },
                        "maintenanceMode": "NONE",
                        "repositoryVolume": {
                            "JsonSubType": "RepositoryVolumeSettings",
                            "clusterUID": {
                                "id": 3802441544150220000
                            },
                            "volumeInfo": {
                                "JsonSubType": "ClariionVolumeInformation",
                                "arraySerialNumber": "APM00144937724",
                                "groupSets": [],
                                "hasLicense": true,
                                "modelName": "VNX8000",
                                "naaUid": [
                                    96,
                                    6,
                                    1,
                                    96,
                                    26,
                                    0,
                                    53,
                                    0,
                                    29,
                                    57,
                                    -57,
                                    123,
                                    -15,
                                    -63,
                                    -28,
                                    17
                                ],
                                "onArrayWithRepository": true,
                                "productName": "VRAID",
                                "rawUid": [
                                    96,
                                    6,
                                    1,
                                    96,
                                    26,
                                    0,
                                    53,
                                    0,
                                    29,
                                    57,
                                    -57,
                                    123,
                                    -15,
                                    -63,
                                    -28,
                                    17
                                ],
                                "sizeInBytes": 6442450944,
                                "vendorName": "DGC",
                                "vendorSpecificInformation": null,
                                "volumeID": {
                                    "id": 8937670382969768000
                                },
                                "volumeName": "Recoverpoint Repository - LUN 200 (200)",
                                "volumeStorageType": "VNX_OR_CLARIION"
                            },
                            "volumeType": "REPOSITORY"
                        },
                        "rpasUIDs": [
                            {
                                "clusterUID": {
                                    "id": 3802441544150220000
                                },
                                "rpaNumber": 1
                            },
                            {
                                "clusterUID": {
                                    "id": 3802441544150220000
                                },
                                "rpaNumber": 2
                            }
                        ],
                        "softwareSerialId": "2428719EID380244154415",
                        "throttlePolicy": [],
                        "vcenterServers": [],
                        "vcenterServersFilters": []
                    },
                    "5939950745093422266": {
                        "ampsSettings": [
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 5939950745093422000
                                    },
                                    "id": 418363355572553000
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [],
                                "name": "Internal ScaleIO",
                                "systemGenerated": true,
                                "type": "SCALEIO"
                            },
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 5939950745093422000
                                    },
                                    "id": 58075385382913370
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [
                                    {
                                        "arrayUID": {
                                            "clusterUID": {
                                                "id": 5939950745093422000
                                            },
                                            "id": 84178859000517700
                                        },
                                        "connetionParams": {
                                            "JsonSubType": "ClariionConnectionParams",
                                            "mgmtIP": {
                                                "ip": "172.24.124.45",
                                                "ipVersion": "IPV4"
                                            },
                                            "spbIP": {
                                                "ip": "172.24.124.46",
                                                "ipVersion": "IPV4"
                                            }
                                        },
                                        "credentials": {
                                            "JsonSubType": "ClariionCredentials",
                                            "authenticationType": "GLOBAL",
                                            "certificate": null,
                                            "credentialsType": "PASSWORD",
                                            "password": "QWIwM0ZKQ3k4MnBWOTJhQXljZ0d6RDBxeWtOWGhGS09yaElMdmVUaHRLcXFaTVh1N2hDcFdGaG0xTkRVZWZjSTBGdE5oeXBrS0ZmbHhFTStSU0pjVmsyaTdIQ202ZFdpTmh1Q0pjR0xPbGtDL05USXBJVGFNUHltdWNTUTF2UEpWaDdIQm9WKzFqaERFTHdXQjRUeWI0b2lDUXdQTGNnbUxoemJLZzYxanFMN2hEYm1XNWFNQTc4RktFWGNVTDQzQXlycXN4UHJRM3ltYi9Db28zb1lYKzdlS2RTSjYvakt4SjFFTE1kdEpGdUZwWXpRb0t1QktxTVQrWlZIc0lCellwU0JxbzVOOHFIL2M5ZTR4Y1N6WUdIT0lER20rRVkxRTRqMmpHVjdQMFBOVmM5QXVGWmlXMWI5eDV2bWt0bXNQcDFoMzZMTWsweVNSWEpCbkRmOHozMXg4ODhyRFcwMWNYckNpME9pL21aYzB1eFRyT1huTlljWkhrRzdxeDJuT01CNzBpaERKQWRtdXZWTHZvNENUa0xTaGNocVpkUmFqNVB6alAvdE9pWGxKVGtJaDB4MVpTNnZQNnZGM2xweXN1YWpJaHVmUCsrZ2RIZ1QyZGhlVDdzeGRJRkx2cTc1R0tHM1lxTVpXRndkNmJPNWhmSkxoZWRxRXgzK2w0cVZKQVkzckFSNzM5YUEwVUNCVjRRNjBXbmRrMFd3Ukpia3R1TnhiVDZkY3Fvcg==",
                                            "username": "sysadmin"
                                        },
                                        "name": "APM00144937726-A",
                                        "resourcePools": [],
                                        "serialNumber": "APM00144937726",
                                        "type": "VNX"
                                    }
                                ],
                                "name": "Internal NaviSec",
                                "systemGenerated": true,
                                "type": "NAVISECCLI"
                            },
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 5939950745093422000
                                    },
                                    "id": 274248167496697180
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [],
                                "name": "Internal VPLEX",
                                "systemGenerated": true,
                                "type": "VPLEX"
                            },
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 5939950745093422000
                                    },
                                    "id": 202190573458769250
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [],
                                "name": "Internal XtremIO",
                                "systemGenerated": true,
                                "type": "XTREMIO"
                            },
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 5939950745093422000
                                    },
                                    "id": 130132979420841300
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [],
                                "name": "Internal VC",
                                "systemGenerated": true,
                                "type": "VC"
                            }
                        ],
                        "attachedPhoenixClusterName": "",
                        "autoRegistrationInfo": null,
                        "clusterIndex": 1,
                        "clusterName": "FFRPCluster01",
                        "clusterUID": {
                            "id": 5939950745093422000
                        },
                        "maintenanceMode": "NONE",
                        "repositoryVolume": {
                            "JsonSubType": "RepositoryVolumeSettings",
                            "clusterUID": {
                                "id": 5939950745093422000
                            },
                            "volumeInfo": {
                                "JsonSubType": "ClariionVolumeInformation",
                                "arraySerialNumber": "APM00144937726",
                                "groupSets": [],
                                "hasLicense": true,
                                "modelName": "VNX8000",
                                "naaUid": [
                                    96,
                                    6,
                                    1,
                                    96,
                                    10,
                                    -48,
                                    52,
                                    0,
                                    119,
                                    -34,
                                    -65,
                                    -78,
                                    -35,
                                    -63,
                                    -28,
                                    17
                                ],
                                "onArrayWithRepository": true,
                                "productName": "VRAID",
                                "rawUid": [
                                    96,
                                    6,
                                    1,
                                    96,
                                    10,
                                    -48,
                                    52,
                                    0,
                                    119,
                                    -34,
                                    -65,
                                    -78,
                                    -35,
                                    -63,
                                    -28,
                                    17
                                ],
                                "sizeInBytes": 6442450944,
                                "vendorName": "DGC",
                                "vendorSpecificInformation": null,
                                "volumeID": {
                                    "id": -2494630064061517300
                                },
                                "volumeName": "Recoverpoint Repository - LUN 200 (200)",
                                "volumeStorageType": "VNX_OR_CLARIION"
                            },
                            "volumeType": "REPOSITORY"
                        },
                        "rpasUIDs": [
                            {
                                "clusterUID": {
                                    "id": 5939950745093422000
                                },
                                "rpaNumber": 2
                            },
                            {
                                "clusterUID": {
                                    "id": 5939950745093422000
                                },
                                "rpaNumber": 1
                            }
                        ],
                        "softwareSerialId": "2428718EID593995074509",
                        "throttlePolicy": [],
                        "vcenterServers": [],
                        "vcenterServersFilters": []
                    }
                }
            }
        },
        "rpa-2": {
            "rpa-clusters": {
                "settings": {
                    "3802441544150219833": {
                        "ampsSettings": [
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 3802441544150220000
                                    },
                                    "id": 208561698267745150
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [],
                                "name": "Internal XtremIO",
                                "systemGenerated": true,
                                "type": "XTREMIO"
                            },
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 3802441544150220000
                                    },
                                    "id": 424734480381528960
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [],
                                "name": "Internal ScaleIO",
                                "systemGenerated": true,
                                "type": "SCALEIO"
                            },
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 3802441544150220000
                                    },
                                    "id": 64446510191889280
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [
                                    {
                                        "arrayUID": {
                                            "clusterUID": {
                                                "id": 3802441544150220000
                                            },
                                            "id": 127557298984413060
                                        },
                                        "connetionParams": {
                                            "JsonSubType": "ClariionConnectionParams",
                                            "mgmtIP": {
                                                "ip": "172.24.125.45",
                                                "ipVersion": "IPV4"
                                            },
                                            "spbIP": {
                                                "ip": "172.24.125.46",
                                                "ipVersion": "IPV4"
                                            }
                                        },
                                        "credentials": {
                                            "JsonSubType": "ClariionCredentials",
                                            "authenticationType": "GLOBAL",
                                            "certificate": null,
                                            "credentialsType": "PASSWORD",
                                            "password": "QVJuNUR2TEVNclNIQzVNYWorUDJxRFUydUFQbDh3RHZMK3pjVFY1MGViZlZWSSt3bnBxbDliUzhPa1hCcENreTF2c2J6aG1IYVhaVnZKaVhoUWxpaFMwQmFQZUtRVVVqQ3lvam50a21heGZzMTZkY0hXKzh4SHVaTnpZS1pPYVlPZGZZelFtYkZvYXhqUXVUWDlMN2taaTlkTWJuVlZFdUpHYzQ2a3poK0lIUnlVNFJYUHlKUWQvWU1GZjI3S2NvVTVMcUFqUlpEaXZQVUh3RWZyYllLbDBJOUZJY05raEF1TWV3SGpiYU9HdkI4RU1JRVZOL0lEaU5JczJkRzNUWmh5aGRMV1M4ZVdUZVM5QkNlNXhqeVloZngxRTViTEZubE05RVMySUN4Vk9uM25hNlF5bWt5dWVVK2hxdm9zbmpmMTVoTXlWN3F6clM1ZTBzeGw1dDNSODFHZ25BNGdnV2lPdEhRV0RUeDZPN0NLZjRkQkxXNnNXVnRrU1JLN1NUNFZSQkhyVk5zTnJwcjU3Z0htekN1YmdZdVk0WHRoSHNBTENxcDJoZEZnU3NlcGJLYVlLSzJLMU1wMU9FZVdRalVaSnNGMkZZc0hpZnNKZGl4YW1xZlVNZW5HeWV6UXpIN1NMZ0xuWFlOcHZ0Nm1taGt1S2dhQWpYem93YWU3Y2s2OVNtTEVIZGlXZ1kxeUpwSmNDUm5LanFVYXpDalZVb2t3RFlmQVNvdityaw==",
                                            "username": "sysadmin"
                                        },
                                        "name": "APM00144937724-A",
                                        "resourcePools": [],
                                        "serialNumber": "APM00144937724",
                                        "type": "VNX"
                                    }
                                ],
                                "name": "Internal NaviSec",
                                "systemGenerated": true,
                                "type": "NAVISECCLI"
                            },
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 3802441544150220000
                                    },
                                    "id": 136504104229817220
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [],
                                "name": "Internal VC",
                                "systemGenerated": true,
                                "type": "VC"
                            },
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 3802441544150220000
                                    },
                                    "id": 280619292305673100
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [],
                                "name": "Internal VPLEX",
                                "systemGenerated": true,
                                "type": "VPLEX"
                            }
                        ],
                        "attachedPhoenixClusterName": "",
                        "autoRegistrationInfo": null,
                        "clusterIndex": 0,
                        "clusterName": "RCRPCluster01",
                        "clusterUID": {
                            "id": 3802441544150220000
                        },
                        "maintenanceMode": "NONE",
                        "repositoryVolume": {
                            "JsonSubType": "RepositoryVolumeSettings",
                            "clusterUID": {
                                "id": 3802441544150220000
                            },
                            "volumeInfo": {
                                "JsonSubType": "ClariionVolumeInformation",
                                "arraySerialNumber": "APM00144937724",
                                "groupSets": [],
                                "hasLicense": true,
                                "modelName": "VNX8000",
                                "naaUid": [
                                    96,
                                    6,
                                    1,
                                    96,
                                    26,
                                    0,
                                    53,
                                    0,
                                    29,
                                    57,
                                    -57,
                                    123,
                                    -15,
                                    -63,
                                    -28,
                                    17
                                ],
                                "onArrayWithRepository": true,
                                "productName": "VRAID",
                                "rawUid": [
                                    96,
                                    6,
                                    1,
                                    96,
                                    26,
                                    0,
                                    53,
                                    0,
                                    29,
                                    57,
                                    -57,
                                    123,
                                    -15,
                                    -63,
                                    -28,
                                    17
                                ],
                                "sizeInBytes": 6442450944,
                                "vendorName": "DGC",
                                "vendorSpecificInformation": null,
                                "volumeID": {
                                    "id": 8937670382969768000
                                },
                                "volumeName": "Recoverpoint Repository - LUN 200 (200)",
                                "volumeStorageType": "VNX_OR_CLARIION"
                            },
                            "volumeType": "REPOSITORY"
                        },
                        "rpasUIDs": [
                            {
                                "clusterUID": {
                                    "id": 3802441544150220000
                                },
                                "rpaNumber": 1
                            },
                            {
                                "clusterUID": {
                                    "id": 3802441544150220000
                                },
                                "rpaNumber": 2
                            }
                        ],
                        "softwareSerialId": "2428719EID380244154415",
                        "throttlePolicy": [],
                        "vcenterServers": [],
                        "vcenterServersFilters": []
                    },
                    "5939950745093422266": {
                        "ampsSettings": [
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 5939950745093422000
                                    },
                                    "id": 274248167496697180
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [],
                                "name": "Internal VPLEX",
                                "systemGenerated": true,
                                "type": "VPLEX"
                            },
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 5939950745093422000
                                    },
                                    "id": 130132979420841300
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [],
                                "name": "Internal VC",
                                "systemGenerated": true,
                                "type": "VC"
                            },
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 5939950745093422000
                                    },
                                    "id": 202190573458769250
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [],
                                "name": "Internal XtremIO",
                                "systemGenerated": true,
                                "type": "XTREMIO"
                            },
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 5939950745093422000
                                    },
                                    "id": 418363355572553000
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [],
                                "name": "Internal ScaleIO",
                                "systemGenerated": true,
                                "type": "SCALEIO"
                            },
                            {
                                "ampUID": {
                                    "clusterUID": {
                                        "id": 5939950745093422000
                                    },
                                    "id": 58075385382913370
                                },
                                "connetionParams": null,
                                "credentials": null,
                                "managedArrays": [
                                    {
                                        "arrayUID": {
                                            "clusterUID": {
                                                "id": 5939950745093422000
                                            },
                                            "id": 84178859000517700
                                        },
                                        "connetionParams": {
                                            "JsonSubType": "ClariionConnectionParams",
                                            "mgmtIP": {
                                                "ip": "172.24.124.45",
                                                "ipVersion": "IPV4"
                                            },
                                            "spbIP": {
                                                "ip": "172.24.124.46",
                                                "ipVersion": "IPV4"
                                            }
                                        },
                                        "credentials": {
                                            "JsonSubType": "ClariionCredentials",
                                            "authenticationType": "GLOBAL",
                                            "certificate": null,
                                            "credentialsType": "PASSWORD",
                                            "password": "QWIwM0ZKQ3k4MnBWOTJhQXljZ0d6RDBxeWtOWGhGS09yaElMdmVUaHRLcXFaTVh1N2hDcFdGaG0xTkRVZWZjSTBGdE5oeXBrS0ZmbHhFTStSU0pjVmsyaTdIQ202ZFdpTmh1Q0pjR0xPbGtDL05USXBJVGFNUHltdWNTUTF2UEpWaDdIQm9WKzFqaERFTHdXQjRUeWI0b2lDUXdQTGNnbUxoemJLZzYxanFMN2hEYm1XNWFNQTc4RktFWGNVTDQzQXlycXN4UHJRM3ltYi9Db28zb1lYKzdlS2RTSjYvakt4SjFFTE1kdEpGdUZwWXpRb0t1QktxTVQrWlZIc0lCellwU0JxbzVOOHFIL2M5ZTR4Y1N6WUdIT0lER20rRVkxRTRqMmpHVjdQMFBOVmM5QXVGWmlXMWI5eDV2bWt0bXNQcDFoMzZMTWsweVNSWEpCbkRmOHozMXg4ODhyRFcwMWNYckNpME9pL21aYzB1eFRyT1huTlljWkhrRzdxeDJuT01CNzBpaERKQWRtdXZWTHZvNENUa0xTaGNocVpkUmFqNVB6alAvdE9pWGxKVGtJaDB4MVpTNnZQNnZGM2xweXN1YWpJaHVmUCsrZ2RIZ1QyZGhlVDdzeGRJRkx2cTc1R0tHM1lxTVpXRndkNmJPNWhmSkxoZWRxRXgzK2w0cVZKQVkzckFSNzM5YUEwVUNCVjRRNjBXbmRrMFd3Ukpia3R1TnhiVDZkY3Fvcg==",
                                            "username": "sysadmin"
                                        },
                                        "name": "APM00144937726-A",
                                        "resourcePools": [],
                                        "serialNumber": "APM00144937726",
                                        "type": "VNX"
                                    }
                                ],
                                "name": "Internal NaviSec",
                                "systemGenerated": true,
                                "type": "NAVISECCLI"
                            }
                        ],
                        "attachedPhoenixClusterName": "",
                        "autoRegistrationInfo": null,
                        "clusterIndex": 1,
                        "clusterName": "FFRPCluster01",
                        "clusterUID": {
                            "id": 5939950745093422000
                        },
                        "maintenanceMode": "NONE",
                        "repositoryVolume": {
                            "JsonSubType": "RepositoryVolumeSettings",
                            "clusterUID": {
                                "id": 5939950745093422000
                            },
                            "volumeInfo": {
                                "JsonSubType": "ClariionVolumeInformation",
                                "arraySerialNumber": "APM00144937726",
                                "groupSets": [],
                                "hasLicense": true,
                                "modelName": "VNX8000",
                                "naaUid": [
                                    96,
                                    6,
                                    1,
                                    96,
                                    10,
                                    -48,
                                    52,
                                    0,
                                    119,
                                    -34,
                                    -65,
                                    -78,
                                    -35,
                                    -63,
                                    -28,
                                    17
                                ],
                                "onArrayWithRepository": true,
                                "productName": "VRAID",
                                "rawUid": [
                                    96,
                                    6,
                                    1,
                                    96,
                                    10,
                                    -48,
                                    52,
                                    0,
                                    119,
                                    -34,
                                    -65,
                                    -78,
                                    -35,
                                    -63,
                                    -28,
                                    17
                                ],
                                "sizeInBytes": 6442450944,
                                "vendorName": "DGC",
                                "vendorSpecificInformation": null,
                                "volumeID": {
                                    "id": -2494630064061517300
                                },
                                "volumeName": "Recoverpoint Repository - LUN 200 (200)",
                                "volumeStorageType": "VNX_OR_CLARIION"
                            },
                            "volumeType": "REPOSITORY"
                        },
                        "rpasUIDs": [
                            {
                                "clusterUID": {
                                    "id": 5939950745093422000
                                },
                                "rpaNumber": 2
                            },
                            {
                                "clusterUID": {
                                    "id": 5939950745093422000
                                },
                                "rpaNumber": 1
                            }
                        ],
                        "softwareSerialId": "2428718EID593995074509",
                        "throttlePolicy": [],
                        "vcenterServers": [],
                        "vcenterServersFilters": []
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
