Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/simplemanager.yaml
Checking for collect existence
{
    "data": {
        "nsx-1": {
            "nsx-appliance": {
                "manager": {
                    "ipv6Address": null
                }
            }
        },
        "nsx-2": {
            "nsx-appliance": {
                "manager": {
                    "ipv6Address": null
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
