http://localhost:5984/
Welcome
http://localhost:5984/svtdev
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/vipr-vdc_storage-tiers.yaml
Checking for collect existence
http://localhost:5984/svtdev/_design/admin/_view/isnewcollect?reduce=true&startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]&group_level=2
http://localhost:5984/svtdev/_design/vipr-vdc/_view/storage-tiers?startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]
{
    "data": {
        "vipr-1": {
            "vipr-vdc": {
                "storage-tiers": {
                    "017a7570-12aa-474a-ba0e-68247f8483ce": {
                        "auto_tier_policy": [],
                        "creation_time": 1436542695270,
                        "disk_drive_technology": "SATA",
                        "global": false,
                        "id": "urn:storageos:StorageTier:017a7570-12aa-474a-ba0e-68247f8483ce:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-tiers/urn:storageos:StorageTier:017a7570-12aa-474a-ba0e-68247f8483ce:vdc1",
                            "rel": "self"
                        },
                        "name": "Capacity",
                        "native_guid": "CLARiiON+APM00144937726+TIER+Pool 0 - Prod_old+Capacity",
                        "percentage": "100",
                        "remote": false,
                        "tags": [],
                        "total_capacity": 161549196984,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "01a978c3-33bd-4cc6-b75b-c01380248acf": {
                        "auto_tier_policy": [],
                        "creation_time": 1433799194965,
                        "disk_drive_technology": "SATA",
                        "global": false,
                        "id": "urn:storageos:StorageTier:01a978c3-33bd-4cc6-b75b-c01380248acf:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-tiers/urn:storageos:StorageTier:01a978c3-33bd-4cc6-b75b-c01380248acf:vdc1",
                            "rel": "self"
                        },
                        "name": "Performance",
                        "native_guid": "CLARiiON+APM00144937724+TIER+Temp Pool - Loaner Disks+Performance",
                        "percentage": "100",
                        "remote": false,
                        "tags": [],
                        "total_capacity": 18426893312,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "1357a9ad-5657-4832-a74e-a7f5d233e4f1": {
                        "auto_tier_policy": [],
                        "creation_time": 1429028918791,
                        "disk_drive_technology": "SSD",
                        "global": false,
                        "id": "urn:storageos:StorageTier:1357a9ad-5657-4832-a74e-a7f5d233e4f1:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-tiers/urn:storageos:StorageTier:1357a9ad-5657-4832-a74e-a7f5d233e4f1:vdc1",
                            "rel": "self"
                        },
                        "name": "Extreme Performance",
                        "native_guid": "CLARiiON+APM00144937726+TIER+Pool 0 - Prod+Extreme Performance",
                        "percentage": "100",
                        "remote": false,
                        "tags": [],
                        "total_capacity": 2638115758,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "18e6e567-d196-48cd-9ca4-028b13acfb10": {
                        "auto_tier_policy": [],
                        "creation_time": 1428533672988,
                        "disk_drive_technology": "SATA",
                        "global": false,
                        "id": "urn:storageos:StorageTier:18e6e567-d196-48cd-9ca4-028b13acfb10:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-tiers/urn:storageos:StorageTier:18e6e567-d196-48cd-9ca4-028b13acfb10:vdc1",
                            "rel": "self"
                        },
                        "name": "Capacity",
                        "native_guid": "CLARiiON+APM00144937724+TIER+Pool 0+Capacity",
                        "percentage": "100",
                        "remote": false,
                        "tags": [],
                        "total_capacity": 161549196984,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "4015e1fc-18fe-4369-b84a-0daafa2b3db3": {
                        "auto_tier_policy": [],
                        "creation_time": 1428533672982,
                        "disk_drive_technology": "SATA",
                        "global": false,
                        "id": "urn:storageos:StorageTier:4015e1fc-18fe-4369-b84a-0daafa2b3db3:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-tiers/urn:storageos:StorageTier:4015e1fc-18fe-4369-b84a-0daafa2b3db3:vdc1",
                            "rel": "self"
                        },
                        "name": "Performance",
                        "native_guid": "CLARiiON+APM00144937724+TIER+Pool 0+Performance",
                        "percentage": "100",
                        "remote": false,
                        "tags": [],
                        "total_capacity": 116730497956,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "4bdd2035-ee03-46ba-a8ef-36f31395fa2c": {
                        "auto_tier_policy": [],
                        "creation_time": 1428533672974,
                        "disk_drive_technology": "SSD",
                        "global": false,
                        "id": "urn:storageos:StorageTier:4bdd2035-ee03-46ba-a8ef-36f31395fa2c:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-tiers/urn:storageos:StorageTier:4bdd2035-ee03-46ba-a8ef-36f31395fa2c:vdc1",
                            "rel": "self"
                        },
                        "name": "Extreme Performance",
                        "native_guid": "CLARiiON+APM00144937724+TIER+Pool 0+Extreme Performance",
                        "percentage": "100",
                        "remote": false,
                        "tags": [],
                        "total_capacity": 3072547881,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "8c0c9c4d-62ae-44c1-9959-13064bcdd847": {
                        "auto_tier_policy": [],
                        "creation_time": 1436542695261,
                        "disk_drive_technology": "SSD",
                        "global": false,
                        "id": "urn:storageos:StorageTier:8c0c9c4d-62ae-44c1-9959-13064bcdd847:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-tiers/urn:storageos:StorageTier:8c0c9c4d-62ae-44c1-9959-13064bcdd847:vdc1",
                            "rel": "self"
                        },
                        "name": "Extreme Performance",
                        "native_guid": "CLARiiON+APM00144937726+TIER+Pool 0 - Prod_old+Extreme Performance",
                        "percentage": "100",
                        "remote": false,
                        "tags": [],
                        "total_capacity": 3072547881,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "d1baa836-58b6-4cb0-9611-14e3ceee3058": {
                        "auto_tier_policy": [],
                        "creation_time": 1434670396343,
                        "disk_drive_technology": "SATA",
                        "global": false,
                        "id": "urn:storageos:StorageTier:d1baa836-58b6-4cb0-9611-14e3ceee3058:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-tiers/urn:storageos:StorageTier:d1baa836-58b6-4cb0-9611-14e3ceee3058:vdc1",
                            "rel": "self"
                        },
                        "name": "Performance",
                        "native_guid": "CLARiiON+APM00144937726+TIER+Temp Pool - Loaner Disks+Performance",
                        "percentage": "100",
                        "remote": false,
                        "tags": [],
                        "total_capacity": 18456311235,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "d2229937-5871-4f70-9112-0295258a0d78": {
                        "auto_tier_policy": [],
                        "creation_time": 1436542695266,
                        "disk_drive_technology": "SATA",
                        "global": false,
                        "id": "urn:storageos:StorageTier:d2229937-5871-4f70-9112-0295258a0d78:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-tiers/urn:storageos:StorageTier:d2229937-5871-4f70-9112-0295258a0d78:vdc1",
                            "rel": "self"
                        },
                        "name": "Performance",
                        "native_guid": "CLARiiON+APM00144937726+TIER+Pool 0 - Prod_old+Performance",
                        "percentage": "100",
                        "remote": false,
                        "tags": [],
                        "total_capacity": 117662013194,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "d7e13da4-35ce-455d-b0b4-54749cc38981": {
                        "auto_tier_policy": [],
                        "creation_time": 1429028918805,
                        "disk_drive_technology": "SATA",
                        "global": false,
                        "id": "urn:storageos:StorageTier:d7e13da4-35ce-455d-b0b4-54749cc38981:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-tiers/urn:storageos:StorageTier:d7e13da4-35ce-455d-b0b4-54749cc38981:vdc1",
                            "rel": "self"
                        },
                        "name": "Capacity",
                        "native_guid": "CLARiiON+APM00144937726+TIER+Pool 0 - Prod+Capacity",
                        "percentage": "100",
                        "remote": false,
                        "tags": [],
                        "total_capacity": 161549193380,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "ef4a8c0a-1416-4d0e-ab15-b9ec09e1521e": {
                        "auto_tier_policy": [],
                        "creation_time": 1429028918801,
                        "disk_drive_technology": "SATA",
                        "global": false,
                        "id": "urn:storageos:StorageTier:ef4a8c0a-1416-4d0e-ab15-b9ec09e1521e:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-tiers/urn:storageos:StorageTier:ef4a8c0a-1416-4d0e-ab15-b9ec09e1521e:vdc1",
                            "rel": "self"
                        },
                        "name": "Performance",
                        "native_guid": "CLARiiON+APM00144937726+TIER+Pool 0 - Prod+Performance",
                        "percentage": "100",
                        "remote": false,
                        "tags": [],
                        "total_capacity": 117662013194,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
