http://localhost:5984/
Welcome
http://localhost:5984/svtdev
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/vipr_cg.yaml
Checking for collect existence
http://localhost:5984/svtdev/_design/admin/_view/isnewcollect?reduce=true&startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]&group_level=2
http://localhost:5984/svtdev/_design/vipr-block/_view/consistency-groups?startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]
{
    "data": {
        "vipr-1": {
            "vipr-block": {
                "consistency-groups": {
                    "09fce068-3c1b-4ecb-9326-e99e87fb4df3.json": {
                        "name": "RC-Tenant-DR-Cluster01_vPool-VNX7724-RC-DR-Tier_1440424856159",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "0b9d2e16-7c94-4e08-82fa-8c699939b3ce.json": {
                        "name": "RC-Tenant-DR-Cluster01_vPool-VNX7724-RC-DR-Tier_1440514468763",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "1a8b0b41-3578-40d4-a00b-82b17ea638f0.json": {
                        "name": "RC-Tenant-DR-Cluster01_vPool-VNX7724-RC-DR-Tier_1439500459003",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "1e7e15bc-6307-42c2-93b7-547f931d8960.json": {
                        "name": "CG_Rob_Test",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "2158001a-d278-4f40-b1e4-cba3d4be5254.json": {
                        "name": "Tier2_1461292301630",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "2c4733fe-a518-4935-87fb-b1831e69d146.json": {
                        "name": "Tier1_1461271216074",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "300ac1a8-1da8-48c1-bb61-6c4bb0405afd.json": {
                        "name": "RC-Tenant-DR-Cluster01_Tier1_1441216140442",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "342d6d1a-0c82-4ccf-8e5e-bf41f190dba7.json": {
                        "name": "RC-Tenant-DR-Cluster01_vPool-VNX7724-RC-DR-Tier_1439223196872",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "35ba1426-b1c7-43bb-9577-1bbfd89c9a70.json": {
                        "name": "RC-Tenant-DR-Cluster01_vPool-VNX7724-RC-DR-Tier_1439315303684",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "418ad962-892b-4de5-861b-51ed7dce079c.json": {
                        "name": "RC-Tenant-DR-Cluster01_vPool-VNX7724-RC-DR-Tier_1438882531049",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "4578949e-74e9-4907-9dc3-d4a9962662a3.json": {
                        "name": "Tier1_1461314420954",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "5a6235f2-5f9e-4bd8-b9f8-a7edf1f3d971.json": {
                        "name": "RC-Tenant-DR-Cluster01_Tier1_1440787488582",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "5f661c80-37a0-4f33-a327-f7c516091b61.json": {
                        "name": "Tier2_1450463564957",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "65bbc4e5-6698-4ad4-a555-97efa141e73d.json": {
                        "name": "CGforRC",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "6aed4120-33b2-48ed-b0c4-dc4274ae7b56.json": {
                        "name": "Tier2_1461349974181",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "bd6bad22-4113-4155-8aea-994194485c4c.json": {
                        "name": "Tier1_1461291049851",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "d096d72c-e2c9-4d82-8df2-c338e1c23108.json": {
                        "name": "Tier1_1461593412706",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "d3b5046e-8a97-4966-aa65-a57b29619499.json": {
                        "name": "Tier2_1461592865949",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    },
                    "edd140bf-f4bc-45c6-b3d2-6e83baa7ee57.json": {
                        "name": "RC-Tenant-DR-Cluster01_vPool-VNX7724-RC-DR-Tier_1440004100935",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        }
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
