http://localhost:5984/
Welcome
http://localhost:5984/svtdev
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/vipr-tenant_tenants.yaml
Checking for collect existence
http://localhost:5984/svtdev/_design/admin/_view/isnewcollect?reduce=true&startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]&group_level=2
http://localhost:5984/svtdev/_design/vipr-tenant/_view/tenants?startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]
{
    "data": {
        "vipr-1": {
            "vipr-tenant": {
                "tenants": {
                    "70f84a12-6ce1-4b50-b616-06ac71c8f94f": {
                        "description": "Root Provider Tenant",
                        "name": "Provider Tenant"
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
