Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/vipr-vdc_simple-storage-systems.yaml
Checking for collect existence
{
    "data": {
        "vipr-1": {
            "vipr-vdc": {
                "storage-systems": {
                    "10d14f9a-cc42-4286-becc-9a396bafee41.json": {
                        "model": "Rack Mounted VNX8000",
                        "name": "CLARIION+APM00144937724"
                    },
                    "94eff137-6f58-45d3-b6f9-cd12497edbb2.json": {
                        "model": "Rack Mounted VNX8000",
                        "name": "CLARIION+APM00144937726"
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
