http://localhost:5984/
Welcome
http://localhost:5984/svtdev
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/vipr-vdc_storage-pools.yaml
Checking for collect existence
http://localhost:5984/svtdev/_design/admin/_view/isnewcollect?reduce=true&startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]&group_level=2
http://localhost:5984/svtdev/_design/vipr-vdc/_view/storage-pools?startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]
{
    "data": {
        "vipr-1": {
            "vipr-vdc": {
                "storage-pools": {
                    "339b5640-0c2f-4193-8c3b-460924f47a2e.json": {
                        "assigned_varrays": [],
                        "auto_tiering_supported": false,
                        "compatibility_status": "COMPATIBLE",
                        "connected_varrays": [
                            "urn:storageos:VirtualArray:091eef95-c33a-4e09-9842-ed54658a790f:vdc1",
                            "urn:storageos:VirtualArray:7a35a458-a44e-4459-9247-8d55a59eab3e:vdc1"
                        ],
                        "controller_params": [],
                        "copy_types": [
                            "UNSYNC_UNASSOC",
                            "SYNC",
                            "UNSYNC_ASSOC"
                        ],
                        "creation_time": 1429028918197,
                        "discovery_status": "VISIBLE",
                        "drive_types": [
                            "SAS",
                            "NL_SAS",
                            "SSD"
                        ],
                        "free_gb": 422817,
                        "global": false,
                        "id": "urn:storageos:StoragePool:339b5640-0c2f-4193-8c3b-460924f47a2e:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-systems/urn:storageos:StorageSystem:94eff137-6f58-45d3-b6f9-cd12497edbb2:vdc1/storage-pools/urn:storageos:StoragePool:339b5640-0c2f-4193-8c3b-460924f47a2e:vdc1",
                            "rel": "self"
                        },
                        "long_term_retention": false,
                        "max_pool_utilization_percentage": 75,
                        "max_resources": -1,
                        "max_thin_pool_subscription_percentage": 300,
                        "maximum_thick_volume_size_gb": 262144,
                        "maximum_thin_volume_size_gb": 262144,
                        "minimum_thick_volume_size_gb": 0,
                        "minimum_thin_volume_size_gb": 0,
                        "name": "CLARIION+APM00144937726+POOL+U+Pool 0 - Prod",
                        "native_guid": "CLARIION+APM00144937726+POOL+U+Pool 0 - Prod",
                        "num_resources": 71,
                        "operational_status": "READY",
                        "percent_subscribed": 135,
                        "percent_used": 22,
                        "pool_name": "Pool 0 - Prod",
                        "pool_service_type": "block",
                        "protocols": [
                            "FC"
                        ],
                        "raid_levels": [
                            "RAID6"
                        ],
                        "registration_status": "REGISTERED",
                        "remote": false,
                        "storage_system": {
                            "id": "urn:storageos:StorageSystem:94eff137-6f58-45d3-b6f9-cd12497edbb2:vdc1",
                            "link": {
                                "href": "/vdc/storage-systems/urn:storageos:StorageSystem:94eff137-6f58-45d3-b6f9-cd12497edbb2:vdc1",
                                "rel": "self"
                            }
                        },
                        "subscribed_gb": 726979,
                        "supported_resource_types": "THIN_AND_THICK",
                        "tagged_varrays": [
                            "urn:storageos:VirtualArray:091eef95-c33a-4e09-9842-ed54658a790f:vdc1",
                            "urn:storageos:VirtualArray:7a35a458-a44e-4459-9247-8d55a59eab3e:vdc1"
                        ],
                        "tags": [],
                        "thin_volume_preallocation_supported": false,
                        "tier_utilization_percentages": [
                            {
                                "name": "SATA",
                                "value": "100"
                            },
                            {
                                "name": "SSD",
                                "value": "100"
                            }
                        ],
                        "usable_gb": 540519,
                        "used_gb": 117702,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "3f44c57f-a176-4514-8eae-bd03eddef2b5.json": {
                        "assigned_varrays": [],
                        "auto_tiering_supported": false,
                        "compatibility_status": "COMPATIBLE",
                        "connected_varrays": [
                            "urn:storageos:VirtualArray:b60c49fd-4bdc-4752-ae20-7895868a9f8a:vdc1",
                            "urn:storageos:VirtualArray:4687b6ca-3741-4bc1-9e65-c6a6c072dad2:vdc1"
                        ],
                        "controller_params": [],
                        "copy_types": [
                            "UNSYNC_UNASSOC",
                            "SYNC",
                            "UNSYNC_ASSOC"
                        ],
                        "creation_time": 1428533672203,
                        "discovery_status": "VISIBLE",
                        "drive_types": [
                            "SAS",
                            "NL_SAS",
                            "SSD"
                        ],
                        "free_gb": 410000,
                        "global": false,
                        "id": "urn:storageos:StoragePool:3f44c57f-a176-4514-8eae-bd03eddef2b5:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-systems/urn:storageos:StorageSystem:10d14f9a-cc42-4286-becc-9a396bafee41:vdc1/storage-pools/urn:storageos:StoragePool:3f44c57f-a176-4514-8eae-bd03eddef2b5:vdc1",
                            "rel": "self"
                        },
                        "long_term_retention": false,
                        "max_pool_utilization_percentage": 75,
                        "max_resources": -1,
                        "max_thin_pool_subscription_percentage": 300,
                        "maximum_thick_volume_size_gb": 262144,
                        "maximum_thin_volume_size_gb": 262144,
                        "minimum_thick_volume_size_gb": 0,
                        "minimum_thin_volume_size_gb": 0,
                        "name": "CLARIION+APM00144937724+POOL+U+Pool 0",
                        "native_guid": "CLARIION+APM00144937724+POOL+U+Pool 0",
                        "num_resources": 69,
                        "operational_status": "READY",
                        "percent_subscribed": 133,
                        "percent_used": 25,
                        "pool_name": "Pool 0",
                        "pool_service_type": "block",
                        "protocols": [
                            "FC"
                        ],
                        "raid_levels": [
                            "RAID6"
                        ],
                        "registration_status": "REGISTERED",
                        "remote": false,
                        "storage_system": {
                            "id": "urn:storageos:StorageSystem:10d14f9a-cc42-4286-becc-9a396bafee41:vdc1",
                            "link": {
                                "href": "/vdc/storage-systems/urn:storageos:StorageSystem:10d14f9a-cc42-4286-becc-9a396bafee41:vdc1",
                                "rel": "self"
                            }
                        },
                        "subscribed_gb": 716017,
                        "supported_resource_types": "THIN_AND_THICK",
                        "tagged_varrays": [
                            "urn:storageos:VirtualArray:b60c49fd-4bdc-4752-ae20-7895868a9f8a:vdc1",
                            "urn:storageos:VirtualArray:4687b6ca-3741-4bc1-9e65-c6a6c072dad2:vdc1"
                        ],
                        "tags": [],
                        "thin_volume_preallocation_supported": false,
                        "tier_utilization_percentages": [
                            {
                                "name": "SATA",
                                "value": "100"
                            },
                            {
                                "name": "SSD",
                                "value": "100"
                            }
                        ],
                        "usable_gb": 540519,
                        "used_gb": 130519,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "a31a325c-8851-44f5-9c0b-dc607d8d803a.json": {
                        "assigned_varrays": [],
                        "auto_tiering_supported": false,
                        "compatibility_status": "COMPATIBLE",
                        "connected_varrays": [
                            "urn:storageos:VirtualArray:091eef95-c33a-4e09-9842-ed54658a790f:vdc1",
                            "urn:storageos:VirtualArray:7a35a458-a44e-4459-9247-8d55a59eab3e:vdc1"
                        ],
                        "controller_params": [],
                        "copy_types": [
                            "UNSYNC_UNASSOC",
                            "SYNC",
                            "UNSYNC_ASSOC"
                        ],
                        "creation_time": 1434670394543,
                        "discovery_status": "NOTVISIBLE",
                        "drive_types": [
                            "SAS"
                        ],
                        "free_gb": 17573,
                        "global": false,
                        "id": "urn:storageos:StoragePool:a31a325c-8851-44f5-9c0b-dc607d8d803a:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-systems/urn:storageos:StorageSystem:94eff137-6f58-45d3-b6f9-cd12497edbb2:vdc1/storage-pools/urn:storageos:StoragePool:a31a325c-8851-44f5-9c0b-dc607d8d803a:vdc1",
                            "rel": "self"
                        },
                        "long_term_retention": false,
                        "max_pool_utilization_percentage": 75,
                        "max_resources": -1,
                        "max_thin_pool_subscription_percentage": 300,
                        "maximum_thick_volume_size_gb": 17225,
                        "maximum_thin_volume_size_gb": 262144,
                        "minimum_thick_volume_size_gb": 0,
                        "minimum_thin_volume_size_gb": 0,
                        "name": "CLARIION+APM00144937726+POOL+U+Temp Pool - Loaner Disks",
                        "native_guid": "CLARIION+APM00144937726+POOL+U+Temp Pool - Loaner Disks",
                        "num_resources": 0,
                        "operational_status": "READY",
                        "percent_subscribed": 1,
                        "percent_used": 1,
                        "pool_name": "Temp Pool - Loaner Disks",
                        "pool_service_type": "block",
                        "protocols": [
                            "FC"
                        ],
                        "raid_levels": [
                            "RAID5"
                        ],
                        "registration_status": "UNREGISTERED",
                        "remote": false,
                        "storage_system": {
                            "id": "urn:storageos:StorageSystem:94eff137-6f58-45d3-b6f9-cd12497edbb2:vdc1",
                            "link": {
                                "href": "/vdc/storage-systems/urn:storageos:StorageSystem:94eff137-6f58-45d3-b6f9-cd12497edbb2:vdc1",
                                "rel": "self"
                            }
                        },
                        "subscribed_gb": 29,
                        "supported_resource_types": "THIN_AND_THICK",
                        "tagged_varrays": [
                            "urn:storageos:VirtualArray:091eef95-c33a-4e09-9842-ed54658a790f:vdc1",
                            "urn:storageos:VirtualArray:7a35a458-a44e-4459-9247-8d55a59eab3e:vdc1"
                        ],
                        "tags": [],
                        "thin_volume_preallocation_supported": false,
                        "tier_utilization_percentages": [
                            {
                                "name": "SATA",
                                "value": "100"
                            }
                        ],
                        "usable_gb": 17601,
                        "used_gb": 28,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "a58f5819-033d-4845-b537-2a0048c31192.json": {
                        "assigned_varrays": [],
                        "auto_tiering_supported": false,
                        "compatibility_status": "COMPATIBLE",
                        "connected_varrays": [
                            "urn:storageos:VirtualArray:091eef95-c33a-4e09-9842-ed54658a790f:vdc1",
                            "urn:storageos:VirtualArray:7a35a458-a44e-4459-9247-8d55a59eab3e:vdc1"
                        ],
                        "controller_params": [],
                        "copy_types": [
                            "UNSYNC_UNASSOC",
                            "SYNC",
                            "UNSYNC_ASSOC"
                        ],
                        "creation_time": 1436542693231,
                        "discovery_status": "NOTVISIBLE",
                        "drive_types": [
                            "SAS",
                            "NL_SAS",
                            "SSD"
                        ],
                        "free_gb": 268792,
                        "global": false,
                        "id": "urn:storageos:StoragePool:a58f5819-033d-4845-b537-2a0048c31192:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-systems/urn:storageos:StorageSystem:94eff137-6f58-45d3-b6f9-cd12497edbb2:vdc1/storage-pools/urn:storageos:StoragePool:a58f5819-033d-4845-b537-2a0048c31192:vdc1",
                            "rel": "self"
                        },
                        "long_term_retention": false,
                        "max_pool_utilization_percentage": 75,
                        "max_resources": -1,
                        "max_thin_pool_subscription_percentage": 300,
                        "maximum_thick_volume_size_gb": 262144,
                        "maximum_thin_volume_size_gb": 262144,
                        "minimum_thick_volume_size_gb": 0,
                        "minimum_thin_volume_size_gb": 0,
                        "name": "CLARIION+APM00144937726+POOL+U+Pool 0 - Prod_old",
                        "native_guid": "CLARIION+APM00144937726+POOL+U+Pool 0 - Prod_old",
                        "num_resources": 0,
                        "operational_status": "READY",
                        "percent_subscribed": 1,
                        "percent_used": 1,
                        "pool_name": "Pool 0 - Prod_old",
                        "pool_service_type": "block",
                        "protocols": [
                            "FC"
                        ],
                        "raid_levels": [
                            "RAID6",
                            "RAID5"
                        ],
                        "registration_status": "UNREGISTERED",
                        "remote": false,
                        "storage_system": {
                            "id": "urn:storageos:StorageSystem:94eff137-6f58-45d3-b6f9-cd12497edbb2:vdc1",
                            "link": {
                                "href": "/vdc/storage-systems/urn:storageos:StorageSystem:94eff137-6f58-45d3-b6f9-cd12497edbb2:vdc1",
                                "rel": "self"
                            }
                        },
                        "subscribed_gb": 415,
                        "supported_resource_types": "THIN_AND_THICK",
                        "tagged_varrays": [
                            "urn:storageos:VirtualArray:091eef95-c33a-4e09-9842-ed54658a790f:vdc1",
                            "urn:storageos:VirtualArray:7a35a458-a44e-4459-9247-8d55a59eab3e:vdc1"
                        ],
                        "tags": [],
                        "thin_volume_preallocation_supported": false,
                        "tier_utilization_percentages": [
                            {
                                "name": "SATA",
                                "value": "100"
                            },
                            {
                                "name": "SSD",
                                "value": "100"
                            }
                        ],
                        "usable_gb": 269206,
                        "used_gb": 414,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "cfc82b99-c33a-4c49-a92a-df961f9e6685.json": {
                        "assigned_varrays": [],
                        "auto_tiering_supported": false,
                        "compatibility_status": "COMPATIBLE",
                        "connected_varrays": [
                            "urn:storageos:VirtualArray:b60c49fd-4bdc-4752-ae20-7895868a9f8a:vdc1",
                            "urn:storageos:VirtualArray:4687b6ca-3741-4bc1-9e65-c6a6c072dad2:vdc1"
                        ],
                        "controller_params": [],
                        "copy_types": [
                            "UNSYNC_UNASSOC",
                            "SYNC",
                            "UNSYNC_ASSOC"
                        ],
                        "creation_time": 1437597327630,
                        "discovery_status": "VISIBLE",
                        "drive_types": [
                            "SAS"
                        ],
                        "free_gb": 1071,
                        "global": false,
                        "id": "urn:storageos:StoragePool:cfc82b99-c33a-4c49-a92a-df961f9e6685:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-systems/urn:storageos:StorageSystem:10d14f9a-cc42-4286-becc-9a396bafee41:vdc1/storage-pools/urn:storageos:StoragePool:cfc82b99-c33a-4c49-a92a-df961f9e6685:vdc1",
                            "rel": "self"
                        },
                        "long_term_retention": false,
                        "max_pool_utilization_percentage": 75,
                        "max_resources": -1,
                        "max_thin_pool_subscription_percentage": 300,
                        "maximum_thick_volume_size_gb": 1049,
                        "maximum_thin_volume_size_gb": 0,
                        "minimum_thick_volume_size_gb": 0,
                        "minimum_thin_volume_size_gb": 0,
                        "name": "CLARIION+APM00144937724+POOL+C+0978",
                        "native_guid": "CLARIION+APM00144937724+POOL+C+0978",
                        "num_resources": 0,
                        "operational_status": "READY",
                        "percent_subscribed": 1,
                        "percent_used": 1,
                        "pool_name": "0978",
                        "pool_service_type": "block",
                        "protocols": [
                            "FC"
                        ],
                        "raid_levels": [
                            "RAID5"
                        ],
                        "registration_status": "REGISTERED",
                        "remote": false,
                        "storage_system": {
                            "id": "urn:storageos:StorageSystem:10d14f9a-cc42-4286-becc-9a396bafee41:vdc1",
                            "link": {
                                "href": "/vdc/storage-systems/urn:storageos:StorageSystem:10d14f9a-cc42-4286-becc-9a396bafee41:vdc1",
                                "rel": "self"
                            }
                        },
                        "subscribed_gb": 2,
                        "supported_resource_types": "THICK_ONLY",
                        "tagged_varrays": [
                            "urn:storageos:VirtualArray:b60c49fd-4bdc-4752-ae20-7895868a9f8a:vdc1",
                            "urn:storageos:VirtualArray:4687b6ca-3741-4bc1-9e65-c6a6c072dad2:vdc1"
                        ],
                        "tags": [],
                        "thin_volume_preallocation_supported": false,
                        "tier_utilization_percentages": [],
                        "usable_gb": 1073,
                        "used_gb": 2,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    },
                    "da0101cd-c257-44db-af75-a913538bd0a3.json": {
                        "assigned_varrays": [],
                        "auto_tiering_supported": false,
                        "compatibility_status": "COMPATIBLE",
                        "connected_varrays": [
                            "urn:storageos:VirtualArray:b60c49fd-4bdc-4752-ae20-7895868a9f8a:vdc1",
                            "urn:storageos:VirtualArray:4687b6ca-3741-4bc1-9e65-c6a6c072dad2:vdc1"
                        ],
                        "controller_params": [],
                        "copy_types": [
                            "UNSYNC_UNASSOC",
                            "SYNC",
                            "UNSYNC_ASSOC"
                        ],
                        "creation_time": 1433799193306,
                        "discovery_status": "NOTVISIBLE",
                        "drive_types": [
                            "SAS"
                        ],
                        "free_gb": 17573,
                        "global": false,
                        "id": "urn:storageos:StoragePool:da0101cd-c257-44db-af75-a913538bd0a3:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/vdc/storage-systems/urn:storageos:StorageSystem:10d14f9a-cc42-4286-becc-9a396bafee41:vdc1/storage-pools/urn:storageos:StoragePool:da0101cd-c257-44db-af75-a913538bd0a3:vdc1",
                            "rel": "self"
                        },
                        "long_term_retention": false,
                        "max_pool_utilization_percentage": 75,
                        "max_resources": -1,
                        "max_thin_pool_subscription_percentage": 300,
                        "maximum_thick_volume_size_gb": 17225,
                        "maximum_thin_volume_size_gb": 262144,
                        "minimum_thick_volume_size_gb": 0,
                        "minimum_thin_volume_size_gb": 0,
                        "name": "CLARIION+APM00144937724+POOL+U+Temp Pool - Loaner Disks",
                        "native_guid": "CLARIION+APM00144937724+POOL+U+Temp Pool - Loaner Disks",
                        "num_resources": 0,
                        "operational_status": "READY",
                        "percent_subscribed": 1,
                        "percent_used": 1,
                        "pool_name": "Temp Pool - Loaner Disks",
                        "pool_service_type": "block",
                        "protocols": [
                            "FC"
                        ],
                        "raid_levels": [
                            "RAID5"
                        ],
                        "registration_status": "UNREGISTERED",
                        "remote": false,
                        "storage_system": {
                            "id": "urn:storageos:StorageSystem:10d14f9a-cc42-4286-becc-9a396bafee41:vdc1",
                            "link": {
                                "href": "/vdc/storage-systems/urn:storageos:StorageSystem:10d14f9a-cc42-4286-becc-9a396bafee41:vdc1",
                                "rel": "self"
                            }
                        },
                        "subscribed_gb": 29,
                        "supported_resource_types": "THIN_AND_THICK",
                        "tagged_varrays": [
                            "urn:storageos:VirtualArray:b60c49fd-4bdc-4752-ae20-7895868a9f8a:vdc1",
                            "urn:storageos:VirtualArray:4687b6ca-3741-4bc1-9e65-c6a6c072dad2:vdc1"
                        ],
                        "tags": [],
                        "thin_volume_preallocation_supported": false,
                        "tier_utilization_percentages": [
                            {
                                "name": "SATA",
                                "value": "100"
                            }
                        ],
                        "usable_gb": 17601,
                        "used_gb": 28,
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        }
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
