http://localhost:5984/
Welcome
http://localhost:5984/svtdev
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/vipr-project_acls.yaml
Checking for collect existence
http://localhost:5984/svtdev/_design/admin/_view/isnewcollect?reduce=true&startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]&group_level=2
http://localhost:5984/svtdev/_design/vipr-project/_view/acls?startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]
{
    "data": {
        "vipr-1": {
            "vipr-project": {
                "acls": {
                    "64483cc2-ecbc-4b09-b3e4-43df721ff597": {
                        "acl": [
                            {
                                "privilege": [
                                    "ALL"
                                ],
                                "subject_id": "svccloudauto@utility.pge.com"
                            },
                            {
                                "group": "ADMINCLOUD@UTILITY.PGE.COM",
                                "privilege": [
                                    "ALL"
                                ]
                            },
                            {
                                "privilege": [
                                    "ALL"
                                ],
                                "subject_id": "ixah@pge.com"
                            },
                            {
                                "privilege": [
                                    "ALL"
                                ],
                                "subject_id": "svcviprautomation@utility.pge.com"
                            }
                        ]
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
