http://localhost:5984/
Welcome
http://localhost:5984/svtdev
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: test/yaml/vro-misc_packages.yaml
Checking for collect existence
http://localhost:5984/svtdev/_design/admin/_view/isnewcollect?reduce=true&startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]&group_level=2
http://localhost:5984/svtdev/_design/vro-misc/_view/packages?startkey=["2016-09-13-10-35-57", "PGE"]&endkey=["2016-09-13-10-35-57", "PGE", {}]
{
    "data": {
        "vro-1": {
            "vro-misc": {
                "packages": {
                    "package1": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080815069925501508328a97b3aa1"
                            },
                            {
                                "name": "name",
                                "value": "addToGroupMember"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/addToGroupMember/",
                        "rel": "package"
                    },
                    "package10": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814f6051f0014f85ac8e0a28d7"
                            },
                            {
                                "name": "name",
                                "value": "com.emc.epc2.hotfix5"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "This is hotfix 5 package to address issues found in 2.5.1.0 EHC Foundation Package"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.emc.epc2.hotfix5/",
                        "rel": "package"
                    },
                    "package11": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814fdafa94014fe07215300c22"
                            },
                            {
                                "name": "name",
                                "value": "com.emc.epc2.iaas.patch01"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.emc.epc2.iaas.patch01/",
                        "rel": "package"
                    },
                    "package12": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814e3fdd98014e49f6a5734316"
                            },
                            {
                                "name": "name",
                                "value": "com.emc.otc.backup"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.emc.otc.backup/",
                        "rel": "package"
                    },
                    "package13": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb490eba00697"
                            },
                            {
                                "name": "name",
                                "value": "com.emc.vipr.workflows.sealed"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "EMC ViPR Workflows & Actions"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.emc.vipr.workflows.sealed/",
                        "rel": "package"
                    },
                    "package14": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff808081552c70a501552c7138d50000"
                            },
                            {
                                "name": "name",
                                "value": "com.F5.iControl"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.F5.iControl/",
                        "rel": "package"
                    },
                    "package15": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080815062cf97015062d04d8f0000"
                            },
                            {
                                "name": "name",
                                "value": "com.infoblox.ipam"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "The Infoblox IPAM Plug-in Package"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.infoblox.ipam/",
                        "rel": "package"
                    },
                    "package16": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080815062cf97015062d0800c01ac"
                            },
                            {
                                "name": "name",
                                "value": "com.infoblox.ipam.vcac"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "The Infoblox IPAM Plug-in vCAC Package"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.infoblox.ipam.vcac/",
                        "rel": "package"
                    },
                    "package17": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff80808150e255740150f9e87c6e65f4"
                            },
                            {
                                "name": "name",
                                "value": "com.misc"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.misc/",
                        "rel": "package"
                    },
                    "package18": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814d064d12014d06f5c80600e7"
                            },
                            {
                                "name": "name",
                                "value": "com.pge.onetimecharge"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "One Time Charge Workflows"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.pge.onetimecharge/",
                        "rel": "package"
                    },
                    "package19": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff80808150a7810e0150ba77ef86385e"
                            },
                            {
                                "name": "name",
                                "value": "com.pge.postprovisioning"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.pge.postprovisioning/",
                        "rel": "package"
                    },
                    "package2": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff80808150e255740150f9dee7d165f1"
                            },
                            {
                                "name": "name",
                                "value": "com.ahead.applicationServices"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.ahead.applicationServices/",
                        "rel": "package"
                    },
                    "package20": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814d1a45a2014d259d2bd70455"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.coe.ad.addcomputertooubystring"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.coe.ad.addcomputertooubystring/",
                        "rel": "package"
                    },
                    "package21": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814d1a45a2014d259d62280465"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.coe.ad.deletedisablecomputer"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.coe.ad.deletedisablecomputer/",
                        "rel": "package"
                    },
                    "package22": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080815086161001508f47893f2b96"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.coe.guestScriptManager"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "Create, store, run, distribute script to run in guest OS.\n\nSupports cmd / powershell / bash.\nProvides stdout and stderror.\nUse cmdAnsi from Pierre Torris. Donateware on www.ptorris.com"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.coe.guestScriptManager/",
                        "rel": "package"
                    },
                    "package23": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff808081552cdece01552d0980e90296"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.coe.plugin.dynamictypes.generator.v2"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "Dynamic Types Plug-in generator for REST APIs"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.coe.plugin.dynamictypes.generator.v2/",
                        "rel": "package"
                    },
                    "package24": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff808081552c70a501552cd37dbb057a"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.coe.plugin.dynamictypes.nsx.v2"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "Exported Dynamic Types Configuration"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.coe.plugin.dynamictypes.nsx.v2/",
                        "rel": "package"
                    },
                    "package25": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff808081552e454001555bbc0af8264e"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.coe.vcd.getvCenterVM"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.coe.vcd.getvCenterVM/",
                        "rel": "package"
                    },
                    "package26": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb49109a30973"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library/",
                        "rel": "package"
                    },
                    "package27": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb49099af0000"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.amqp"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "AMQP plug-in package"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.amqp/",
                        "rel": "package"
                    },
                    "package28": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb490e14305e9"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.configuration"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.configuration/",
                        "rel": "package"
                    },
                    "package29": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb3d841014cb3d8ca7e03fb"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.http-rest"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.http-rest/",
                        "rel": "package"
                    },
                    "package3": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff80808150617f9f015061969ea60181"
                            },
                            {
                                "name": "name",
                                "value": "com.ahead.pge"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.ahead.pge/",
                        "rel": "package"
                    },
                    "package30": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb4910db00a25"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.locking"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.locking/",
                        "rel": "package"
                    },
                    "package31": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb490f7d50758"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.mail"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "Contains the workflows of the Mail plugin"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.mail/",
                        "rel": "package"
                    },
                    "package32": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb490fee1080d"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.microsoft"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.microsoft/",
                        "rel": "package"
                    },
                    "package33": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb3d841014cb3d8a91a006b"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.powershell"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.powershell/",
                        "rel": "package"
                    },
                    "package34": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb3d841014cb3d8b0140113"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.powershell.converter"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "Contains logic for converting between PowerCLI objects and VC plugin objects.\nTransformations in both directions are possible."
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.powershell.converter/",
                        "rel": "package"
                    },
                    "package35": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb3d841014cb3d89bff0000"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.snmp"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.snmp/",
                        "rel": "package"
                    },
                    "package36": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb490d9aa0564"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.soap"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "SOAP plug-in package"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.soap/",
                        "rel": "package"
                    },
                    "package37": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb4915a3f1335"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.sql"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "Database package"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.sql/",
                        "rel": "package"
                    },
                    "package38": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb490fc7707e2"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.ssh"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.ssh/",
                        "rel": "package"
                    },
                    "package39": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb49112050aae"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.tagging"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.tagging/",
                        "rel": "package"
                    },
                    "package4": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814f24c685014f290819280cc3"
                            },
                            {
                                "name": "name",
                                "value": "com.cisco.ucs.mgr"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.cisco.ucs.mgr/",
                        "rel": "package"
                    },
                    "package40": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb490ae1d0095"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.vcac"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.vcac/",
                        "rel": "package"
                    },
                    "package41": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb3d841014cb3d8b5240143"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.vcaccafe"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "vCloud Automation Center package"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.vcaccafe/",
                        "rel": "package"
                    },
                    "package42": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb4911b800ac5"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.vcenter"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "VMware vCenter"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.vcenter/",
                        "rel": "package"
                    },
                    "package43": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb49105ed08f8"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.vco.management"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.vco.management/",
                        "rel": "package"
                    },
                    "package44": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb4910ec00a38"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.webview"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.webview/",
                        "rel": "package"
                    },
                    "package45": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb3d841014cb3d8ce280490"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.wfdocs"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "vCO Workflow Documentation Plugin"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.wfdocs/",
                        "rel": "package"
                    },
                    "package46": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb490a4a20064"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.library.xml"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.library.xml/",
                        "rel": "package"
                    },
                    "package47": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814d1195eb014d1196d7a40000"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.nsx"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "NSX Plug-in package"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.nsx/",
                        "rel": "package"
                    },
                    "package48": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb490f944077e"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.o11n.plugin.dynamictypes"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "Dynamic Types package"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.o11n.plugin.dynamictypes/",
                        "rel": "package"
                    },
                    "package49": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814dd91abc014dd91b4c070000"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.o11n.plugin.puppet"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "Puppet plug-in package"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.o11n.plugin.puppet/",
                        "rel": "package"
                    },
                    "package5": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814d064d12014d0b57edad02cd"
                            },
                            {
                                "name": "name",
                                "value": "com.dailyhypervisor.vcac.customhostname"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.dailyhypervisor.vcac.customhostname/",
                        "rel": "package"
                    },
                    "package50": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cda1522014cdcfb651f0006"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.pso.cryptojs"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.pso.cryptojs/",
                        "rel": "package"
                    },
                    "package51": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814d1a45a2014d268c5b230527"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.pso.vcac.proptoolkit"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.pso.vcac.proptoolkit/",
                        "rel": "package"
                    },
                    "package52": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff808081552cdece01552cee3c8900cb"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.sddc.f5.ltm.dynamictypes.v1.3"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "Exported Dynamic Types Configuration"
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.sddc.f5.ltm.dynamictypes.v1.3/",
                        "rel": "package"
                    },
                    "package53": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb49111130a8d"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.util"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.util/",
                        "rel": "package"
                    },
                    "package54": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb87bf40313f7"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.vcac.asd"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.vcac.asd/",
                        "rel": "package"
                    },
                    "package55": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cb49028014cb490a312004e"
                            },
                            {
                                "name": "name",
                                "value": "com.vmware.weboperator"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.vmware.weboperator/",
                        "rel": "package"
                    },
                    "package56": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cda1522014cdcfc0f640080"
                            },
                            {
                                "name": "name",
                                "value": "isAPICompartible"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/isAPICompartible/",
                        "rel": "package"
                    },
                    "package57": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff808081548a54090154f31c5aae34e3"
                            },
                            {
                                "name": "name",
                                "value": "org.company.OneCloudLab"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/org.company.OneCloudLab/",
                        "rel": "package"
                    },
                    "package58": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080815086161001508ac5c88c13d2"
                            },
                            {
                                "name": "name",
                                "value": "org.company.removeagent-rajiv"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/org.company.removeagent-rajiv/",
                        "rel": "package"
                    },
                    "package59": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814f2f7b3e014f4bca83217358"
                            },
                            {
                                "name": "name",
                                "value": "org.emc.cloud.pge"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/org.emc.cloud.pge/",
                        "rel": "package"
                    },
                    "package6": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814ff0b6d7014ffc65be0d55a2"
                            },
                            {
                                "name": "name",
                                "value": "com.emc.ehc.dr"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.emc.ehc.dr/",
                        "rel": "package"
                    },
                    "package60": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff808081548a540901550cb9929c364a"
                            },
                            {
                                "name": "name",
                                "value": "org.OneCloud.CoreProvExport"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/org.OneCloud.CoreProvExport/",
                        "rel": "package"
                    },
                    "package61": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff808081552e454001554b1df1e4101e"
                            },
                            {
                                "name": "name",
                                "value": "org.onecloud.elements"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/org.onecloud.elements/",
                        "rel": "package"
                    },
                    "package62": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff808081552e45400155501c8c3410dd"
                            },
                            {
                                "name": "name",
                                "value": "org.onecloud.infoblox"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/org.onecloud.infoblox/",
                        "rel": "package"
                    },
                    "package63": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff808081548a5409015512382f643801"
                            },
                            {
                                "name": "name",
                                "value": "org.OneCloud.ScratchPostExport"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/org.OneCloud.ScratchPostExport/",
                        "rel": "package"
                    },
                    "package64": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080815627f6cb015647d537572427"
                            },
                            {
                                "name": "name",
                                "value": "org.pge.HostNaming"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/org.pge.HostNaming/",
                        "rel": "package"
                    },
                    "package65": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff80808152ad7750015352b6558a6bc4"
                            },
                            {
                                "name": "name",
                                "value": "org.pge.onecloud"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/org.pge.onecloud/",
                        "rel": "package"
                    },
                    "package66": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff808081548a54090154f344ce5134fa"
                            },
                            {
                                "name": "name",
                                "value": "org.pge.onecloudpackages.backup1"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/org.pge.onecloudpackages.backup1/",
                        "rel": "package"
                    },
                    "package67": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff808081548a54090154f347b67234fc"
                            },
                            {
                                "name": "name",
                                "value": "org.pge.onecloudpackages.backup2"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/org.pge.onecloudpackages.backup2/",
                        "rel": "package"
                    },
                    "package68": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff80808155cc4b060155eadc7afd0ecd"
                            },
                            {
                                "name": "name",
                                "value": "org.pge.OneCloudRelease1.3"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/org.pge.OneCloudRelease1.3/",
                        "rel": "package"
                    },
                    "package69": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080815042caf0015043390aa702cb"
                            },
                            {
                                "name": "name",
                                "value": "org.vmware.GSS.KB"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/org.vmware.GSS.KB/",
                        "rel": "package"
                    },
                    "package7": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814fefd6fb014ff08dc8a60444"
                            },
                            {
                                "name": "name",
                                "value": "com.emc.ehc.foundation"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.emc.ehc.foundation/",
                        "rel": "package"
                    },
                    "package70": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814fdafa94014fdafb7ba00000"
                            },
                            {
                                "name": "name",
                                "value": "srm-package-5.8.0"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/srm-package-5.8.0/",
                        "rel": "package"
                    },
                    "package71": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff80808152ad77500152b410dccc0630"
                            },
                            {
                                "name": "name",
                                "value": "today.automate-it.vra"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/today.automate-it.vra/",
                        "rel": "package"
                    },
                    "package8": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814cda1522014cdcfeaab30084"
                            },
                            {
                                "name": "name",
                                "value": "com.emc.epc2"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": ""
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.emc.epc2/",
                        "rel": "package"
                    },
                    "package9": {
                        "attributes": [
                            {
                                "name": "id",
                                "value": "ff8080814d26bd05014d29d459cf02f1"
                            },
                            {
                                "name": "name",
                                "value": "com.emc.epc2.backup"
                            },
                            {
                                "name": "type",
                                "value": "Package"
                            },
                            {
                                "name": "description",
                                "value": "Data Protection package for EHC 2.5.1.  Contains workflows, actions, resource  files and other artefacts needed to run data Protection related workflows from VCAC."
                            }
                        ],
                        "href": "https://itcldrcorcapl01.utility.pge.com:8281/vco/api/packages/com.emc.epc2.backup/",
                        "rel": "package"
                    }
                },
                "svt_single": {}
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
