Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: yamldefs/all_vipr_cg.yaml
Checking for collect existence
{
    "data": {
        "vipr-1": {
            "vipr-block": {
                "consistency-groups": {
                    "09fce068-3c1b-4ecb-9326-e99e87fb4df3.json": {
                        "creation_time": 1440424856627,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:09fce068-3c1b-4ecb-9326-e99e87fb4df3:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:09fce068-3c1b-4ecb-9326-e99e87fb4df3:vdc1",
                            "rel": "self"
                        },
                        "name": "RC-Tenant-DR-Cluster01_vPool-VNX7724-RC-DR-Tier_1440424856159",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": []
                    },
                    "0b9d2e16-7c94-4e08-82fa-8c699939b3ce.json": {
                        "creation_time": 1440514469245,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:0b9d2e16-7c94-4e08-82fa-8c699939b3ce:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:0b9d2e16-7c94-4e08-82fa-8c699939b3ce:vdc1",
                            "rel": "self"
                        },
                        "name": "RC-Tenant-DR-Cluster01_vPool-VNX7724-RC-DR-Tier_1440514468763",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": []
                    },
                    "1a8b0b41-3578-40d4-a00b-82b17ea638f0.json": {
                        "creation_time": 1439500459464,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:1a8b0b41-3578-40d4-a00b-82b17ea638f0:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:1a8b0b41-3578-40d4-a00b-82b17ea638f0:vdc1",
                            "rel": "self"
                        },
                        "name": "RC-Tenant-DR-Cluster01_vPool-VNX7724-RC-DR-Tier_1439500459003",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": []
                    },
                    "1e7e15bc-6307-42c2-93b7-547f931d8960.json": {
                        "creation_time": 1463627909076,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:1e7e15bc-6307-42c2-93b7-547f931d8960:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:1e7e15bc-6307-42c2-93b7-547f931d8960:vdc1",
                            "rel": "self"
                        },
                        "link_status": "ENABLED",
                        "name": "CG_Rob_Test",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "rp_consistency_group_id": "366529159",
                        "rp_protection_system": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                        "system_consistency_groups": [
                            {
                                "name": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                                "value": "ViPR-CG_Rob_Test"
                            }
                        ],
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": [
                            {
                                "id": "urn:storageos:Volume:8ad2703a-66b0-4075-9c27-1629daaa4872:vdc1",
                                "link": {
                                    "href": "/block/volumes/urn:storageos:Volume:8ad2703a-66b0-4075-9c27-1629daaa4872:vdc1",
                                    "rel": "self"
                                }
                            }
                        ]
                    },
                    "2158001a-d278-4f40-b1e4-cba3d4be5254.json": {
                        "creation_time": 1461292303677,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:2158001a-d278-4f40-b1e4-cba3d4be5254:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:2158001a-d278-4f40-b1e4-cba3d4be5254:vdc1",
                            "rel": "self"
                        },
                        "link_status": "ENABLED",
                        "name": "Tier2_1461292301630",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "rp_consistency_group_id": "2123973208",
                        "rp_protection_system": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                        "system_consistency_groups": [
                            {
                                "name": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                                "value": "ViPR-Tier2_1461292301630"
                            }
                        ],
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": [
                            {
                                "id": "urn:storageos:Volume:fb9d8476-07ed-416e-829f-55cb171d7076:vdc1",
                                "link": {
                                    "href": "/block/volumes/urn:storageos:Volume:fb9d8476-07ed-416e-829f-55cb171d7076:vdc1",
                                    "rel": "self"
                                }
                            }
                        ]
                    },
                    "2c4733fe-a518-4935-87fb-b1831e69d146.json": {
                        "creation_time": 1461271221473,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:2c4733fe-a518-4935-87fb-b1831e69d146:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:2c4733fe-a518-4935-87fb-b1831e69d146:vdc1",
                            "rel": "self"
                        },
                        "link_status": "ENABLED",
                        "name": "Tier1_1461271216074",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "rp_consistency_group_id": "1101361153",
                        "rp_protection_system": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                        "system_consistency_groups": [
                            {
                                "name": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                                "value": "ViPR-Tier1_1461271216074"
                            }
                        ],
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": [
                            {
                                "id": "urn:storageos:Volume:e7da1abf-163a-47bf-ad87-9d5a3d3e213b:vdc1",
                                "link": {
                                    "href": "/block/volumes/urn:storageos:Volume:e7da1abf-163a-47bf-ad87-9d5a3d3e213b:vdc1",
                                    "rel": "self"
                                }
                            }
                        ]
                    },
                    "300ac1a8-1da8-48c1-bb61-6c4bb0405afd.json": {
                        "creation_time": 1441216140909,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:300ac1a8-1da8-48c1-bb61-6c4bb0405afd:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:300ac1a8-1da8-48c1-bb61-6c4bb0405afd:vdc1",
                            "rel": "self"
                        },
                        "link_status": "ENABLED",
                        "name": "RC-Tenant-DR-Cluster01_Tier1_1441216140442",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "rp_consistency_group_id": "689085890",
                        "rp_protection_system": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                        "system_consistency_groups": [
                            {
                                "name": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                                "value": "ViPR-RC-Tenant-DR-Cluster01_Tier1_1441216140442"
                            }
                        ],
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": [
                            {
                                "id": "urn:storageos:Volume:6b3d7970-6f0c-40e8-a625-98fede6bac87:vdc1",
                                "link": {
                                    "href": "/block/volumes/urn:storageos:Volume:6b3d7970-6f0c-40e8-a625-98fede6bac87:vdc1",
                                    "rel": "self"
                                }
                            }
                        ]
                    },
                    "342d6d1a-0c82-4ccf-8e5e-bf41f190dba7.json": {
                        "creation_time": 1439223197361,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:342d6d1a-0c82-4ccf-8e5e-bf41f190dba7:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:342d6d1a-0c82-4ccf-8e5e-bf41f190dba7:vdc1",
                            "rel": "self"
                        },
                        "name": "RC-Tenant-DR-Cluster01_vPool-VNX7724-RC-DR-Tier_1439223196872",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": []
                    },
                    "35ba1426-b1c7-43bb-9577-1bbfd89c9a70.json": {
                        "creation_time": 1439315304090,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:35ba1426-b1c7-43bb-9577-1bbfd89c9a70:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:35ba1426-b1c7-43bb-9577-1bbfd89c9a70:vdc1",
                            "rel": "self"
                        },
                        "name": "RC-Tenant-DR-Cluster01_vPool-VNX7724-RC-DR-Tier_1439315303684",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": []
                    },
                    "418ad962-892b-4de5-861b-51ed7dce079c.json": {
                        "creation_time": 1438882531450,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:418ad962-892b-4de5-861b-51ed7dce079c:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:418ad962-892b-4de5-861b-51ed7dce079c:vdc1",
                            "rel": "self"
                        },
                        "name": "RC-Tenant-DR-Cluster01_vPool-VNX7724-RC-DR-Tier_1438882531049",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": []
                    },
                    "4578949e-74e9-4907-9dc3-d4a9962662a3.json": {
                        "creation_time": 1461314426089,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:4578949e-74e9-4907-9dc3-d4a9962662a3:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:4578949e-74e9-4907-9dc3-d4a9962662a3:vdc1",
                            "rel": "self"
                        },
                        "link_status": "ENABLED",
                        "name": "Tier1_1461314420954",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "rp_consistency_group_id": "1060991872",
                        "rp_protection_system": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                        "system_consistency_groups": [
                            {
                                "name": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                                "value": "ViPR-Tier1_1461314420954"
                            }
                        ],
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": [
                            {
                                "id": "urn:storageos:Volume:36ae10e7-2279-4659-80f1-a02631b55d14:vdc1",
                                "link": {
                                    "href": "/block/volumes/urn:storageos:Volume:36ae10e7-2279-4659-80f1-a02631b55d14:vdc1",
                                    "rel": "self"
                                }
                            }
                        ]
                    },
                    "5a6235f2-5f9e-4bd8-b9f8-a7edf1f3d971.json": {
                        "creation_time": 1440787489072,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:5a6235f2-5f9e-4bd8-b9f8-a7edf1f3d971:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:5a6235f2-5f9e-4bd8-b9f8-a7edf1f3d971:vdc1",
                            "rel": "self"
                        },
                        "name": "RC-Tenant-DR-Cluster01_Tier1_1440787488582",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": []
                    },
                    "5f661c80-37a0-4f33-a327-f7c516091b61.json": {
                        "creation_time": 1450463566814,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:5f661c80-37a0-4f33-a327-f7c516091b61:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:5f661c80-37a0-4f33-a327-f7c516091b61:vdc1",
                            "rel": "self"
                        },
                        "link_status": "ENABLED",
                        "name": "Tier2_1450463564957",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "rp_consistency_group_id": "658922387",
                        "rp_protection_system": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                        "system_consistency_groups": [
                            {
                                "name": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                                "value": "ViPR-Tier2_1450463564957"
                            }
                        ],
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": [
                            {
                                "id": "urn:storageos:Volume:c8d7cfe5-e464-4862-9b24-41f2133ed739:vdc1",
                                "link": {
                                    "href": "/block/volumes/urn:storageos:Volume:c8d7cfe5-e464-4862-9b24-41f2133ed739:vdc1",
                                    "rel": "self"
                                }
                            }
                        ]
                    },
                    "65bbc4e5-6698-4ad4-a555-97efa141e73d.json": {
                        "creation_time": 1430164271345,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:65bbc4e5-6698-4ad4-a555-97efa141e73d:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:65bbc4e5-6698-4ad4-a555-97efa141e73d:vdc1",
                            "rel": "self"
                        },
                        "name": "CGforRC",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": []
                    },
                    "6aed4120-33b2-48ed-b0c4-dc4274ae7b56.json": {
                        "creation_time": 1461349976024,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:6aed4120-33b2-48ed-b0c4-dc4274ae7b56:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:6aed4120-33b2-48ed-b0c4-dc4274ae7b56:vdc1",
                            "rel": "self"
                        },
                        "link_status": "ENABLED",
                        "name": "Tier2_1461349974181",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "rp_consistency_group_id": "1327527686",
                        "rp_protection_system": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                        "system_consistency_groups": [
                            {
                                "name": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                                "value": "ViPR-Tier2_1461349974181"
                            }
                        ],
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": [
                            {
                                "id": "urn:storageos:Volume:f6e57552-f05d-445e-ae2a-c0040d623828:vdc1",
                                "link": {
                                    "href": "/block/volumes/urn:storageos:Volume:f6e57552-f05d-445e-ae2a-c0040d623828:vdc1",
                                    "rel": "self"
                                }
                            }
                        ]
                    },
                    "bd6bad22-4113-4155-8aea-994194485c4c.json": {
                        "creation_time": 1461291052152,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:bd6bad22-4113-4155-8aea-994194485c4c:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:bd6bad22-4113-4155-8aea-994194485c4c:vdc1",
                            "rel": "self"
                        },
                        "link_status": "ENABLED",
                        "name": "Tier1_1461291049851",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "rp_consistency_group_id": "115578816",
                        "rp_protection_system": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                        "system_consistency_groups": [
                            {
                                "name": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                                "value": "ViPR-Tier1_1461291049851"
                            }
                        ],
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": [
                            {
                                "id": "urn:storageos:Volume:e479fe95-3a5d-4446-a1c8-90d015a0c33b:vdc1",
                                "link": {
                                    "href": "/block/volumes/urn:storageos:Volume:e479fe95-3a5d-4446-a1c8-90d015a0c33b:vdc1",
                                    "rel": "self"
                                }
                            }
                        ]
                    },
                    "d096d72c-e2c9-4d82-8df2-c338e1c23108.json": {
                        "creation_time": 1461593414769,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:d096d72c-e2c9-4d82-8df2-c338e1c23108:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:d096d72c-e2c9-4d82-8df2-c338e1c23108:vdc1",
                            "rel": "self"
                        },
                        "link_status": "ENABLED",
                        "name": "Tier1_1461593412706",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "rp_consistency_group_id": "290065760",
                        "rp_protection_system": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                        "system_consistency_groups": [
                            {
                                "name": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                                "value": "ViPR-Tier1_1461593412706"
                            }
                        ],
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": [
                            {
                                "id": "urn:storageos:Volume:a948901a-002d-43ff-a4aa-f9c8d079064a:vdc1",
                                "link": {
                                    "href": "/block/volumes/urn:storageos:Volume:a948901a-002d-43ff-a4aa-f9c8d079064a:vdc1",
                                    "rel": "self"
                                }
                            }
                        ]
                    },
                    "d3b5046e-8a97-4966-aa65-a57b29619499.json": {
                        "creation_time": 1461592868001,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:d3b5046e-8a97-4966-aa65-a57b29619499:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:d3b5046e-8a97-4966-aa65-a57b29619499:vdc1",
                            "rel": "self"
                        },
                        "link_status": "ENABLED",
                        "name": "Tier2_1461592865949",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "rp_consistency_group_id": "1634401112",
                        "rp_protection_system": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                        "system_consistency_groups": [
                            {
                                "name": "urn:storageos:ProtectionSystem:a2f69393-413e-4558-ac34-9c11c0732fe4:vdc1",
                                "value": "ViPR-Tier2_1461592865949"
                            }
                        ],
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": [
                            {
                                "id": "urn:storageos:Volume:0e3c3e40-81b3-4a4d-b6ef-491919662f4a:vdc1",
                                "link": {
                                    "href": "/block/volumes/urn:storageos:Volume:0e3c3e40-81b3-4a4d-b6ef-491919662f4a:vdc1",
                                    "rel": "self"
                                }
                            }
                        ]
                    },
                    "edd140bf-f4bc-45c6-b3d2-6e83baa7ee57.json": {
                        "creation_time": 1440004101398,
                        "global": false,
                        "id": "urn:storageos:BlockConsistencyGroup:edd140bf-f4bc-45c6-b3d2-6e83baa7ee57:vdc1",
                        "inactive": false,
                        "internal": false,
                        "link": {
                            "href": "/block/consistency-groups/urn:storageos:BlockConsistencyGroup:edd140bf-f4bc-45c6-b3d2-6e83baa7ee57:vdc1",
                            "rel": "self"
                        },
                        "name": "RC-Tenant-DR-Cluster01_vPool-VNX7724-RC-DR-Tier_1440004100935",
                        "project": {
                            "id": "urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                            "link": {
                                "href": "/projects/urn:storageos:Project:64483cc2-ecbc-4b09-b3e4-43df721ff597:global",
                                "rel": "self"
                            }
                        },
                        "remote": false,
                        "tags": [],
                        "types": [
                            "RP"
                        ],
                        "vdc": {
                            "id": "urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                            "link": {
                                "href": "/vdc/urn:storageos:VirtualDataCenter:d103d756-584f-4b27-9339-301997423b1e:vdc1",
                                "rel": "self"
                            }
                        },
                        "volumes": []
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
