Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: yamldefs/nsx-appliance.yaml
Checking for collect existence
{
    "data": {
        "nsx-1": {
            "nsx": {
                "appliance-management": {
                    "backuprestore-backupsettings": {
                        "backupFrequency": {
                            "dayOfWeek": null,
                            "frequency": "DAILY",
                            "hourOfDay": 23,
                            "minuteOfHour": 55
                        },
                        "excludeTables": null,
                        "ftpSettings": {
                            "backupDirectory": "/root/nsx-mgr-backup",
                            "filenamePrefix": "fehc-",
                            "hostNameIPAddress": "itvirccldrep01.utility.pge.com",
                            "passPhrase": null,
                            "passiveMode": true,
                            "password": null,
                            "port": 22,
                            "transferProtocol": "SFTP",
                            "useEPRT": false,
                            "useEPSV": true,
                            "userName": "root"
                        }
                    },
                    "components": {
                        "NSX": {
                            "componentGroup": "NSXGRP",
                            "componentId": "NSX",
                            "description": "NSX Manager",
                            "enabled": true,
                            "name": "NSX Manager",
                            "showTechSupportLogs": true,
                            "status": "RUNNING",
                            "usedBy": [],
                            "uses": [
                                "VPOSTGRES",
                                "RABBITMQ"
                            ],
                            "versionInfo": {
                                "buildNumber": "3102213",
                                "majorVersion": "6",
                                "minorVersion": "1",
                                "patchVersion": "5"
                            }
                        },
                        "NSXAPIMGMT": {
                            "componentGroup": "NSXAPIGRP",
                            "componentId": "NSXAPIMGMT",
                            "description": "NSX API Manager",
                            "enabled": true,
                            "name": "NSX API Manager Service",
                            "showTechSupportLogs": true,
                            "status": "STOPPED",
                            "usedBy": [],
                            "uses": null,
                            "versionInfo": null
                        },
                        "RABBITMQ": {
                            "componentGroup": "COMMON",
                            "componentId": "RABBITMQ",
                            "description": "RabbitMQ - Messaging service",
                            "enabled": true,
                            "name": "RabbitMQ",
                            "showTechSupportLogs": false,
                            "status": "RUNNING",
                            "usedBy": [
                                "NSX"
                            ],
                            "uses": null,
                            "versionInfo": null
                        },
                        "SSH": {
                            "componentGroup": "SYSTEM",
                            "componentId": "SSH",
                            "description": "Secure Shell",
                            "enabled": true,
                            "name": "SSH Service",
                            "showTechSupportLogs": false,
                            "status": "RUNNING",
                            "usedBy": [],
                            "uses": null,
                            "versionInfo": null
                        },
                        "VPOSTGRES": {
                            "componentGroup": "COMMON",
                            "componentId": "VPOSTGRES",
                            "description": "vPostgres - Database service",
                            "enabled": true,
                            "name": "vPostgres",
                            "showTechSupportLogs": false,
                            "status": "RUNNING",
                            "usedBy": [
                                "NSX"
                            ],
                            "uses": null,
                            "versionInfo": null
                        }
                    },
                    "system-cpuinfo": {
                        "capacity": "2900 MHZ",
                        "freeCapacity": "1432 MHZ",
                        "totalNoOfCPUs": 4,
                        "usedCapacity": "1468 MHZ",
                        "usedPercentage": 51
                    }
                }
            }
        },
        "nsx-2": {
            "nsx": {
                "appliance-management": {
                    "backuprestore-backupsettings": {
                        "backupFrequency": {
                            "dayOfWeek": null,
                            "frequency": "DAILY",
                            "hourOfDay": 1,
                            "minuteOfHour": 0
                        },
                        "excludeTables": null,
                        "ftpSettings": {
                            "backupDirectory": "/root/nsx-mgr-backup",
                            "filenamePrefix": "fehc-",
                            "hostNameIPAddress": "itviffvbtrep01.utility.pge.com",
                            "passPhrase": null,
                            "passiveMode": true,
                            "password": null,
                            "port": 22,
                            "transferProtocol": "SFTP",
                            "useEPRT": false,
                            "useEPSV": true,
                            "userName": "root"
                        }
                    },
                    "components": {
                        "NSX": {
                            "componentGroup": "NSXGRP",
                            "componentId": "NSX",
                            "description": "NSX Manager",
                            "enabled": true,
                            "name": "NSX Manager",
                            "showTechSupportLogs": true,
                            "status": "RUNNING",
                            "usedBy": [],
                            "uses": [
                                "VPOSTGRES",
                                "RABBITMQ"
                            ],
                            "versionInfo": {
                                "buildNumber": "3102213",
                                "majorVersion": "6",
                                "minorVersion": "1",
                                "patchVersion": "5"
                            }
                        },
                        "NSXAPIMGMT": {
                            "componentGroup": "NSXAPIGRP",
                            "componentId": "NSXAPIMGMT",
                            "description": "NSX API Manager",
                            "enabled": true,
                            "name": "NSX API Manager Service",
                            "showTechSupportLogs": true,
                            "status": "STOPPED",
                            "usedBy": [],
                            "uses": null,
                            "versionInfo": null
                        },
                        "RABBITMQ": {
                            "componentGroup": "COMMON",
                            "componentId": "RABBITMQ",
                            "description": "RabbitMQ - Messaging service",
                            "enabled": true,
                            "name": "RabbitMQ",
                            "showTechSupportLogs": false,
                            "status": "RUNNING",
                            "usedBy": [
                                "NSX"
                            ],
                            "uses": null,
                            "versionInfo": null
                        },
                        "SSH": {
                            "componentGroup": "SYSTEM",
                            "componentId": "SSH",
                            "description": "Secure Shell",
                            "enabled": true,
                            "name": "SSH Service",
                            "showTechSupportLogs": false,
                            "status": "RUNNING",
                            "usedBy": [],
                            "uses": null,
                            "versionInfo": null
                        },
                        "VPOSTGRES": {
                            "componentGroup": "COMMON",
                            "componentId": "VPOSTGRES",
                            "description": "vPostgres - Database service",
                            "enabled": true,
                            "name": "vPostgres",
                            "showTechSupportLogs": false,
                            "status": "RUNNING",
                            "usedBy": [
                                "NSX"
                            ],
                            "uses": null,
                            "versionInfo": null
                        }
                    },
                    "system-cpuinfo": {
                        "capacity": "2900 MHZ",
                        "freeCapacity": "2155 MHZ",
                        "totalNoOfCPUs": 4,
                        "usedCapacity": "745 MHZ",
                        "usedPercentage": 26
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
