Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: yamldefs/vipr-tenant_tenants.yaml
Checking for collect existence
{
    "data": {
        "vipr-1": {
            "vipr-tenant": {
                "tenants": {
                    "70f84a12-6ce1-4b50-b616-06ac71c8f94f": {
                        "description": "Root Provider Tenant",
                        "name": "Provider Tenant"
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
