Welcome
Action: Generate
Collect: 2016-09-13-10-35-57
Client: PGE
YAML: yamldefs/vipr-project_projects.yaml
Checking for collect existence
{
    "data": {
        "vipr-1": {
            "vipr-project": {
                "projects": {
                    "64483cc2-ecbc-4b09-b3e4-43df721ff597": {
                        "name": "pge",
                        "owner": "root"
                    }
                }
            }
        }
    },
    "info": {
        "svt_client": "PGE",
        "svt_collect": "2016-09-13-10-35-57"
    }
}
